sonic-net/sonic-sairedis

lib/inc/sai_redis.h
lib/src/Makefile.am
lib/src/sai_redis_interfacequery.cpp
lib/src/sai_redis_tunnel.cpp
syncd/syncd.h
syncd/syncd_init.cpp

- added references to sai_tunnel_api in syncd.h, syncd_init.cpp, and
sai_redis.h
- added redis mapping of sai_tunnel_api by creating sai_redis_tunnel.cpp
and adding reference to sai_redis_interfacequery.cpp
- added sai_redis_tunnel.cpp to Makefile for compiling

Added full tunnel support

---

configure.ac
debian/rules
syncd/Makefile.am
syncd/syncd.cpp
syncd/syncd.h

Second attempt.
-lthrift is required in Makefile. rpcserver needs it too on link stage.

Introduce rpc server

---

debian/syncd.init

Fixed the same-MAC-address-bug by reading it from eth0 and writing into .profile file.

Fixed the same-MAC-address-bug.

---

meta/sai_meta_acl.cpp

Signed-off-by: Shuotian Cheng <shuche@microsoft.com>

[meta]: Fix metadata_sai_acl_bind_point_t_enum_values_count to 5

---

debian/syncd.init
etc/syncd.d/ingrasys_s9100.profile

Signed-off-by: Sam Yang <yang.kaiyu@gmail.com>

syncd.init: Add ingrasys switch s9100

---

meta/sai_meta.cpp

Signed-off-by: Shuotian Cheng <shuche@microsoft.com>

[meta]: Fix typo "don't exists" -> "doesn't exist"

---

syncd/syncd_counters.cpp

- Remove counter collection timer
- Change counter thread log to INFO

[syncd]: Remove SWSS_LOG_TIMER and update log level

---

syncd/syncd.cpp

Enable logger linking to DB

---

syncd/scripts/syncd_init_common.sh

Adding Marvell staff to syncd_init_common.sh.

Add Marvell ASIC.

---

syncd/syncd.cpp
syncd/syncd.h
syncd/syncd_counters.cpp
syncd/syncd_notifications.cpp
syncd/syncd_reinit.cpp

Add separate lock for notification and reuse
global syncd lock to protect only db access

Fix thread deadlock issue

---

meta/saiserialize.cpp

[saiserialize]: Make delete[] match new[]

---

syncd/Makefile.am
syncd/syncd.cpp
syncd/syncd_flex_counter.cpp
syncd/syncd_flex_counter.h
tests/Makefile.am

[syncd]: Rename PFC WD to Flex Counter

---

vslib/src/sai_vs_hostintf.cpp

[252] Create hostif fails on vslib when no tap device is used

---

meta/saiserialize.cpp
meta/saiserialize.h
syncd/tests.cpp
vslib/inc/sai_vs.h
vslib/inc/sai_vs_state.h
vslib/src/Makefile.am
vslib/src/sai_vs_hostintf.cpp
vslib/src/sai_vs_switch.cpp
vslib/src/sai_vs_switch_BCM56850.cpp
vslib/src/sai_vs_switch_MLNX2700.cpp

[254] Add port state change notification support to vslib

---

lib/inc/sai_redis.h
lib/inc/sairedis.h
lib/src/sai_redis_fdb.cpp
lib/src/sai_redis_generic_remove.cpp
lib/src/sai_redis_nexthopgroup.cpp
lib/src/sai_redis_route.cpp
syncd/syncd.cpp
syncd/tests.cpp

Implement bulk create/remove for nhgm/route/fdb

---

vslib/inc/sai_vs.h
vslib/src/sai_vs_interfacequery.cpp
vslib/src/tests.cpp

For easier testing when using python framework

Add virtual switch unittests channel via redis

---

syncd/syncd_flex_counter.cpp

[FlexCounter]: Use fine-grained locks.

---

syncd/syncd_flex_counter.cpp
syncd/syncd_flex_counter.h

Check plugin lists along with counter IDs lists
before trying to remove FC instance

[flex_counter]: Check if plugin lists are empty

---

syncd/syncd_flex_counter.cpp
syncd/syncd_flex_counter.h

[flex_counter]: Include plugins delay into poll correction

---

syncd/syncd_flex_counter.cpp
syncd/syncd_flex_counter.h

[flexcounter]: query port supported counters once for all instances

---

syncd/syncd_flex_counter.cpp

[flexCounter]: Enable redis pipeline in flex counter table

---

syncd/syncd_flex_counter.cpp

Required to make sonic-sairedis work with https://github.com/Azure/sonic-swss-common/pull/190

Align with swss-common table name separator changes

---

syncd/scripts/syncd_init_common.sh

**- What I did**
Updated Cavium syncd config: hwsku and fast reboot.

[cavm]: Updated Cavium syncd config: hwsku and fast reboot.

---

syncd/syncd.cpp
syncd/syncd_flex_counter.cpp

Signed-off-by: Volodymyr Samotiy <volodymyrs@mellanox.com>

[syncd]: Clean-up log messages

---

lib/src/sai_redis_routerintf.cpp
vslib/src/sai_vs_router_interface.cpp

Signed-off-by: Ying Xie <ying.xie@microsoft.com>

[SAI] upgrade to SAI header version v1.3.3

---

meta/sai_meta.cpp

Signed-off-by: Shu0T1an ChenG <shuche@microsoft.com>

[saimeta]: Fix typo: > then -> >; don't exists -> doesn't exist

---

syncd/scripts/syncd_init_common.sh

So warm start swss is possible.

Use syncd -u option

---

syncd/syncd.cpp

…ction
* add while() loop to handle entries when buffer is Not empty

sairedis: add while loop to make syncd processEvent() handle as many entries as possible in one event call

---

vslib/src/sai_vs_hostintf.cpp

In VS test, we found below errors when implementing a new FDB notification test.
```
Sep 11 15:39:28.880133 346360b6760c DEBUG /syncd: :- findBridgeVlanForPortVlan: found bridge port oid:0x3a00000022 for port oid:0x100000011
Sep 11 15:39:28.880136 346360b6760c DEBUG /syncd: :> vs_generic_get: enter
Sep 11 15:39:28.880138 346360b6760c DEBUG /syncd: :> sai_serialize_object_id: enter
Sep 11 15:39:28.880141 346360b6760c DEBUG /syncd: :< sai_serialize_object_id: exit
Sep 11 15:39:28.880143 346360b6760c DEBUG /syncd: :> sai_switch_id_query: enter
Sep 11 15:39:28.880145 346360b6760c DEBUG /syncd: :> sai_object_type_query: enter
Sep 11 15:39:28.880147 346360b6760c DEBUG /syncd: :< sai_object_type_query: exit
Sep 11 15:39:28.880149 346360b6760c DEBUG /syncd: :> vs_construct_object_id: enter
Sep 11 …
```

Fix findBridgeVlanForPortVlan for 1Q bridge

---

meta/sai_serialize.h
meta/saiserialize.cpp
syncd/syncd.cpp
syncd/syncd_flex_counter.cpp
syncd/syncd_flex_counter.h

Add code for Watermark feature
[High Level Design Document](https://github.com/Azure/SONiC/blob/694754ac31c77724f43458e2779b552223791974/doc/watermarks_HLD.md)
*What I did*
- Extended Flex counter to collect PG stats
- Extended Flex counter to generate PG MAPS(PG to port, PG to index, PG to name)
- Read and clear stats mode support

[watarmark] add watermark support

---

meta/sai_meta.cpp
meta/sai_meta.h
meta/sai_serialize.h
meta/saiserialize.cpp
vslib/inc/sai_vs.h
vslib/src/Makefile.am
vslib/src/sai_vs_bfd.cpp
vslib/src/sai_vs_generic_create.cpp
vslib/src/sai_vs_generic_get.cpp
vslib/src/sai_vs_generic_remove.cpp
vslib/src/sai_vs_generic_set.cpp
vslib/src/sai_vs_interfacequery.cpp
vslib/src/sai_vs_ipmc.cpp
vslib/src/sai_vs_ipmc_group.cpp
vslib/src/sai_vs_l2mc.cpp
vslib/src/sai_vs_l2mcgroup.cpp
vslib/src/sai_vs_mcastfdb.cpp
vslib/src/sai_vs_mpls.cpp
vslib/src/sai_vs_rpfgroup.cpp
vslib/src/sai_vs_segmentroute.cpp
vslib/src/sai_vs_tam.cpp
vslib/src/sai_vs_uburst.cpp

Add missing object types to virtual switch

---

syncd/syncd_hard_reinit.cpp

Signed-off-by: Ying Xie <ying.xie@microsoft.com>

[syncd] re-establish notifications after warm boot

---

syncd/syncd.cpp

Signed-off-by: Ying Xie <ying.xie@microsoft.com>

[syncd] provide docker name when checking warm restart

---

.gitignore

Signed-off-by: Shu0T1an ChenG <shuche@microsoft.com>

[.gitignore]: Add more files in .gitignore file

---

meta/sai_meta.cpp
meta/saiserialize.cpp

Signed-off-by: Marian Pritsak <marianp@mellanox.com>

[meta]: Add support for ip prefix

---

lib/inc/sai_redis.h
lib/src/Makefile.am
lib/src/sai_redis_bmtor.cpp
lib/src/sai_redis_interfacequery.cpp

Add support for saiexperimentalbmtor
Signed-off-by: Marian Pritsak <marianp@mellanox.com>

Update SAI pointer

---

meta/sai_serialize.h
meta/saiserialize.cpp
syncd/syncd.cpp
syncd/syncd_flex_counter.cpp
syncd/syncd_flex_counter.h
tests/aspell.en.pws

Enable FC to poll RIF stats
Signed-off-by: Mykola Faryma <mykolaf@mellanox.com>

[flex counter] handle router interface stats

---

syncd/syncd_applyview.cpp

Add more specific comparison logic for matching ingress ACL and matching buffer profile on queues and ingress priority groups

Add more specific logic for ingress ACL and buffer profile

---

syncd/syncd_saiswitch.cpp

Signed-off-by: Guohan Lu <gulv@microsoft.com>

[syncd]: support query port with 8 lanes (400G)

---

syncd/syncd_applyview.cpp

As part of upgrading syncd docker to stretch

Fix compilation issues in stretch docker with gcc-6.3

---

vslib/inc/sai_vs.h
vslib/inc/sai_vs_internal.h
vslib/inc/sai_vs_state.h
vslib/src/Makefile.am
vslib/src/sai_vs_bmtor.cpp
vslib/src/sai_vs_generic_create.cpp
vslib/src/sai_vs_interfacequery.cpp

Signed-off-by: Volodymyr Samotiy <volodymyrs@mellanox.com>

[vslib]: Add support of bitmap VNET (bmtor) SAI API

---

meta/sai_serialize.h
meta/saiserialize.cpp

Signed-off-by: Wenda Ni <wenni@microsoft.com>

Add metadata serialization support for buffer pool stats

---

lib/src/sai_redis_bmtor.cpp
vslib/src/sai_vs_bmtor.cpp

Signed-off-by: Marian Pritsak <marianp@mellanox.com>

[SAI] Advance submodule to v1.4.1

---

meta/sai_meta.cpp
meta/saiserialize.cpp

[meta] add support for SAI_ATTR_VALUE_TYPE_ACL_CAPABILITY

---

syncd/scripts/syncd_init_common.sh

Added environment variable for python
Signed-off-by: Myron Sosyak <msosyak@barefootnetworks.com>

[syncd] Fixed config_syncd_barefoot function

---

syncd/scripts/syncd_init_common.sh

Signed-off-by: Andriy Kokhan <akokhan@barefootnetworks.com>

Fixed p4 profile change for BFN platform

---

saisdkdump/saisdkdump.cpp

Signed-off-by: Volodymyr Samotiy <volodymyrs@mellanox.com>

[saisdkdump]: Fix dump generation crash

---

syncd/scripts/syncd_init_common.sh

Signed-off-by: Tony Titus ttitus@innovium.com

[syncd] Add support for Innovium platform

---

lib/src/sai_redis_generic_create.cpp
lib/src/sai_redis_generic_remove.cpp
lib/src/sai_redis_generic_set.cpp

* fix typo in previous added syncMode related codes

fix found typo in new added syncMode related codes

---

lib/src/sai_redis_switch.cpp
lib/src/sai_redis_tam.cpp
vslib/src/sai_vs_switch.cpp
vslib/src/sai_vs_tam.cpp

Signed-off-by: Wenda Ni <wenni@microsoft.com>

Advance SAI reference pointer to v1.5.0

---

saidiscovery/Makefile.am
saisdkdump/Makefile.am
syncd/Makefile.am

Signed-off-by: Andriy Kokhan <akokhan@barefootnetworks.com>
**What I did**
Removed BFN specific code from Makefile.am files
Migration from libswitchsai to libsai
Private build of BFN target

Cleanup Makrefile.am from BFN specific code

---

lib/src/sai_redis_port.cpp
vslib/src/sai_vs_port.cpp

* Defining new serdes attributes (#1002)
* Improve debug counter enums (#1006)
* Introduce buffer pool type SAI_BUFFER_POOL_TYPE_BOTH (#986)
Signed-off-by: Danny Allen <daall@microsoft.com>

[SAI] Update SAI submodule to v1.5.1

---

vslib/inc/sai_vs_state.h
vslib/src/sai_vs_hostintf.cpp
vslib/src/sai_vs_switch.cpp

Also switched from blocking read and recvmsg to support select operation and event notifier to gracefully join thread on syncd exit.

Add support for remove hostif when using tap device

---

syncd/syncd.cpp

Signed-off-by: Danny Allen <daall@microsoft.com>

[syncd] Fix off-by-one error for attribute enum values query

---

vslib/src/sai_vs_hostintf.cpp

Also will prevent print warnings on finding bridge when port is part of
LAG, it will then try to find bridge for that LAG if it's not rif based.

Don't learn fdb entries on LAG when rif based

---

tests/mlnx.pl

For new Perl @INC path must be updated for current directory module
lookup

Fix mlnx.pl script for perl include local directory

---

syncd/syncd.cpp

Signed-off-by: Danny Allen <daall@microsoft.com>

[syncd] Update syncd to expect correct object query message

---

meta/sai_meta.cpp

In normal operation orch agent should query or create all bridge, vlan and bridge port, so we should not get this message. Let's put it as warning for better visibility. Most likely if this happen  there is a vendor bug in SAI and we should also see warnings or errors reported from syncd in logs.
Originally the solution was to create the object and then continue to learn fdb_entry, which causes other issue on SONiC. Consider the following scenario:
1. SWITCH ASIC reports fdb learnt on a certain vlan/port
2. Create object for the vlan/port
3. Learn the mac address, which will increase the reference count of port
4. On SONiC, all port will be removed from bridge during creating switch, which is done by calling removeDefaultBridgePorts. It contains a logic of checking the reference number of …

[meta/sai_meta]Fix the issue that fdb learnt during create switch fails removeDefaultBridgePorts - 201911

---

configure.ac

add swss-common-{inc,lib} to specify the prefix of swss-common library

---

lgtm.yml

[lgtm]: add lgtm static analysis configuration

---

vslib/src/SwitchStateBase.cpp
vslib/src/SwitchStateBaseHostif.cpp

[vs]: set mtu only on the physical port

---

syncd/scripts/syncd_init_common.sh
syncd/tests.cpp
vslib/src/tests.cpp

* correct multiDB API/cmd in new added codes

[MultiDB] use new multiDB API/cmd in new added codes

---

configure.ac
python/setup.py.in

[build]: support lgtm build for python library

---

saiplayer/CommandLineOptions.cpp
saiplayer/CommandLineOptions.h
saiplayer/CommandLineOptionsParser.cpp
saiplayer/SaiPlayer.cpp
syncd/RedisClient.cpp
syncd/RedisClient.h
syncd/Syncd.cpp
syncd/Syncd.h
tests/brcm.pl
tests/utils.pm

Will require https://github.com/Azure/sonic-swss-common/pull/344 to work

Add synchronous mode to sairedis library

---

syncd/FlexCounter.cpp

* use get API to obtain dbid instead of hardcode value

[MultiDB] use get API to obtain dbid instead of hardcode value

---

saiplayer/CommandLineOptions.cpp
saiplayer/CommandLineOptions.h
saiplayer/CommandLineOptionsParser.cpp
saiplayer/SaiPlayer.cpp
saiplayer/SaiPlayer.h

Will allow to read context_config.ini file

[saiplayer] Add support for profile.ini

---

lib/inc/sai_redis.h
lib/src/Makefile.am
lib/src/sai_redis_interfacequery.cpp
lib/src/sai_redis_system_port.cpp
vslib/inc/sai_vs.h
vslib/src/Makefile.am
vslib/src/sai_vs_interfacequery.cpp
vslib/src/sai_vs_system_port.cpp

Change log:
```
- Update SAI VoQ support (#1107) …
- Voq system (#1081) …
- [meta] Add support for ignored enum values (#1099)
- TPID SAI proposal (#1089) …
- ACL GRE key match (#1076) …
- Add IPv6 NS and NA Traps (#1092) …
- MACsec flow list attribute added in MACsec object (#1095) …
- Add Enterprise Number for IPFIX Report Type (#1072) …
- Provide TTL and QoS treatment during MPLS encap and decap (#1079)
- Create and Set for Tunnel Attributes (#1086) …
```

[submodule update] SAI submodule update to v1.6.3

---

syncd/Syncd.cpp

Fix notification on shutdown request

[syncd] Fix notification on shutdown request

---

lib/inc/RedisVidIndexGenerator.h
lib/src/RedisVidIndexGenerator.cpp
syncd/tests.cpp

After this PR: https://github.com/Azure/sonic-swss-common/pull/382
*Please move submodules together to include above commit*

Replace RedisClient with DBConnector

---

meta/saiserialize.cpp

This will speed up entire pipeline by 50%

[meta] Add dedicated (de)serialize methods for route_entry 

---

vslib/src/SwitchStateBaseFdb.cpp

Respect fdb learning mode on virtual switch, mainly for disable learning mode on bridge port, so when a new packet will arrive, no fdb event notification will be sent, to prevent sairedis receive that notification and prevent metadata learning (snoop) bridge port oid. Notification will be sent only when learning is enabled at the first packet for that particular bridge port/mac/vlan.

[vs] Respect fdb learning mode on VS

---

lib/inc/PerformanceIntervalTimer.h
lib/src/Makefile.am
lib/src/PerformanceIntervalTimer.cpp
lib/src/RedisRemoteSaiInterface.cpp
lib/src/tests.cpp
saiplayer/SaiPlayer.cpp
saiplayer/SaiPlayer.h
syncd/Syncd.cpp
syncd/ZeroMQSelectableChannel.cpp
vslib/src/Makefile.am
vslib/src/VirtualSwitchSaiInterface.cpp

This PR requires https://github.com/Azure/sonic-sairedis/pull/659

Add support for saiplayer bulk API and add performance timers

---

syncd/scripts/gbsyncd_startup.py

[gbsyncd]: add missing python dependency

---

saiplayer/SaiPlayer.cpp

[saiplayer] Fix log messages

---

meta/Meta.cpp
meta/sai_serialize.h
meta/saiserialize.cpp

Add MACsec meta methods

---

lib/src/Recorder.cpp
saisdkdump/saisdkdump.cpp
syncd/PortMapParser.cpp

Fix LGTM localtime function warnings

---

lib/src/Sai.cpp
saidump/saidump.cpp
syncd/SaiSwitch.cpp
syncd/ServiceMethodTable.cpp
syncd/SwitchNotifications.cpp
vslib/inc/SwitchStateBase.h
vslib/src/SwitchStateBase.cpp

Remove global functions and variables, make them static.

Code clean refactor

---

vslib/inc/SwitchStateBase.h
vslib/src/SwitchStateBase.cpp

findObjects: Find out objects that have expected attribute
dumpObject: dump object attributes to vector<sai_attributes_t> according to specified object id

[vslib]Add helper functions, findObjects and dumpObject

---

vslib/inc/MACsecAttr.h
vslib/inc/MACsecManager.h
vslib/src/MACsecAttr.cpp
vslib/src/MACsecManager.cpp

MACsec Manager provides some function to manage Linux MACsec device ,interacts with `HostInterfaceInfo` via MACsec filters that added at https://github.com/Azure/sonic-sairedis/pull/713 and manager MACsec forwarder that added at https://github.com/Azure/sonic-sairedis/pull/714

[vslib]Add MACsec Manager

---

lib/src/sai_redis_fdb.cpp
syncd/tests.cpp

Use SAI bulk methods since they are already present in the headers

[sairedis] Remove custom bulk fdb methods

---

README.md

Updated installation steps
Added missing required packages
Signed-off-by: Alexandru Banu <Alexandru.Banu@metaswitch.com>

[README.md] Update installation steps

---

vslib/src/VirtualSwitchSaiInterfaceFdb.cpp

[vs] Support flush entry type all on virtual switch

---

meta/Meta.h
vslib/src/SaiUnittests.cpp

[vs] Use meta class instead info when using unittests

---

syncd/PortMap.cpp
syncd/PortMap.h
syncd/PortMapParser.cpp
syncd/PortMapParser.h
syncd/TimerWatchdog.cpp
syncd/TimerWatchdog.h

[syncd] Move syncd classes to syncd namespace

---

meta/Meta.cpp

[meta] Fix stat_mode enums to sai_bulk_op_error_mode_t

---

azure-pipelines.yml

[ci]: build arm64

---

syncd/AsicOperation.h
syncd/AsicView.cpp
syncd/ComparisonLogic.cpp

For better debugging purposes.

[syncd] Comparison logic log also current attr value on set operation

---

azure-pipelines.yml

[ci]: download artifacts from master branch

---

lib/src/NotificationFactory.cpp
lib/src/RedisRemoteSaiInterface.cpp
lib/src/VirtualObjectIdManager.cpp
lib/src/ZeroMQChannel.cpp
meta/AttrKeyMap.cpp
meta/Meta.cpp
meta/OidRefCounter.cpp
meta/saiserialize.cpp
meta/tests.cpp
syncd/AsicView.cpp
syncd/BestCandidateFinder.cpp
syncd/ComparisonLogic.cpp
syncd/NotificationProcessor.cpp
syncd/RedisClient.cpp
syncd/RequestShutdownCommandLineOptionsParser.cpp
syncd/SaiAttr.cpp
syncd/SingleReiniter.cpp
syncd/Syncd.cpp
syncd/VendorSai.cpp
syncd/ZeroMQSelectableChannel.cpp
vslib/src/CorePortIndexMap.cpp
vslib/src/NetMsgRegistrar.cpp
vslib/src/SaiUnittests.cpp
vslib/src/SwitchState.cpp

Signed-off-by: liat-grozovik <liatg@nvidia.com>

Spell check fixes

---

syncd/BestCandidateFinder.cpp
syncd/BestCandidateFinder.h
syncd/ComparisonLogic.cpp
syncd/ComparisonLogic.h
syncd/Makefile.am
syncd/SaiSwitch.cpp
syncd/SaiSwitch.h
syncd/SaiSwitchInterface.cpp
syncd/SaiSwitchInterface.h

This class will be needed for future asic compare.

[syncd] Create base class SaiSwitchInterface

---

lib/inc/VirtualObjectIdManager.h
lib/src/Sai.cpp
lib/src/VirtualObjectIdManager.cpp
syncd/VidManager.cpp
syncd/VidManager.h
vslib/inc/RealObjectIdManager.h

Will be needed for asic compare.

[sairedis][syncd] VidManager add updateIndex method

---

.azure-pipelines/build-docker-sonic-vs-template.yml
.azure-pipelines/build-swss-template.yml
.azure-pipelines/build-template.yml
.azure-pipelines/build_and_install_module.sh
.azure-pipelines/docker-sonic-vs/Dockerfile
.azure-pipelines/test-docker-sonic-vs-template.yml
azure-pipelines.yml

[ci]: add vstest

---

syncd/scripts/syncd_init_common.sh

Allow SAI xml dynamic config override when template is defined

[Mellanox] Add SAI template config support

---

lib/src/sai_redis_interfacequery.cpp
lib/src/sai_redis_tam.cpp

Export presence is needed by pyext module.

[sairedis] Add missing SAI interface apis

---

vslib/src/VirtualSwitchSaiInterface.cpp

Signed-off-by: Stepan Blyschak <stepanb@nvidia.com>

[vslib] implement query for SAI_DEBUG_COUNTER_TYPE enum values

---

syncd/scripts/syncd_init_common.sh

Signed-off-by: Venkat Garigipati <venkatg@cisco.com>

Remove redundant mention of platform cisco-8000

---

vslib/inc/SwitchStateBase.h
vslib/src/SwitchStateBase.cpp

[vs]: Add refreshing macsec sa stat

---

lib/inc/ContextConfig.h
lib/src/ContextConfig.cpp
lib/src/ContextConfigContainer.cpp

Will help eliminate mistakes in context_config.json file

[sairedis] Add context config fields conflict check

---

vslib/src/SwitchStateBaseFdb.cpp

Signed-off-by: Wenda Ni <wonda.ni@gmail.com>

[vslib] Clean SwitchStateBase::send_fdb_event_notification

---

pyext/py2/Makefile.am
pyext/py3/Makefile.am

Note which source files are auto generated for python modules

[pyext] Add built sources list to makefiles

---

syncd/Makefile.am
syncd/main.cpp

* Register stack dumper for syncd crashes
Signed-off-by: Alexandru Banu <v-albanu@microsoft.com>

[syncd] Add stack dumper for better crash reports

---

syncd/scripts/syncd_init_common.sh

Signed-off by: Thomas Cappleman <tcappleman@microsoft.com>

[soda] Add support for SODA data plane

---

syncd/RequestShutdownCommandLineOptionsParser.cpp

Unrecognized command was crashing sigsegv, since option index zero was missing ad the end in opt configuration

[syncd] Refactor syncd request shutdown command line parser

---

.azure-pipelines/build_and_install_module.sh

Fix the option missing in kernel config issue
The installing module step will hang forever before the issue fixed.

[ci]: Fix the option missing in kernel config issue

---

syncd/SaiSwitch.cpp

[syncd] Add workaround for warm boot new objects

---

.azure-pipelines/build-template.yml
azure-pipelines.yml

[ci]: use native armhf and arm64 pool

---

lib/inc/NotificationBfdSessionStateChange.h
lib/src/Makefile.am
lib/src/NotificationBfdSessionStateChange.cpp
lib/src/NotificationFactory.cpp
lib/src/Switch.cpp
meta/Meta.cpp
meta/Meta.h
meta/sai_serialize.h
meta/saiserialize.cpp
pyext/pysairedis.cpp
saiplayer/SaiPlayer.cpp
saiplayer/SaiPlayer.h
syncd/NotificationHandler.cpp
syncd/NotificationHandler.h
syncd/NotificationProcessor.cpp
syncd/NotificationProcessor.h
syncd/SwitchNotifications.cpp
syncd/SwitchNotifications.h
syncd/Syncd.cpp
tests/aspell.en.pws
vslib/src/Switch.cpp
vslib/src/SwitchStateBase.cpp

Include changes of https://github.com/Azure/sonic-sairedis/pull/903 in the 202012 branch
Add sairedis and syncd support to handle and send back bfd session state change notifications.

[202012] Add support for BFD notification

---

syncd/Syncd.cpp

Cherry-pick: #908 to 202012 branch.
Signed-off-by: Stephen Sun stephens@nvidia.com

Change the log severity leve from ERROR to NOTICE if getStatus is not supported by vendor (#908)

---

.azure-pipelines/test-docker-sonic-vs-template.yml

Cherry pick PRs https://github.com/Azure/sonic-swss/pull/2142, https://github.com/Azure/sonic-swss/pull/2138

[ci] pipeline fixes for VS test

---

lib/sai_redis_nexthopgroup.cpp
lib/sai_redis_port.cpp
syncd/SwitchNotifications.h
vslib/sai_vs_nexthopgroup.cpp
vslib/sai_vs_port.cpp

Signed-off-by: Vineet Mittal <vineetmittal@microsoft.com>

[SAI submodule update] Enable support for SAI v1.10.2

---

lib/inc/sai_redis.h
lib/src/sai_redis_switch.cpp
lib/src/sai_redis_tunnel.cpp
vslib/inc/sai_vs.h
vslib/src/sai_vs_switch.cpp
vslib/src/sai_vs_tunnel.cpp

Changes include
```
c460675 [SAI]Fix build in v1.7 and remove unnecessary change (#1468)
bfaaa0e Tunnel Scoped TC MAP and Remarking (#1452)
```
Signed-off-by: bingwang <bingwang@microsoft.com>

Advance submodule SAI for 202012 branch

---

.azure-pipelines/build-docker-sonic-vs-template.yml
.azure-pipelines/build-swss-template.yml
.azure-pipelines/build-template.yml
.azure-pipelines/test-docker-sonic-vs-template.yml
azure-pipelines.yml

cherry-pick from master branch:
https://github.com/Azure/sonic-sairedis/pull/1040

[ci] Paralize azure pipeline

---

.azure-pipelines/build-docker-sonic-vs-template.yml
.azure-pipelines/build-swss-template.yml
.azure-pipelines/build-template.yml
.azure-pipelines/test-docker-sonic-vs-template.yml
azure-pipelines.yml

Cherry-pick a PR to enable CI pipeline:
https://github.com/Azure/sonic-sairedis/pull/1040

[ci] Cherry-pick Paralize azure pipeline from master

---

configure.ac
syncd/VendorSai.cpp

sai_query_api_version may not be availabe in vendor SAI library.

---

syncd/scripts/syncd_init_common.sh

Signed-off-by: Venkat Garigipati <venkatg@cisco.com>

Support For CISCO debug-shell in syncd-container

---

syncd/scripts/syncd_init_common.sh

Signed-off-by: Venkat Garigipati <venkatg@cisco.com>

Enable cisco debug shell by default

---

syncd/scripts/syncd_init_common.sh

Signed-off-by: Venkat Garigipati <venkatg@cisco.com>

Remove duplicate cisco-8000 functions and call to those functions

---

lib/Recorder.cpp

Update recording file if not start recording was performed previously

[sairedis] Fix reopen recoding file

---

lgtm.yml

Needed to build swss-common in lgtm container

[lgtm] Add uuid library

---

syncd/FlexCounter.cpp

Updating logging level for unsupported counters messages as it keeps on filling syslogs.

Updated logging level for un-supported counters messages

---

.azure-pipelines/build-template.yml

* Test using stock gcovr
Signed-off-by: Saikrishna Arcot <sarcot@microsoft.com>
* Use gcovr 5.2
Signed-off-by: Saikrishna Arcot <sarcot@microsoft.com>
Signed-off-by: Saikrishna Arcot <sarcot@microsoft.com>

[202205] Switch to using stock gcovr 5.2 (#1174)

---

.azure-pipelines/build-docker-sonic-vs-template.yml
.azure-pipelines/build-swss-template.yml
.azure-pipelines/build-template.yml
.azure-pipelines/build_and_install_module.sh
.azure-pipelines/test-docker-sonic-vs-template.yml

Fix pipeline issue.Cherry pick tow commits in master branch:
```
2bbe97f [ci] Continue on error when running test.
749b393 [ci] Fix apt-get install unable locate package issue. (#1212)
```

[ci] Fix apt-get install unable locate package issue. (#1212)

---

.azure-pipelines/test-docker-sonic-vs-template.yml

docker 4.4.1 don't support urllib3 v2.
Update it to latest.

Fix pipeline issue caused by urllib3 v2

---

syncd/VendorSai.cpp

Reverts sonic-net/sonic-sairedis#1248

Revert "Remove return failure when SAI version mismatch"

---

.github/workflows/codeql-analysis.yml

This PR contains a fix of CodeQL bug introduced by: https://github.com/sonic-net/sonic-sairedis/pull/1194

[CodeQL]: Fix syncd compilation in azp template

---

.azure-pipelines/test-docker-sonic-vs-template.yml

**Cherry-Pick:** https://github.com/sonic-net/sonic-swss-common/pull/799

[CI]: Fix collect log error in azp template

---

.azure-pipelines/test-docker-sonic-vs-template.yml

Signed-off-by: Nazarii Hnydyn [nazariig@nvidia.com](mailto:nazariig@nvidia.com)
**Cherry-Pick:** https://github.com/sonic-net/sonic-sairedis/pull/1238

[202211][CI]: Fix pipeline issue caused by urllib3 v2

---

vslib/SwitchConfig.cpp

[vs] Use boost join to concatenate switch types in config

---

syncd/VendorSai.cpp

Build was failing because of this if some features were available

[syncd] Fix missing comma

---

.azure-pipelines/test-docker-sonic-vs-template.yml

**What I did**
Change the sonic_buildimage_ubuntu20_04 from master to $(BUILD_BRANCH)
Azp maybe apply to other branch
Check Azp

[Azp]: Change default branch to build_branch

---

.azure-pipelines/test-docker-sonic-vs-template.yml

[202211][CI]: Fix collect log error in azp template

---

.azure-pipelines/build-swss-template.yml
.azure-pipelines/build-template.yml
azure-pipelines.yml

For better debugging if anything will fail

[azp] Update az pipeline for swss docker to add syslog

---

.github/workflows/codeql-analysis.yml

Install nlohmann-json3-dev package for codeql

---

configure.ac
lib/RedisRemoteSaiInterface.cpp
syncd/Syncd.cpp

Will help debugging and identification of specific version

Add log for git revision

---

vslib/SwitchStateBase.cpp

Add fabric ports related calls for vs tests.
This is the preparation for adding vs test for fabric daemon ( https://github.com/sonic-net/sonic-swss/pull/2920 )

Add fabric ports related calls for vs tests.

---

vslib/SwitchMLNX2700.cpp
vslib/SwitchStateBase.cpp

Fix methods signature definitions for VSLIB implementation

[vslib]: Fix method signatures

---

syncd/NotificationProcessor.cpp
unittest/syncd/TestNotificationProcessor.cpp

Fixes https://github.com/sonic-net/sonic-buildimage/issues/16992

[syncd] Translate removed RID on bfd session state change (#1320)

---

vslib/SwitchStateBase.cpp
vslib/SwitchStateBase.h

Add vslib support for the following attributes:
* SAI_ACL_TABLE_ATTR_AVAILABLE_ACL_ENTRY
* SAI_ACL_TABLE_ATTR_AVAILABLE_ACL_COUNTER

[vslib] add support for ACL table available entry/counter attributes

---

lib/Makefile.am
lib/sai_redis.h
lib/sai_redis_interfacequery.cpp
lib/sai_redis_poe.cpp
meta/SaiSerialize.cpp
meta/sai_serialize.h
unittest/lib/Makefile.am
unittest/lib/test_sai_redis_poe.cpp
unittest/vslib/Makefile.am
unittest/vslib/test_sai_vs_poe.cpp
vslib/Makefile.am
vslib/sai_vs.h
vslib/sai_vs_interfacequery.cpp
vslib/sai_vs_poe.cpp

Will include adding new POE api

[submodule] Update SAI submodule to v1.14

---

meta/DummySaiInterface.cpp
proxylib/Makefile.am
proxylib/Proxy.cpp
proxylib/Proxy.h
proxylib/Sai.cpp
proxylib/Sai.h
unittest/meta/TestDummySaiInterface.cpp
unittest/proxylib/Makefile.am
unittest/proxylib/TestSai.cpp

Initial implementaion of all APIs except bulk and notifications required for sai proxy feature

[saiproxy] Implement all APIs except bulk

---

.github/workflows/codeql-analysis.yml

[codeql] Show gcc version before compile

---

.github/workflows/codeql-analysis.yml

To check if PR is actually taken into account

[codeql] Show git ancestry graph

---

.github/workflows/codeql-analysis.yml
configure.ac

To pick up PR changes to workflow
Also switch to swig4 in sairedis and codeql

[codeql] Change pull_request_target to pull_request

---

syncd/VendorSai.cpp
tests/TestDash.cpp
unittest/syncd/TestVendorSai.cpp

Add VendorSai bulk quad oid api support for DASH SAI meter rule object.

[DASH] Add meter rule bulk support in syncd

---

meta/Meta.cpp
meta/Meta.h
meta/SaiSerialize.cpp
meta/sai_serialize.h
syncd/VendorSai.cpp
unittest/meta/TestMeta.cpp
unittest/meta/TestSaiSerialize.cpp
unittest/syncd/TestVendorSai.cpp

Will include updates on other components to accomodate for changes

[submodule] Update SAI to latest origin master

---

syncd/Syncd.cpp
syncd/tests/TestSyncdBrcm.cpp

Support bulk set in INIT_VIEW mode.

[syncd] Support bulk set in INIT_VIEW mode

---

meta/Meta.cpp
meta/Meta.h
meta/SaiInterface.cpp
meta/SaiInterface.h
meta/SaiOptions.h
meta/SaiSerialize.cpp
meta/sai_serialize.h
syncd/AttrVersionChecker.cpp
syncd/AttrVersionChecker.h
syncd/CommandLineOptions.cpp
syncd/CommandLineOptions.h
syncd/CommandLineOptionsParser.cpp
syncd/Makefile.am
syncd/SaiDiscovery.cpp
syncd/SaiDiscovery.h
syncd/SaiSwitch.h
syncd/SingleReiniter.cpp
syncd/Syncd.cpp
syncd/VendorSai.cpp
syncd/VendorSaiOptions.h
tests/aspell.en.pws
tests/utils.pm
unittest/meta/TestMeta.cpp
unittest/meta/TestSaiInterface.cpp
unittest/meta/TestSaiSerialize.cpp
unittest/syncd/Makefile.am
unittest/syncd/TestAttrVersionChecker.cpp
unittest/syncd/TestCommandLineOptions.cpp
unittest/syncd/TestVendorSai.cpp

This reverts commit 4f7eed0aac95288077fa9959dc61eacd2f3938d6.

Revert "Revert back to SAI version 1 15 (#1481)"

---

.azure-pipelines/build-template.yml

Download and install vpp deb packages so sairedis could be build with VPP enabled

[azp] Download and install sonic-platform-vpp artifacts

---

lib/RedisRemoteSaiInterface.cpp
syncd/FlexCounter.cpp
syncd/FlexCounter.h
tests/aspell.en.pws
unittest/syncd/TestFlexCounter.cpp

Reverts sonic-net/sonic-sairedis#1534
This change caused test_virtualdb_table_streaming to fail, so reverting in 202411.
Work item tracking
Microsoft ADO (number only): 31968783

Revert "[202411] Optimize counter polling interval by making it more accurate (Backport PR #1457)"

---

syncd/FlexCounter.cpp
unittest/syncd/TestFlexCounter.cpp

* Add support for a new SRv6 MySID counter
* Extended flex counter test

[FlexCounter] add support for SRv6 MySID counters

---

unittest/vslib/TestSwitchStateBase.cpp
vslib/SwitchStateBase.cpp
vslib/SwitchStateBase.h

**HLD:** https://github.com/sonic-net/SONiC/pull/1898
Requires SAI API v1.15.7
```
.---.        .-----------
/     \  __  /    ------
/ /     \(  )/    -----
//////   ' \/ `   ---
//// / // :    : ---
// /   /  /`    '--
//          //..\\
====UU====UU====
'//||\\`
''``
```

[trim]: Add Packet Trimming to VS lib

---

meta/Makefile.am
meta/Meta.cpp
meta/Meta.h
meta/NotificationFactory.cpp
meta/NotificationHaScopeEvent.cpp
meta/NotificationHaScopeEvent.h
meta/NotificationHaSetEvent.cpp
meta/NotificationHaSetEvent.h
meta/SaiSerialize.cpp
meta/sai_serialize.h
proxylib/Proxy.cpp
proxylib/Proxy.h
pyext/pysairedis.cpp
pyext/pysairedis.i
saiplayer/SaiPlayer.cpp
saiplayer/SaiPlayer.h
syncd/NotificationHandler.cpp
syncd/NotificationHandler.h
syncd/NotificationProcessor.cpp
syncd/NotificationProcessor.h
syncd/SwitchNotifications.cpp
syncd/SwitchNotifications.h
unittest/meta/Makefile.am
unittest/meta/TestDummySaiInterface.cpp
unittest/meta/TestNotificationHaScopeEvent.cpp
unittest/meta/TestNotificationHaSetEvent.cpp
unittest/proxylib/TestProxy.cpp
unittest/proxylib/TestSai.cpp
vslib/SwitchStateBase.cpp

Adding sairedis and syncd support to process and send back ha set and ha scope events.
Sign-off: Jing Zhang zhangjing@microsoft.com

Add support for ha event notifications

---

vslib/vpp/SwitchVppBfd.cpp

Fix the failures in BFD test caused by not passing the port id

fix the BFD tests for VPP

---

.gitmodules

This PR updates the SAI version to 1.16.3, which adds support for trim counters.

Updating SAI version to 1.16.3

---

syncd/scripts/syncd_init_common.sh

Modified Xsight platform init sequence to support the new X2 systems

[Xsight] update config_syncd_xsight()

---

vslib/vpp/vppxlate/SaiVppXlate.c

Update deprecated SR_BEHAVIOR_API_END_UN_PERF to SR_BEHAVIOR_API_END_UN for correct SRH behavior.

Update UN_PERF to UN.

---

.azure-pipelines/test-docker-sonic-vs-template.yml

Reverts sonic-net/sonic-sairedis#1639

Revert "[sai] Install yang related debto align with latest libswsscommon requirement"

---

lib/RedisRemoteSaiInterface.cpp
syncd/NotificationProcessor.cpp
syncd/Syncd.cpp
unittest/syncd/TestNotificationProcessor.cpp

HA notifications were not reaching orchagent, added binding to Syncd.cpp. Also fixed check in RedisRemoteSaiInterface.cpp to account for attr extensions range and added RidToVid translation for ha_scope and ha_set ids.

Fix ha notifications.

---

syncd/FlexCounter.cpp

After the cold reboot, due to the field/value sequence, the flex counter first does status configuration and starts counter polling with the default interval of 60 sec used during switch group initialization. The subsequent polling interval configuration doesn't have any effect, since the polling has been already started with the default interval.
Current `sonic-sairedis` implementation doesn't support immediate status/polling update - only after the previous polling is done. This change allows having a configuration update immediately if a long polling interval was set.
**sonic-swss/orchagent/switchorch.cpp**
```
// defines ------------------------------------------------------------------------------------------------------------ …
```

[flexcounter]: Apply configuration immediately on state change
