sonic-net/sonic-sairedis

syncd/syncd.cpp
Adding MLNX SAI support in syncd.cpp
=> syncd: adding MLNX SAI support

syncd/syncd.cpp, syncd/syncd.h, syncd/syncd_hard_reinit.cpp, syncd/syncd_reinit.cpp
When syncd will exit unexpectedly because of db failure or any SAI api failure it will send notification to OA so it can know and respond and take action. This notification is not guaranteed to be send on unexpected exit or crash.
=> Add OA switch_shutdown_request notification on syncd exit

debian/syncd.init, etc/syncd.d/dell_s6000.profile
The profile supposed to be in /etc/bcm/td-s6000-32x40G.config.bcm file
=> Use a custom profile for dell s6000

lib/src/sai_redis_record.cpp
Because race condition of main thread and notifications thread it could happen that some lines in recording log were duplicated, using mutex will fix that problem
=> Fix record line for notifications

README.md, configure.ac, debian/rules, syncd/Makefile.am, syncd/syncd.cpp
To address https://github.com/Azure/sonic-sairedis/issues/137
=> syncd: Remove platform dependency code

meta/sai_meta.cpp
the log level should match the return value, since the return value is error,
the log level should be error too.
=> change the log level to error for conditional attribute check

meta/sai_meta.h
0 is valid value for SAI_MIRROR_SESSION_ATTR_VLAN_ID attribute. Means that
outer packet should be untagged. On attempt to create session with VLAN 0
error was returned.
=> [everflow]: Remove SAI_MIRROR_SESSION_ATTR_VLAN_ID from VLAN validation.

debian/syncd.init
Add support of fast-reboot option for Broadcom.
As soon as kernel command line contains fast-reboot option, we can add -t fast parameter for syncd.
=> Add support of fast-reboot option

syncd/scripts/syncd_init_common.sh
This reverts commit 2e2ddaf600bc0d205b00001a4e315ab1531fd63f.
Issue with bash MAC address is fixed.
=> Revert "*** Temp workaround for MLNX mac truncating bug"

lib/src/sai_redis_queue.cpp, meta/saiserialize.cpp, meta/saiserialize.h, syncd/Makefile.am, syncd/syncd.cpp, syncd/syncd.h, syncd/syncd_pfc_watchdog.cpp, syncd/syncd_pfc_watchdog.h, tests/Makefile.am
Changes include support fur dynamic subscription to syncd counters, needed for PFC WD.
libsairedis was extended to support queue counters serialization.
=> [PFC WD]: Initial support

syncd/syncd_saiswitch.cpp
Keep port oids in COUNTERS_DB in serializable format
This way client code can reuse sai_deserialize... api
=> [syncd_saiswitch]: Keep full port oids

lib/src/sai_redis_notifications.cpp, meta/saiserialize.cpp, meta/saiserialize.h, syncd/syncd_notifications.cpp
Implement notification path and serializattion/deserialization
for event SAI_SWITCH_ATTRIBUTE_QUEUE_PFC_DEADLOCK_NOTIFY
=> [notifications]: Add support for native PFC storm notify

syncd/scripts/syncd_init_common.sh
This line causes to deletion of the database content AFTER configuration set.
Signed-off-by: Denis Maslov denis.maslov@cavium.com
=> [syncd]: The cause of 10 minutes long reboot for SONiC project removed.

syncd/scripts/syncd_init_common.sh
**-What I did**
Add switch ASIC vendor: Nephos
Add switch configuration file for Nephos
Check switch ports has been created and worked as well
**- Description for the changelog**
Add switch ASIC vendor for Nephos
Signed-off-by: Sam Yang <yang.kaiyu@gmail.com>
=> Add switch ASIC vendor for Nephos

syncd/syncd_flex_counter.cpp
lock_guard holds mutex during sleep, which does not allow other threads
to acquire it for most of time. It is moved to a scope that actually
needs this mutex.
=> [syncd_flex_counter.cpp]: Move lock_guard to narrow scope

syncd/syncd_flex_counter.cpp, syncd/syncd_flex_counter.h
The previous hardcoded for loop to iterate items defined in the SAI
header file was not ideal. Update the logic here so that only needed
attributes are checked for the support.
Signed-off-by: Shu0T1an ChenG <shuche@microsoft.com>
=> [syncd]: Only query queue counters that are needed by the application

syncd/scripts/syncd_init_common.sh
**-What I did**
Add switch ASIC vendor: Nephos
Add switch configuration file for Nephos
Check switch ports has been created and worked as well
**- Description for the changelog**
Add switch ASIC vendor for Nephos
Signed-off-by: Sam Yang <yang.kaiyu@gmail.com>
=> Add Nephos ASIC

vslib/src/sai_vs_hostintf.cpp
This is when one of the virtual ethernet interface
is down, then EIO is returned.
=> Do not log error when write fails to tap device

debian/rules, syncd/syncd.cpp
The rebased copy of #260
Export switch ID variable required by SAI thrift.
=> Enable syncd-rpc target compilation.

syncd/syncd.cpp, syncd/syncd_flex_counter.cpp
Remove objects from flex counter bu key, not when iterating over values
because on DEL op there are no values, only key.
Fix logic in removeQueue.
=> [flex_counter]: Fix cleanup flow

syncd/syncd_flex_counter.cpp, syncd/syncd_flex_counter.h
Measure the delay that it takes to read counters from hardware and
adjust sleep time by it.
=> [flex_counter]: Add delay correction to poll

syncd/syncd.cpp, syncd/syncd_flex_counter.cpp, syncd/syncd_flex_counter.h
=> [Flex_counter]: Remove poll interval from db key

syncd/syncd_flex_counter.cpp
Remove non-existing queue/port id doesn't mean to be error. Reduce severity to notice.
=> [flex_counter]:change log level from error to notice

saiplayer/saiplayer.cpp, syncd/syncd.cpp
Log warn and error messages on stderr for sai metadata checks.
=> Add stderr logging for sai metadata

lib/src/sai_redis_interfacequery.cpp, syncd/syncd.cpp
Not an actionable syslog and sai_api_queries failures have been changed to NOTICE.
Also changing to NOTICE the error in sai_log_set which generates multiple ERR syslogs:
syslog:Feb 12 17:44:11.277382 sonic ERR orchagent: :- sai_log_set: not implemented
syslog:Feb 12 17:44:11.277382 sonic ERR orchagent: :- sai_log_set: not implemented
syslog:Feb 12 17:44:11.277382 sonic ERR orchagent: :- sai_log_set: not implemented
syslog:Feb 12 17:44:11.277382 sonic ERR orchagent: :- sai_log_set: not implemented
syslog:Feb 12 17:44:11.277431 sonic ERR orchagent: :- sai_log_set: not implemented
syslog:Feb 12 17:44:11.277431 sonic ERR orchagent: :- sai_log_set: not implemented
syslog:Feb 12 17:44:11.277431 sonic ERR orchagent: :- sai_log_set: not implemented
syslog:Feb 12 17:44:11.277541 sonic ERR …
=> Change WARNING in sai_api_query to NOTICE and ERROR in sai_log_set to NOTICE

syncd/syncd.cpp, syncd/syncd_hard_reinit.cpp
The fix for below issue with incorrect global "gSwitchId" variable which is used by SAI thrift
Azure/sonic-buildimage#1405
=> Fix for the correct export gSwitchId for SAI thrift

syncd/syncd_notifications.cpp
consolidated fdb flush event will carry a fdb_entry which include a bvid equal to SAI_NULL_OBJECT_ID, in fdb flush case it shall not be considered as an invalid fdb_entry.
This fix has been verified on MLNX platform.
=> [syncd] fix a fdb-clear bug that introduced by SAI 1.2 modification

syncd/scripts/syncd_init_common.sh
This commit changes the directory of sai.profile to point to the new
directory location for sai.profile /etc/sai.d/sai.profile file.
This is the location of sai.profile dynamic generation or for
copying the file from the hwsku directory.
Unit tested the code on S6100 for dynamic generation of sai.profile file for
both T0 and T1 and the file was created in /etc/sai.d/sai.profile
Similarly tested the sonic binary on S6000 to make sure that the sai.profile is
copied from the /usr/share/sonic/hwsku/sai.profile to /etc/sai.d/sai.profile.
Signed-off-by: Harish Venkatraman <Harish_Venkatraman@dell.com>
=> [src/sonic-sairedis] Change sai.profile directory

syncd/scripts/syncd_init_common.sh
Change centec way of passing mac-address arg from sai.profile to -m param with orchagent
=> Change centec way of passing mac-address arg from sai.profile to -m param with orchagent

syncd/syncd.cpp, syncd/syncd_flex_counter.cpp, syncd/syncd_flex_counter.h, syncd/syncd_notifications.cpp
- Stop notification thread before removing switch
- Stop flex counter queries before removing switch
=> [Syncd] make sure syncd can exit gracefully

syncd/syncd.cpp, syncd/syncd_flex_counter.cpp, syncd/syncd_flex_counter.h
=> [counter]: support enable/disable counter query

syncd/scripts/syncd_init_common.sh
Signed-off-by: Andriy Moroz <c_andriym@mellanox.com>
**- What I did**
Updated syncd init script to pass MAC from EEPROM to SAI for Mellanox platforms. Interfaces will be created with this MAC
updated syncd init script (syncd_init_common.sh) 
Start SONiC and make sure MACs on Interfaces are similar to one returned by command
od -vt x1 -An /sys/bus/i2c/devices/8-0051/eeprom | xargs printf "0x%s " | xargs printf "%02x:" | awk 'BEGIN { FS=":"; i=8+1+2+1} {while(i<NF) {type=$i; len=("0x"$(i+1));if(type!="24") {i=i+2+len} else {print substr($0, (i+1)*3+1, len*3-1); break}}}'
some bits in last byte may differ
=> Use MAC from EEPROM for Interfaces

.gitmodules, lib/src/sai_redis_bridge.cpp, lib/src/sai_redis_buffer.cpp, lib/src/sai_redis_hostintf.cpp, lib/src/sai_redis_policer.cpp, lib/src/sai_redis_port.cpp, lib/src/sai_redis_queue.cpp, lib/src/sai_redis_tunnel.cpp, lib/src/sai_redis_vlan.cpp, syncd/syncd_notifications.cpp, vslib/src/sai_vs_bridge.cpp, vslib/src/sai_vs_buffer.cpp, vslib/src/sai_vs_hostintf.cpp, vslib/src/sai_vs_policer.cpp, vslib/src/sai_vs_port.cpp, vslib/src/sai_vs_queue.cpp, vslib/src/sai_vs_tunnel.cpp, vslib/src/sai_vs_vlan.cpp
Placeholder PR to migrate to SAI 1.3 headers
=> SAI 1.3 changes

syncd/syncd.h, syncd/syncd_notifications.cpp
In the event of continuous mac-move, it is observed that the notifier-queue keeps growing consuming high memory. 
Current solution is to drop FDB events beyond a limit (set to `300k`, considering 256k MAC entries in a typical L2 deployment + some extra buffer for other events). A permanent approach would be to have the event stateful and notify only the latest event. 
Tested and observed that with this cap, the syncd memory usage is `~3.8%` and does not exceed beyond this.
=> Suppress FDB events if notifier queue exceeds limit 

lib/src/sai_redis_interfacequery.cpp
* create RedisPipeline obj by default constructor , which enabled redispipeline with parameter 128
* create producer g_asicState using redisPipeline instance with redispipeline enabled
* with the changes in swss and swss-common, route performance improved by 200~300 routes/sec
* this changes depends on swss-common#219
=> sairedis: add RedisPipeline instance to construct producer g_asicState

syncd/syncd.cpp
When shutdown is requested, notify SAI when removing switch so that SAI would save states.
=> [syncd] initiate warm shutdown when requested

syncd/scripts/syncd_init_common.sh, syncd/syncd.cpp, syncd/syncd.h, syncd/syncd_hard_reinit.cpp
This set of commits partially enables warm recovery when syncd is restarted without full system warm reboot.
The missing parts are:
- After syncd warm restarted, it need to re-register all notifications with SAI again.
- After syncd warm recovery (succeeded or not), it should remove the SAI saved file.
=> [syncd] partial warm recovery support

syncd/scripts/syncd_init_common.sh, vslib/src/sai_vs_hostintf.cpp
Signed-off-by: Guohan Lu <gulv@microsoft.com>
=> support virtual switch

syncd/syncd.cpp, syncd/syncd_hard_reinit.cpp, syncd/syncd_request_shutdown.cpp, tests/aspell.en.pws
Adding 2 stage shutdown support for warm reboot.
Stage-1: pre-shutdown, back up SAI/SDK data, detach almost all data plane, but leave CPU port active.
Stage-2: warm shutdown, fully shutdown SAI.
=> [sycnd] add 2 stage shutdown support for warm reboot

syncd/scripts/syncd_init_common.sh, syncd/syncd.cpp, syncd/syncd.h, tests/aspell.en.pws
Signed-off-by: Volodymyr Samotiy <volodymyrs@mellanox.com>
=> [Mellanox|FFB]: Add support for Mellanox fast-fast boot  in syncd

configure.ac, syncd/Makefile.am, syncd/scripts/syncd_init_common.sh, syncd/scripts/syncd_start.sh, syncd/syncd.cpp
use common warm boot flow for mellanox fastfast boot.
=> [mellanox|ffb] use system level warm reboot for Mellanox fastfast boot

lib/inc/sai_redis_internal.h, lib/src/Makefile.am, lib/src/sai_redis_generic_create.cpp, lib/src/sai_redis_uburst.cpp, meta/Makefile.am, meta/sai_meta.cpp, meta/sai_serialize.h, meta/saiserialize.cpp, meta/tests.cpp, saidiscovery/Makefile.am, saidump/Makefile.am, saiplayer/Makefile.am, saisdkdump/Makefile.am, syncd/Makefile.am, syncd/syncd.cpp, syncd/syncd_applyview.cpp, syncd/syncd_flex_counter.cpp, syncd/syncd_hard_reinit.cpp, tests/Makefile.am, vslib/inc/sai_vs_internal.h, vslib/src/Makefile.am, vslib/src/sai_vs_uburst.cpp, vslib/src/tests.cpp
Signed-off-by: Marian Pritsak <marianp@mellanox.com>
=> Update SAI pointer to latest master

debian/libsaivs-dev.install
fix swss build issue
https://sonic-jenkins.westus2.cloudapp.azure.com/job/vs/job/sonic-swss-build/54/console
=> install SAI extension header files into /usr/include/sai

tests/aspell.en.pws, vslib/src/sai_vs_switch_BCM56850.cpp, vslib/src/sai_vs_switch_MLNX2700.cpp
- add default port attributes - admin state and mtu
Get SAI_PORT_ATTR_ADMIN_STATUS before it was set returned not implemented:
```
Feb 10 00:57:46.380006 adcde36a1608 ERR #orchagent: :- meta_sai_get_oid: get status: SAI_STATUS_NOT_IMPLEMENTED
Feb 10 00:57:46.380018 adcde36a1608 ERR #orchagent: :- getPortAdminStatus: Failed to get admin status for port pid:1000000000008
```
Also, added MTU set as default (1514 as defined by SAI)
<b>NOTE:</b> To 201811 as well
=> [vslib] add missing port attributes for virtual switch

syncd/scripts/syncd_init_common.sh
Signed-off-by: Nazarii Hnydyn <nazariig@mellanox.com>
These changes are made in terms of propagating new Mellanox platforms: SN3700/SN3700C:
Spectrum-1/Spectrum-2 based devices requires a different MAC alignment and the correct values should be taken directly from system EEPROM.
**- What I did**
* Removed MAC alignment WA for Mellanox platforms
* Updated syncd init script
1. make configure PLATFORM=mellanox
2. make target/sonic-mellanox.bin
**- Description for the changelog**
* N/A
=> Remove MAC alignment WA for Mellanox platforms.

saidiscovery/Makefile.am, saisdkdump/Makefile.am, syncd/Makefile.am, syncd/scripts/syncd_init_common.sh
- Remove hard coded libs in saidiscovery for bfn platform
- Remove ignoring unresolved-symbols
- Get rid of LD_PRELOAD in syncd
Signed-off-by: Nadiya.Stetskovych <nstetskovych@barefootnetworks.com>
=> [bfn|syncd] Ged rid of ld_preload. Link against libsai only

syncd/scripts/syncd_init_common.sh
**- What I did**
added WARM_BOOT options for Barefoot based platforms including
* append sai.profile to the syncd arguments
run sudo warm-reboot on the hardware box
**- Description for the changelog**
Add warm/fast-boot feature processing for wedge100bf_32x/65x platforms
**- Should be merged together with**
https://github.com/Azure/sonic-buildimage/pull/2687
https://github.com/Azure/sonic-utilities/pull/485
@akokhan, @mkbalani FYI
=> Add warm/fast-boot feature processing for wedge100bf_32x/65x platforms

syncd/syncd_flex_counter.cpp
Fix logic to remove the Flex counter instance if it does not have registered Counter Ids or plugins.
Signed-off-by: Mykola Faryma <mykolaf@mellanox.com>
=> [flex couter] add RIF counter check to isEmpty

debian/rules
Make binary-syncd the last target, so the non-rpc requisites will be available after the first build
It will allow doing incremental builds later on for the main binary type
=> [debian/rules] Change build order in target binary

syncd/syncd.cpp, syncd/syncd_flex_counter.cpp, syncd/syncd_flex_counter.h
In the current implementation, when  FLEX_COUNTER_STATUS is set to disable, which can be issued by counterpoll disable cli, a flex counter thread will still wake up every polling interval, though skipping the actual collectCounters() and runPlugins() operations. 
The main drive of the PR is to put the polling thread to a complete sleep in the above situation to save CPU cycles, and hence to improve the scalability of flex counter polling architecture in general.
To that end, the following changes are made to pave the way and for further optimization purpose:
1\) Introduce a per-thread lock, together with a condition variable, to enable the full sleep behavior when FLEX_COUNTER_STATUS is set to disable, the status of which is maintained by data member m_enable per flex counter object. 
2\) …
=> Full sleep wait flex counter polling thread when POLL_COUNTER_STATUS is disable

syncd/syncd_flex_counter.cpp, syncd/syncd_flex_counter.h
When issuing 'pfcwd stop' cli to stop PFC watchdog, it only clears the counter id list for physical ports under the hood, leaving lua script plugins still installed and ieEmpty() returns false.
So even when PFC watchdog is stopped, the flex counter thread would wake up every 200 ms.
Jun  4 17:58:51.273413 str-a7050-acs-1 ERR syncd#syncd: :- flexCounterThread: End of flex counter thread FC PFC_WD, took 33 ms
Jun  4 17:58:51.471288 str-a7050-acs-1 ERR syncd#syncd: :- flexCounterThread: End of flex counter thread FC PFC_WD, took 30 ms
Jun  4 17:58:51.672930 str-a7050-acs-1 ERR syncd#syncd: :- flexCounterThread: End of flex counter thread FC PFC_WD, took 31 ms
Jun  4 17:58:51.882972 str-a7050-acs-1 ERR syncd#syncd: :- flexCounterThread: End of flex counter thread FC PFC_WD, took 40 ms
Jun  4 …
=> Full sleep wait change for PFC watchdog

vslib/inc/sai_vs_switch_BCM56850.h, vslib/inc/sai_vs_switch_MLNX2700.h, vslib/src/sai_vs_port.cpp, vslib/src/sai_vs_switch_BCM56850.cpp, vslib/src/sai_vs_switch_MLNX2700.cpp
For breakout a port, it needs to support create port and remove port.
When create a port, it needs to init some attributes.
Signed-off-by: chiourung_huang <chiourung_huang@edge-core.com>
=> Modify sai_create_port to breakout a port for virtual switch

lib/src/sai_redis_generic_create.cpp, meta/sai_meta.cpp, meta/saiserialize.cpp
Signed-off-by: Antony Rheneus <arheneus@marvell.com>
=> ARM32 bit fixes, for 64bit printf format specifier

syncd/scripts/syncd_init_common.sh
We should handle both cases for backward-compatible with 201803:
- fast-reboot
- SONIC_BOOT_TYPE=fast-reboot
=> [syncd_init_common.sh] fix fast reboot backwards compatibility

syncd/scripts/syncd_init_common.sh
It will handle the kernel argument on 201803 image correctly.
The bug was introduced by https://github.com/Azure/sonic-sairedis/pull/480
=> Fix a bug in parsing kernel argument of fast-reboot

meta/sai_meta.cpp, vslib/src/sai_vs_switch_BCM56850.cpp, vslib/src/sai_vs_switch_MLNX2700.cpp
=> [vslib] add ACL action capabilities support

syncd/syncd.cpp, syncd/syncd_flex_counter.cpp, syncd/syncd_flex_counter.h
Add STATS_MODE field parsing when oid in FLEX_COUTER_TABLE key is SAI_OBJECT_TYPE_BUFFER_POOL.
Use READ_AND_CLEAR mode when either global stats polling mode or the particular buffer pool stats polling mode is READ_AND_CLEAR.
In the opposite, use READ mode (no stats clear) only when both global and per buffer pool stats polling mode are READ.
=> Per buffer pool watermark polling mode

syncd/scripts/syncd_init_common.sh
Signed-off-by: Nazarii Hnydyn <nazariig@mellanox.com>
Fixed:
Jul 17 15:29:42.645392 sonic INFO syncd#supervisord: syncd /usr/bin/syncd_init_common.sh: line 62: [: ==: unary operator expected
=> Fixed conditional operator

syncd/syncd.h, syncd/syncd_saiswitch.cpp
This bug is introduced from https://github.com/Azure/sonic-sairedis/pull/316#issuecomment-512007085
The bug is exposed by below steps. The expected log level for SAI_API_SWITCH is SAI_LOG_LEVEL_DEBUG.
```
admin@sonic:~$ swssloglevel -l SAI_LOG_LEVEL_DEBUG -s -c SWITCH
admin@sonic:~$ redis-cli -n 3 hgetall "SAI_API_SWITCH:SAI_API_SWITCH"
1) "LOGLEVEL"
2) "SAI_LOG_LEVEL_DEBUG"
3) "LOGOUTPUT"
4) "SYSLOG"
admin@sonic:~$ sudo systemctl restart swss
admin@sonic:~$ redis-cli -n 3 hgetall "SAI_API_SWITCH:SAI_API_SWITCH"
1) "LOGLEVEL"
2) "SAI_LOG_LEVEL_DEBUG"
3) "LOGOUTPUT"
4) "SYSLOG"
admin@sonic:~$ sudo grep "loglevel SAI_API_SWITCH" /var/log/syslog
Jul 25 00:00:28.280667 sonic NOTICE syncd#syncd: :- saiLoglevelNotify: Setting SAI loglevel SAI_API_SWITCH to SAI_LOG_LEVEL_DEBUG
Jul 25 …
```
=> Fix bug: Restore sai log levels from LOGLEVEL_DB after saiDiscover

syncd/syncd_flex_counter.cpp, syncd/syncd_flex_counter.h
Each time a new counter/attribute type is added to flex counter infrastructure, collectCounters() is tailed with the logic of collecting the stats for the new type. As more and more possible id lists are being added to the flex counter, the collectCounters() member function is becoming bulky to check against all possible id lists, both existing and newly added ones.
Current list is already significantly long---port counters, queue counters, queue attributes, pg counters, pg attributes, and buffer pool counters. And most of them are irrelevant to a particular flex counter instance thread. E.g., For buffer pool watermark thread, only buffer pool counters matter, not the rest, port counters, queue counters, queue attributes, pg counters, pg attributes.
Improvement:
1. Separate each …
=> Use pointer to member function to reduce the footprint of collectCounters()

lib/src/sai_redis_generic_remove.cpp, lib/src/sai_redis_generic_set.cpp, lib/src/sai_redis_interfacequery.cpp, syncd/syncd.cpp
* fix wrong API type in internal_api_wait_for_response()
* add cmdline parse option "s" , otherwise syncd cannot be executed via -s option, system cannot be up with syncd
* current behavior:
```
root@ASW-7005:/# /usr/bin/syncd --diag -u -p /etc/sai.d/sai.profile -s
/usr/bin/syncd: invalid option -- 's'
Usage: syncd [-N] [-U] [-d] [-p profile] [-i interval] [-t [cold|warm|fast|fastfast]] [-h] [-u] [-S] [-s]
-N --nocounters
Disable counter thread
-d --diag
Enable diagnostic shell
-p --profile profile
Provide profile map file
-i --countersInterval interval
Provide counter thread interval
-t --startType type
Specify cold|warm|fast|fastfast start type
-u --useTempView:
Use temporary view between init and apply
-S --disableExitSleep
Disable sleep when syncd crashes
-U --eableUnittests
Metadata …
```
=> syncd cannot be executed using -s option, remove unuseful buffer

syncd/syncd_notifications.cpp
Invalid OIDs in fdb notifications are considered vendor bug, and are skipped at this point, since storing them will cause later on comparison logic issues
=> Do not store invalid OIDs from FDB notification into ASIC DB

syncd/syncd_flex_counter.cpp
We check to see which counters are supported, if something is not, that is not an error.
It may cause some Ansible tests fail because of the loganalyzer found errors in syslog.
=> [flex counter] Lower the severity of log during rif counter support check

lib/src/sai_redis_route.cpp, syncd/syncd.cpp
* add redis_dummy_remove_route_entry() for meta_sai_remove_route_entry() calls, which is the same logic as create/set
* add NULL pointer check and add meta_sai_remove_route_entry() calls which will remove meta data after remove entries. The logic is the same as create/set
* syncd add bulkremove option for processEvent() to select  processBulkEvent()
* together with this , there should be a consumer_table_pops.lua script changes to handle bulkremove in sonic_swss_common
https://github.com/Azure/sonic-swss-common/pull/306
* after these changes , when we call bulk_create and bulk_remove, the meta data is cleared and we can bulk_create again, otherwise it raise error entry already exists.
=> fully support bulk_remove in sairedis

tests/aspell.en.pws, vslib/src/sai_vs_hostintf.cpp
**What I did**
Added support in swss for SFLOW. It includes sfloworch and sflowmgr changes.
Added support for supporting genetlink attribute in vs
Loaded vs image. Enabled sflow and checked the redis-db
These changes are required for supporting sflow. When sflow is enabled, the genetlink attributes are programmed and vslib shouldn't return any errors which might crash orchagent.
=> Copp changes for supporting genetlink in vs

syncd/scripts/syncd_init_common.sh
Enable fast-reboot only if "FAST_REBOOT|system" key exists in STATE db.
This PR is required to be included into https://github.com/Azure/sonic-buildimage/pull/3741 to fix https://github.com/Azure/sonic-buildimage/issues/3697
=> Enable FastReboot if we have key "FAST_REBOOT|system" in State db

syncd/scripts/syncd_init_common.sh
Add a solution to don't start in fast-reboot mode if uptime greater than 180 seconds.
But it will not prevent a case when someone restarted syncd within 180 seconds. In this case syncd will start in FR mode.
This would be fixed by https://github.com/Azure/sonic-buildimage/pull/3741
=> Disable Fast-Reboot start if uptime is greater than 3 minutes

vslib/src/sai_vs_debug_counter.cpp
Signed-off-by: Danny Allen <daall@microsoft.com>
=> [vs] Implement indices for debug counters in VS

lib/src/sai_redis_interfacequery.cpp, syncd/syncd.cpp, vslib/inc/sai_vs_state.h, vslib/src/sai_vs_hostintf.cpp
When interfaces are already created in the system and when rebooting syncd port status won't change when creating tap device, Linux won't send link message again. Lets explicitly sent notification with port status.
=> [vs] Send port status notification when creating hostif interface

vslib/src/sai_vs_switch_BCM56850.cpp, vslib/src/sai_vs_switch_MLNX2700.cpp
Adding support for below NAT switch attributes in vslib (needed to run vs pytests)
SAI_SWITCH_ATTR_AVAILABLE_SNAT_ENTRY
SAI_SWITCH_ATTR_AVAILABLE_DNAT_ENTRY
SAI_SWITCH_ATTR_AVAILABLE_DOUBLE_NAT_ENTRY
Signed-off-by: Akhilesh Samineni <akhilesh.samineni@broadcom.com>
=> Support for snat available entry switch attribute in vslib (needed to run vs pytests)

lib/src/sai_redis_interfacequery.cpp, saidump/saidump.cpp, syncd/scripts/syncd_init_common.sh, syncd/syncd.cpp, syncd/syncd_applyview.cpp, syncd/syncd_flex_counter.cpp, syncd/syncd_request_shutdown.cpp, syncd/tests.cpp, vslib/src/sai_vs_interfacequery.cpp, vslib/src/tests.cpp
* using new APIs DBConnector("DBNAME", TIMEOUT) and sonic-db-cli wrapper
* add database_config.json to dh_auto_testing cases to pass tests when building deb pkg 
* since using sonic-db-cli, we need to update sonic-py-swsssdk to https://github.com/Azure/sonic-py-swsssdk/pull/54 at least. Otherwise, sonic-db-cli is not there.
=> [MultiDB]: repalce old APIs with New APIs incuding testing

lib/inc/SkipRecordAttrContainer.h, lib/src/Makefile.am, lib/src/SkipRecordAttrContainer.cpp, lib/src/sai_redis_generic_get.cpp
AVAILABLE attributes are constantly queries using SAI GET api to obtain it values, and this produces a lot of noise in sairecord.rec log file, and those logs are not containing any OID values, so they can be skipped while recording, since after replay they will not produce any meaningful outcome.
=> [sairedis] Skip recording GET operations on AVAILABLE attributes

vslib/src/sai_vs_hostintf.cpp
gcc-8 generates the following error
sai_vs_hostintf.cpp:822:12: error: 'char* strncpy(char*, const char*, size_t)' specified bound 16 equals destination size [-Werror=stringop-truncation]
Signed-off-by: Wataru Ishida <ishida@nel-america.com>
=> [vs] avoid non null terminated string stored in ifr_name

meta/sai_meta.cpp
* [meta] Flush fdb entries after flush api success
* [meta] Use correct fdb entry type
* [meta] Use correct enum values for fdb entry
Back porting https://github.com/Azure/sonic-sairedis/pull/581
=> [meta] Flush fdb entries after flush api success (#581)

syncd/Syncd.cpp, syncd/VendorSai.cpp
The crash is observed during pfc_wd CT execution on BFN platform.
Null pointer is passed to VendorSai::getStats() function due to data() method call for empty "result"  vector. Then NULL pointer is passed to SAI handler where it causes crash.
In order to fix this "result" vector size is set to the size of counter_ids vector. In addition to this checks for NULL pointers are added to VendorSai::getStats().
=> [syncd] Fix crash during stats polling

meta/Meta.cpp
What I did:
Changed the error code from SAI_STATUS_INVALID_PARAMETER to SAI_STATUS_OBJECT_IN_USE in meta_generic_validation_remove(). Also, deleted the similar check in port object validation as that is NOT required.
Why I did:
When an object has 1 or more references, and it's been requested to delete the object, orchagent expects SAI_STATUS_OBJECT_IN_USE error code. For now, this is true for port object. I believe this should be the case for all objects as well. 
How I tested it:
While testing dynamic port breakout, port object was being deleted and it was being referenced by router interface object. Orchagent was expecting SAI_STATUS_OBJECT_IN_USE but receiving SAI_STATUS_INVALID_PARAMETER, hence it was throwing an exception.. After the fix, correct error code is being returned and …
=> Return correct error code

debian/rules
=> allow to use extra inc/lib location to build the package

syncd/Syncd.cpp
I met below error message in syslog when running test `test_FdbWarmRestartNotifications`.
```
Apr  9 00:32:53.543918 84bbea71037f NOTICE #syncd: :- processBulkQuadEvent: bulk SAI_OBJECT_TYPE_ROUTE_ENTRY execute with 3 items
Apr  9 00:32:53.543994 84bbea71037f ERR #syncd: :- translateVidToRid: unable to get RID for VID oid:0x6000000000607
Apr  9 00:32:53.544118 84bbea71037f ERR #syncd: :- run: Runtime error: :- translateVidToRid: unable to get RID for VID oid:0x6000000000607
Apr  9 00:32:53.544129 84bbea71037f NOTICE #syncd: :- sendShutdownRequest: sending switch_shutdown_request notification to OA for switch: oid:0x21000000000000
Apr  9 00:32:53.544197 84bbea71037f NOTICE #syncd: :- sendShutdownRequestAfterException: notification send successfull
```
=> Do not translateVidToRid for processBulkQuadEvent in InitViewMode

syncd/TimerWatchdog.cpp, syncd/tests.cpp
Clock can rollback in big jumps and this causes TimerWatchdog to through
and crashes syncd. This code uses steady clock instead. Steady clock is
guaranteed to be monotonically increasing clock.
signed-of-by: Tamer Ahmed <tamer.ahmed@microsoft.com>
=> [syncd] Use steady clock for TimerWatchdog

vslib/src/SwitchStateBase.cpp
Change log level for not implemented port attributes and skipped mac learning
What I did:
Change log level from warning/error to debug.
Why I did:
Due to execessive logging we were observing that, orchagent or syncd or bot get stuck in send() system call of logging. This was happening because rsyslog was NOT reading from socket buffer. Verified this by sending SIGSTOP and SIGCONT to rsyslogd. This problem happened everytime we ran Dynamic Port Brteakout scale test case. (test_port_dpb.py)
How I verified:
Ran DPB test case again in Jenkins, the problem did NOT occur
=> Change log level 

debian/rules
because:
1. `make` evaluates conditionals (e.g., `ifeq`) at the time it reads a Makefile.
2. no need to replace with shell command outputs
ref: https://stackoverflow.com/a/11994561/2514803
=> Fix debian/rules makefile: use shell commands instead of dollar replacements

syncd/TimerWatchdog.cpp, syncd/tests.cpp
Clock can rollback in big jumps and this causes TimerWatchdog to through
and crashes syncd. This code uses steady clock instead. Steady clock is
guaranteed to be monotonically increasing clock.
signed-of-by: Tamer Ahmed <tamer.ahmed@microsoft.com>
=> [syncd] Use steady clock for TimerWatchdog (#613)

meta/sai_serialize.h, meta/saiserialize.cpp, syncd/syncd_applyview.cpp
Added nat_type attribute in serialize and deserialize meta code to support DNAT Pool.
Addressing the issue - https://github.com/Azure/sonic-swss/issues/1234 
Depends on :
https://github.com/Azure/sonic-swss/pull/1297
https://github.com/Azure/sonic-utilities/pull/921
Signed-off-by: Akhilesh Samineni <akhilesh.samineni@broadcom.com>
=> Update the meta code to support DNAT Pool changes

Makefile.am, configure.ac, debian/rules, debian/syncd.install
this allows to build swss docker without building syncd with requires vendor SAI library.
=> add option to build without syncd

vslib/src/SwitchStateBaseHostif.cpp
**What I did**
Fixed the delete API for Hostif type genetlink in vs
The hostif type genetlink does not create any tap interfaces. Hence during remove there is no tap interfaces to be removed. Without the check to skip removing tap interfaces the remove hostif API would fail
The verification is done using manual testing and by pytests simluating create and remove genetlink hostif scenarios.
=> Fixing hostif For Genetlink host interfaces

meta/Meta.cpp, syncd/SingleReiniter.cpp, syncd/Syncd.cpp
Signed-off-by: Rajkumar Pennadam Ramamoorthy <rpennadamram@marvell.com>
=> [syncd] ARM32 bit fixes, for 64bit printf format specifier.

lib/inc/Recorder.h, lib/inc/RedisRemoteSaiInterface.h, lib/inc/Sai.h, lib/inc/SaiInterface.h, lib/inc/sairediscommon.h, lib/src/Recorder.cpp, lib/src/RedisRemoteSaiInterface.cpp, lib/src/Sai.cpp, lib/src/sai_redis_interfacequery.cpp, meta/DummySaiInterface.cpp, meta/DummySaiInterface.h, meta/Meta.cpp, meta/Meta.h, syncd/Syncd.cpp, syncd/Syncd.h, syncd/VendorSai.cpp, syncd/VendorSai.h, vslib/inc/Sai.h, vslib/inc/VirtualSwitchSaiInterface.h, vslib/src/Sai.cpp, vslib/src/VirtualSwitchSaiInterface.cpp, vslib/src/sai_vs_interfacequery.cpp
This change adds the support of allowing application to invoking SAI API "sai_query_attribute_capability()" from the sonic application side. 
This change has been tested using the Mellanox platform by exercising this new change to query the port object attribute SAI_PORT_ATTR_TPID
status = sai_query_attribute_capability(gSwitchId, SAI_OBJECT_TYPE_PORT, SAI_PORT_ATTR_TPID, &capability);
as well as LAG object attribute SAI_LAG_ATTR_TPID.
status = sai_query_attribute_capability(gSwitchId, SAI_OBJECT_TYPE_LAG, SAI_LAG_ATTR_TPID, &capability);
These two calls were exercised at orchagent init time in order to test out the changes are working.
I could not test this with BRCM platform due to the required SAI API "sai_query_attribute_capability()" although is defined in the SAI header file but was …
=> Adding support for new SAI API sai_query_attribute_capability()

syncd/SaiSwitch.cpp
Changes from https://github.com/Azure/sonic-sairedis/pull/632 is causing BRCM DUT not able to bootup.
The newly introduced getSwithType at SONiC boot time to support BRCM GearBox SAI is not yet supported by ASIC SAI result to error that causes Orchagent termination at boot up.
This workaround is added to default the switch type to NPU in case receiving a failure from the SAI call so that BRCM DUT can boot up successfully.
I have validated this change using the Force10-S6000 (BRCM ASIC).
Kamil has also reviewed and OKed this change.
=> Workaround getSwitchType failure due to NPU SAI not yet supporting it

syncd/Syncd.cpp
- Why I did it
This PR contains the code changes so that the synchronous bulk API processes all events.
- How I did it
Let the syncUpdateRedisBulkQuadEvent function loop across all events in a bulk rather than returning after processing the first one.
- How to verify it
Verify route entries in ASIC_DB after loading multiple routes using swssconfig in vs tests with synchronous mode enabled.
=> Fix synchronous with bulk API

syncd/VendorSai.cpp
Previously the code to support query SAI attribute capabilities were commented out due to discovered missing BRCM Vendor SAI API missing in their 3.7.5.1 debian package that caused linking error during image build.  
See https://github.com/Azure/sonic-sairedis/pull/645 for details on the SAI attribute capability query support.
Since BRCM has provided the patch for the missing API stub code and included them in BRCM SAI 3.7.5.1-2 (see https://github.com/Azure/sonic-buildimage/pull/5101), I am raising this PR to re-enable the calling to Vendor SAI API sai_query_attribute_capability().
I have tested this with the new BRCM SAI 3.7.5.1-2 debians and ensured that the linking issue was fixed by that patch.
=> Re-enable support for new SAI API sai_query_attribute_capability()

syncd/scripts/syncd_init_common.sh
**-What I did**
Let syncd check CONFIG_DB for whether to enable synchronous mode and initialize with the mode selected.
**-Why I did it**
To allow master control of synchronous mode and allow configuring the mode for orchagent and syncd.
**-How I did it**
Let syncd check the mode in CONFIG_DB in `syncd_init_common.sh`
**-How I verified it**
Test locally with a virtual switch.
**-Details if related**
Related to #Azure/sonic-buildimage/pull/5237
=> Add synchronous switch controlled by CONFIG_DB

syncd/Syncd.cpp
**What I did**
Let syncd send statuses to orchagent rather than stopping swss in the presence of SAI failures in synchronous mode.
I expect syncd to send the failure status to orchagent and let orchagent process the failure in synchronous mode when SAI failures happen. Currently, syncd would throw an exception and stop swss before the failure information is sent to orchagent. 
**How I did it**
Let syncd log the error message rather than throw the exception. As such, the syncd would not trigger swss shutdown in the presence of SAI failures.
Test locally with a virtual switch.
=> Prevent syncd from stopping swss in the presence of SAI failures in synchronous mode

syncd/SaiSwitch.cpp, syncd/SaiSwitch.h
Why I did:
Fix is for the issue as reported in https://github.com/Azure/sonic-buildimage/issues/5274
Fix https://github.com/Azure/sonic-buildimage/issues/5274
Basically Switch Internal OID should always be accounted in Temp and
Current Logic Comparison. It should never trigger remove operation.
Changes is to always add Switch Internal OID to COLDVIDS (even in case of
warm-boot)
Signed-off-by: Abhishek Dosi <abdosi@microsoft.com>
How I verfiy:
a) After change above issue is resolved
b) Dump COLDVIDS/ASIC_VIEW/HIDDEN Table and Switch Internal OID's are accounted in all 3 tables
=> Fix Warmboot Issue when upgraded Image SAI return Switch Internal OID not accounted in previous image.

meta/saiserialize.cpp
Looks like a typo. It should be 32 instead of 16.
=> Fix typo at SAI_ATTR_VALUE_TYPE_ACL_FIELD_DATA_UINT32

syncd/Syncd.cpp
During warm boot we also need to update notification pointers when creating switch in warm boot mode, since syncd/vendor_sai_lib could be loaded at different address space, and this can lead to SIGSEGV, since previous address may not be available
=> [syncd] Fix passing switch pointers during warm boot

syncd/Syncd.cpp, syncd/VirtualOidTranslator.cpp, syncd/VirtualOidTranslator.h
**What I did**
Let `processClearStatsEvent` notify orchagent instead of crashing orchagent when `TranslateVidToRid` fails.
In INIT_VIEW during warm-reboot, the FlexCounterOrch tries to clear stats for BUFFER_POOL_WATERMARK. This is expected to fail in INIT_VIEW in `TranslateVidToRid` since the object is not yet created. In such a scenario, the syncd should respond with a failure rather than crashing orchagent.
Verified using virtual switch.
=> [syncd] Notify orchagent instead of shutting down swss when translateVidToRid fails in processClearStatsEvent

syncd/FlexCounter.cpp
New SAI version provides more counters for fabric ports. Extend the supported counter list to cover those counters.
/** SAI port stat if in FEC correctable pkts */
SAI_PORT_STAT_IF_IN_FEC_CORRECTABLE_FRAMES,
/** SAI port stat if in FEC not correctable pkts */
SAI_PORT_STAT_IF_IN_FEC_NOT_CORRECTABLE_FRAMES,
/** SAI port stat if in FEC symbol errors */
SAI_PORT_STAT_IF_IN_FEC_SYMBOL_ERRORS,
/** Fabric port stat in data units */
SAI_PORT_STAT_IF_IN_FABRIC_DATA_UNITS,
/** Fabric port stat out data units */
SAI_PORT_STAT_IF_OUT_FABRIC_DATA_UNITS,
/** Port stat in drop reasons range start */
SAI_PORT_STAT_IN_DROP_REASON_RANGE_BASE = 0x00001000,
Signed-off-by: ngocdo <ngocdo@arista.com>
=> [fabric] Extend supported counter list in syncd's FlexCounter for fabric

vslib/src/SwitchConfig.cpp
Fix `parseBootType()` function so that it could work with fast reboot in virtual switch.
=> [fast-reboot] fix boot type for fast boot in virtual switch

syncd/scripts/gbsyncd_startup.py
=> [gbsyncd] exit with zero when platform has no gearbox

syncd/NotificationProcessor.cpp
The event SAI_FDB_EVENT_MOVE should do the same operation like SAI_FDB_EVENT_LEARNED.
Signed-off-by: Vincent Chiang (vincent_chiang@edge-core.com)
=> Fix SAI_FDB_EVENT_MOVE not supported error

lib/src/Sai.cpp
Signed-off-by: Lawrence Lee <lawlee@microsoft.com>
Fixes Azure/sonic-buildimage#5570
At the current log level of NOTICE, it is possible for this message to get spammed thousands of times, leading to syslog rate-limiting at the default orchagent log level of NOTICE.
=> [Sai]: Change Sai::set log to level INFO

syncd/FlexCounter.cpp, syncd/FlexCounter.h, syncd/FlexCounterManager.cpp
- The bug description
When the last object in FlexCounter was removed, the FlexCounter is also removed from FlexCounterManager. At the next time, when a new observed object is added and a new FlexCounter will be created. But the new FlexCounter cannot get the configuration. Because the configuration message from FlexCounterDB has been consumed at the first time.
- How to fix it
Add a flag to indicate whether the configuration also be removed from the FlexCounterDB. If not, don't delete the FlexCounter from FlexCounterManager even no observed objects in the FlexCounter.
=> [syncd/FlexCounter]:Fix last remove bug

syncd/scripts/syncd_init_common.sh
**- Why I did it**
This PR follows https://github.com/Azure/sonic-buildimage/pull/5644 to use template file `/usr/share/sonic/templates/swss_vars.j2` to retrieve vars for orchagent and syncd.
Use template file `/usr/share/sonic/templates/swss_vars.j2` to retrieve vars in `syncd_init_common.sh`
Verified with on kvm
=> [syncd_init_common.sh] Use template file to retrieve vars

syncd/VendorSai.cpp
there is command line switch for syncd which was added recently "-l" i think, and it enables use for bulk vendor sai api, previously by default we used 1by1, so actually those error messages are kind a justified that they are in ERROR, since in syncd command line right now we explicitly ask for bulk api
=> [syncd] Lower bulk missing api message level from error to info

syncd/scripts/syncd_init_common.sh
currently disabled since most vendors don't support that yet
=> [syncd] Disable use bulk api by default

meta/sai_serialize.h, meta/saiserialize.cpp, syncd/FlexCounter.cpp, syncd/FlexCounter.h
This PR depends on schema modification: https://github.com/Azure/sonic-swss-common/pull/403
=> Add FlexCounter for MACsec SA

syncd/VendorSai.cpp
SAI_OBJECT_TYPE_NEXT_HOP_GROUP_MEMBER object type should be used for m_apis.next_hop_group_api->create_next_hop_group_members
NEXT_HOP_GROUP object type has no bulk api at all
=> [syncd] Fix bulk api object type for next hop group members

syncd/RedisClient.cpp, syncd/RedisClient.h, syncd/Syncd.cpp
When using SAI bulk in syncd, like create/remove route_entry, we want to have ability to update database as fast as possible, so best way would be to execute every mutable db command inside lua script to make things faster, rather than execute 1 by 1 operation which is done currently inside syncd
depends on https://github.com/Azure/sonic-swss-common/pull/406
=> [syncd] Use lua script to update db when using bulk api

lib/src/ZeroMQChannel.cpp, syncd/ZeroMQNotificationProducer.cpp, tests/Makefile.am, tests/tests.cpp
There is issue with publisher/subscriber, which I use in notification delivery in zmq channel in sairedis. Issue is that first message/notification I never delivered from publisher to subscriber, and seems like this issue is still not solved ☹ Here are details: https://github.com/zeromq/libzmq/issues/2267
=> [syncd][sairedis] Change pub/sub model to push/pull in zmq notification

vslib/inc/CorePortIndexMapContainer.h, vslib/src/CorePortIndexMapContainer.cpp
Signed-off-by: vedganes <vedavinayagam.ganesan@nokia.com>
Core Port-Index Map support for VOQ system ports. This is part of SAI support of VOQ VS testing. This PR has container class for Voq Core port index map.
=> [vs] SAI support for VoQ switch - Core Port Index Map Container

vslib/inc/CorePortIndexMapFileParser.h, vslib/src/CorePortIndexMapFileParser.cpp
Core Port-Index Map support for VOQ system ports. This is part of SAI support of VOQ VS testing. This PR has a class for Core port-index map file parser
=> [vs] SAI support for VOQ switches - Core Port Index Map File parser

vslib/inc/CorePortIndexMap.h, vslib/src/CorePortIndexMap.cpp
Core Port-Index Map support for VOQ system ports. This is part of SAI support of VOQ VS testing
=> [vs] SAI support for VOQ switches

vslib/inc/SwitchStateBase.h, vslib/src/SwitchStateBase.cpp
SAI emulation support added for VOQ system ports. The changes include switch create initialization for VOQ switch objects. APIs for VOQ switch objects initialization, System Port configuration and System Port list initialization are provided.
=> [vs] SAI support for VOQ switches - Switch State Initialization

vslib/inc/SwitchBCM81724.h, vslib/inc/SwitchStateBase.h, vslib/inc/VirtualSwitchSaiInterface.h, vslib/src/SwitchBCM81724.cpp, vslib/src/SwitchStateBase.cpp, vslib/src/VirtualSwitchSaiInterface.cpp
VOQ switch objects are initialized during swich create. This VOQ objects
are initialized after regular switch objects are initialized. This PR depends on https://github.com/Azure/sonic-sairedis/pull/701
for switch state initialization
=> [vs] Initialization of VOQ switch objects

meta/Makefile.am, meta/Meta.cpp, meta/Meta.h, meta/MetaKeyHasher.cpp, meta/MetaKeyHasher.h, meta/SaiObject.cpp, meta/SaiObject.h, meta/SaiObjectCollection.cpp, meta/SaiObjectCollection.h, meta/tests.cpp
Currently unordered_map with std::string key is used, but since sai_serialize_object_meta_key is expensive, it make sense to keep original meta_key as key and write custom hash function. For 100k routes, metadata speeds up 3x when using custom hash.
=> [meta] Use custom hash in SaiObjectCollection

vslib/inc/MACsecForwarder.h, vslib/src/MACsecForwarder.cpp
MACsec Forwarder is for forwarding plaintext data traffic from MACsec device to tap, `Ethernet`, device.
The design document can be found at https://github.com/Azure/SONiC/blob/88c7ada900051f73a29aaf4a28bcaf5062ae7305/doc/macsec/MACsec_hld.md#345-virtual-macsec-sai
=> [vslib]Add MACsec Forwarder

vslib/inc/MACsecEgressFilter.h, vslib/inc/MACsecFilter.h, vslib/inc/MACsecIngressFilter.h, vslib/inc/TrafficFilter.h, vslib/inc/TrafficFilterPipes.h, vslib/src/MACsecEgressFilter.cpp, vslib/src/MACsecFilter.cpp, vslib/src/MACsecIngressFilter.cpp, vslib/src/TrafficFilterPipes.cpp
The document about MACsec Filters can be found at: https://github.com/Azure/SONiC/blob/88c7ada900051f73a29aaf4a28bcaf5062ae7305/doc/macsec/MACsec_hld.md#345-virtual-macsec-sai
All filters will be installed in `HostInterfaceInfo` to filter the EAPOL and data traffic.
The `MACsecEgressFilter` will forward EAPOL packets to eth device and forward data packets to MACsec device.
The `MACsecIngressFilter` will forward EAPOL packets to Ethernet device and drop all data packets. Because the data packets will be forwarded to MACsec device by Linux kernel.
The `TrafficFilterPipes` provides an interfaces to add more filters for future functions.
=> [vslib]Add MACsec Filters

vslib/src/SwitchStateBaseMACsec.cpp
=> [vslib] Add StateBase function for MACsec

vslib/inc/HostInterfaceInfo.h, vslib/inc/MACsecFilter.h, vslib/inc/MACsecForwarder.h, vslib/inc/SwitchStateBase.h, vslib/inc/TrafficForwarder.h, vslib/src/HostInterfaceInfo.cpp, vslib/src/MACsecForwarder.cpp, vslib/src/MACsecManager.cpp, vslib/src/Makefile.am, vslib/src/TrafficForwarder.cpp
Add MACsec filter before VLAN Tag and FDB event processing.
Refer: MACsec in VLAN-aware Bridges
=> [vslib]Add MACsec forward and filters to HostInterfaceInfo

syncd/Syncd.cpp, vslib/src/VirtualSwitchSaiInterface.cpp
Print extra information about loading warm boot state file, like file
size and number of switches loaded from that file.
=> [vs] Fail switch create when warm boot requested and no warm boot state

vslib/src/SwitchStateBase.cpp, vslib/src/tests.cpp
Signed-off-by: Prabhu Sreenivasan <prabhu.sreenivasan@broadcom.com>
Adds SAI_SWITCH_ATTR_SUPPORTED_OBJECT_TYPE_LIST to switch attributes.
Related PRs:
https://github.com/Azure/sonic-swss/pull/1525
=> Switch Capability support

vslib/inc/SwitchStateBase.h, vslib/src/MACsecManager.cpp, vslib/src/Makefile.am, vslib/src/SwitchStateBase.cpp, vslib/src/SwitchStateBaseMACsec.cpp
=> [vslib]: Add MACsec state to state base

meta/Meta.cpp, saidiscovery/Makefile.am, saidiscovery/saidiscovery.cpp
Replace static check_mandatory_attributes with Meta object, which automatically checks for mandatory objects on create switch. Previous function was incorrectly demanding mandatory objects which are on condition.
=> [saidiscovery] Update saidiscovery to use VendorSai object and metadata

syncd/syncd.cpp, syncd/syncd.h, syncd/syncd_notifications.cpp
So it’s basically race condition between removing bridge port and fdb flush notification. After bridge port is removed, fdb flush notification arrives, and tries to translate removed port, and fails. This PR fixes that.
Also this PR also removes all fdb entries from redis db right after fdb flush success, and not in fdb notification.
=> [syncd] Translate removed RIDs in fdb notification

vslib/src/MACsecManager.cpp
=> [vs] Use /sbin/ip absolute path for ip command in MACsecManager

syncd/syncd_flex_counter.cpp
Signed-off-by: Volodymyr Samotiy <volodymyrs@nvidia.com>
* Extended supported counters for "flex counter" logic in order to add support of PFC pause duration counters in microseconds.
* Updated SAI submodule in order to get headers with PFC pause duration counters in microseconds.
* SAI submodule commit ID: ```8a88e31201bff375cadf7db4858735fc2c84571b```
=> [SAI] Add PFC pause duration counters in microseconds

meta/saiserialize.cpp, syncd/ComparisonLogic.cpp, syncd/SaiAttr.cpp, syncd/SaiSwitch.cpp
If attribute is enum, and we are loading some older SAI values it may happen that we get deprecated/ignored value string and we need to update it to current one to not cause attribute compare confusion since they are compared by string value.
This fixes issues when warm shutdown on 201811 branch, and warm boot on master branch.
=> [syncd] Translate depreacated attr enum values to new ones

configure.ac
Some older gcc version may not support strict parameter
=> Configure enable -Wcast-align=strict when supported by compiler

vslib/src/MACsecManager.cpp
Some build containers for sonic-buildimage may not have ip command, and for non MACsec test's this is not required to be present.
=> [vs] Skip MACsec clean up if /sbin/ip is not accessible

vslib/src/MACsecManager.cpp
@Pterosaur please address this when you will be available
=> [vs] Add workaround for clean up macsec ports

vslib/inc/SwitchBCM56850.h, vslib/inc/SwitchStateBase.h, vslib/src/SwitchBCM56850.cpp, vslib/src/SwitchStateBase.cpp
Signed-off-by: Prabhu Sreenivasan <prabhu.sreenivasan@broadcom.com>
Add Queues to CPU port on vslib
=> CPU queues on vslib

syncd/RedisClient.cpp
The template version of hgetall() could work with either map or unordered_map.
=> Use template hgetall, because we will tune the return types of library functions

lib/inc/sai_redis.h, lib/inc/sairedis.h, lib/src/sai_redis_record.cpp, lib/src/sai_redis_switch.cpp
The PR implements the handling of the sairedis rec filename passed to the orchagent.
This PR is porting changes done in https://github.com/Azure/sonic-sairedis/pull/747 to 201911
Corresponding swss pr : Azure/sonic-swss#1546
This change is mainly to be used for multi asic devices where each asic.
Signed-off-by: Arvindsrinivasan Lakshmi Narasimhan <arlakshm@microsoft.com>
=> [201911][logfile] sairedis record file handling

vslib/inc/SwitchStateBase.h, vslib/src/SwitchStateBase.cpp
Signed-off-by: Prabhu Sreenivasan <prabhu.sreenivasan@broadcom.com>
This change is required for https://github.com/Azure/sonic-swss/pull/1511
=> Add support for SAI_SWITCH_ATTR_AVAILABLE_IPMC_ENTRY needed by CRM

vslib/src/SwitchStateBase.cpp
Fix vstest lib to let https://github.com/Azure/sonic-swss/pull/1431 go.
Signed-off-by: ngocdo <ngocdo@arista.com>
=> Do not create fabric port in vslib if mapping is not available

vslib/src/SwitchStateBase.cpp
Missing MACsec Create Port action in `SwitchStateBase::create`. This bug will cause MACsec SC Crate action fail.
=> [vslib]:Fix missing MACsec Create Port action

vslib/src/NetMsgRegistrar.cpp
Fixes: https://github.com/Azure/sonic-buildimage/issues/6466
This is a temporary fix to avoid double-free memory corruption (and core) that is consistently seen in syncd shutdown in KVM switch.
The call made to unregisterMessageHandler as part of NetMsgRegistrar thread causes, double-free memory corruption in one of the executing threads.
=> Remove unregisterMessageHandler from NetMsgRegistrar thread

lib/src/PerformanceIntervalTimer.cpp, lib/src/VirtualObjectIdManager.cpp
This commit fixes a syncd crash seen when running the sonic-mgmt comunity test
suites against the Marvell armhf platform. Analysis of the generated core file
points to improper format specifiers used when writing SWSS log entries. This
commit fixes that.
=> [syncd armhf] Fix syncd crash when running community test suites

azure-pipelines.yml
Libboost 1.71 is already installed in slave buster. Do not install v1.67 on top of it.
singed-off-by: Tamer Ahmed <tamer.ahmed@microsoft.com>
=> [build-vm] Don't Install Lib Boost 1.67

syncd/syncd_flex_counter.cpp
Signed-off-by: Volodymyr Samotiy <volodymyrs@nvidia.com>
Extended supported counters for "flex counter" logic in order to add support of PFC pause duration counters in microseconds.
=> [201911][Flex Counters] Add PFC pause duration counters in microseconds

azure-pipelines.yml
avoid to use publish build artifacts and pipeline artifacts
at the same time.
=> [ci]: use publish pipeline artifacts to publish syslog

syncd/Syncd.cpp
As I didn't see SAI specifying that the user of the service table should reset the iterator before iterating over the values, I think this would come as a surprise to most vendors implementing SAI. Because the iterator was first stored before adding any values to the map, it would be pointing to the profile's .end(), thus if a SAI implementation would try iterating over the values,  it'd get none until it'd reset the iterator.
=> syncd: Fix profile iterator bug

lib/inc/sai_redis.h, lib/inc/sairedis.h, lib/src/sai_redis_fdb.cpp, lib/src/sai_redis_generic_get.cpp, lib/src/sai_redis_generic_set.cpp, lib/src/sai_redis_generic_stats.cpp, lib/src/sai_redis_interfacequery.cpp, lib/src/sai_redis_switch.cpp
=> [sairedis] Add get response timeout knob

debian/control
libsairedis-dev is not usable without libzmq5-dev package, meaning I cannot link my binary without a symlink to .so file provided by dev package. Make it implicitly install by apt-get install -f
Signed-off-by: Stepan Blyshchak <stepanb@nvidia.com>
=> [debian/control] libsairedis-dev depends on libzmq5-dev

syncd/ComparisonLogic.cpp, syncd/SaiSwitch.cpp, syncd/SaiSwitchInterface.cpp, syncd/SaiSwitchInterface.h, vslib/inc/SwitchBCM56850.h, vslib/inc/SwitchMLNX2700.h, vslib/inc/SwitchStateBase.h, vslib/src/SwitchBCM56850.cpp, vslib/src/SwitchMLNX2700.cpp, vslib/src/SwitchStateBase.cpp, vslib/src/VirtualSwitchSaiInterface.cpp
When doing warm boot from older SAI (201811) to master some attributes
maybe not implemented in previous version, but they are expected to be
present on new version. Special logic is required to populate those
default attributes after warm boot.
=> [vs] Add special warm boot logic to populate default attributes

syncd/syncd_flex_counter.cpp
m_pollInterval is used out of the MUTEX lock，when set to a smaller value, it may result of wait for a very long time.
=> Update FlexCounter.cpp, use m_pollInterval in MUTEX lock

configure.ac
When arm platform is compiled, because of ABI warning we get a ton of logs notes:
```
note: parameter passing for argument of type XXX changed in GCC 7.1
```
which pollutes log to a level when it's hard to spot actual error
=> [configure] Add -Wno-psabi to remove "passing argument changed" logs note on arm

syncd/scripts/gbsyncd_startup.py
According to the Python community, `#!/usr/bin/python` is not a portable shebang and is discouraged in favor of `#!/usr/bin/env python[x]`.
The former shebang worked with Python 2, but with the recent migration to Python 3, the Python 3 package installed in SONiC does not install an executable or symlink at `/usr/bin/python`, thus generating the following error:
```
Mar 17 07:32:19.743425 vlab-01 INFO gbsyncd#/supervisord: syncd /usr/bin/gbsyncd_start.sh: /usr/bin/gbsyncd_startup.py: /usr/bin/python: bad interpreter: No such file or directory
```
This patch updates the shebang to `#!/usr/bin/env python3` and also makes the script executable, however that did not pose an issue because the script appears to get executable permissions when it is installed, but it can't hurt.
=> [gbsyncd] Fix shebang in gbsyncd_startup.py; Make script executable

syncd/scripts/gbsyncd_start.sh
`gbsyncd_start.sh` was a simple wrapper which only called `exec "/usr/bin/gbsyncd_startup.py"`. This causes unnecessary extra complexity and maintenance. It makes things simpler to run `/usr/bin/gbsyncd_startup.py` directly, which is being done by https://github.com/Azure/sonic-buildimage/pull/7084. That PR has merged, so we can now merge this.
=> Remove gbsyncd_start.sh

syncd/scripts/gbsyncd_startup.py, syncd/scripts/gbsyncdmgrd
Introduce `gbsyncdmgrd`, which will be responsible for spawning and watching all gearbox syncd processes.
`gbsyncdmgrd` is intended to supplant `gbsyncd_startup.py`. But until all references have been updated, we keep both, and I have added a deprecation warning to `gbsyncd_startup.py`.
=> Introduce gbsyncdmgrd; Deprecate gbsyncd_startup.py

lib/inc/SaiInternal.h, lib/src/Sai.cpp
This will remove possible deadlock when notification arrives during communication channel destructor thread join.
Could result in deadlock when destructing RedisChannel and logs: ~RedisChannel: join ntf thread begin
=> [sairedis] Unlock api mutex for communication mode

lib/src/sai_redis_interfacequery.cpp
All apis needs to be implemented when using pyext module.
=> [sairedis] Add sai_dbg_generate_dump api to redis interface

vslib/inc/SwitchStateBase.h, vslib/src/SwitchStateBase.cpp
Fix the following error message, when setting PFC WD config on port in swss vs test development.
```
114470 Mar 27 11:48:56.959426 97dc8d648d1a WARNING #syncd: :- refresh_read_only: need to recalculate RO: SAI_QUEUE_ATTR_PAUSE_STATUS
114471 Mar 27 11:48:56.959444 97dc8d648d1a ERR #syncd: :- collectQueueAttrs: Failed to get attr of queue 0x15000000000168: -15
```
`SAI_QUEUE_ATTR_PAUSE_STATUS` is prevented from being set to `COUNTERS_DB` on fake broadcom platform. The absence of `SAI_QUEUE_ATTR_PAUSE_STATUS` will cause pfc detect lua to exist early, not being able to reach the point of faking PFC storm using `DEBUG_STORM` in vs test.
Needed by https://github.com/Azure/sonic-swss/pull/1612
```
2021-03-30T05:35:44.3797880Z =================================== FAILURES …
```
=> [vslib] Refresh queue pause status

configure.ac, pyext/py2/Makefile.am, pyext/py3/Makefile.am
Older swig version may generate some code that can warn on long to double conversion - currently observed on sonic-buildimage repo
=> [pyext] Update Makefile to disable warning Wconversion for older swig

vslib/src/SwitchStateBaseHostif.cpp
Signed-off-by: Volodymyr Samotiy <volodymyrs@nvidia.com>
Allow host interface object ID to be "VLAN" type.
Needed for VS test for the following changes: https://github.com/Azure/sonic-swss/pull/1645
=> [vslib] Allow host interface object ID to be "VLAN" type

.azure-pipelines/docker-sonic-vs/Dockerfile
What I did:
Looks like there is some issue with sonic-vs docker used in sonic-sai-redis repo for swss DVS test.
Swss debian package used in VS docker is not the same artifact generated by Azure pipeline
Compared md5sum of binaries of Azure artifact swss debian package and the one running in VS docker and they are not matching. And thus test fails.
Tried locally also:
Docker from Artifact ==> Test Fails
Docker from Artifact + Using swss debian from Artifact ==> Test passes.
Eg:
md5sum of sflowmgrd as part of docker-sonic-vs artifact 47e395fddbc5ab29c57477013e6dde70
md5sum of sflowmgrd as part of swss*.deb artifact beb6e096b2923716823754b3477133cb
Confirmed:-
- sflowmgrd as part of docker-sonic-vs is from the base sonic-docer-vs and dpkg -i swss*.deb did not updated all the processes.
- …
=> fix dvs test failure because of debian packages not installed correctly in base docker-vs image

configure.ac, debian/rules, python/Makefile
When making build sairedis directory could be polluted by previous build
which was configured without '--enable-syncd=no', and that created
makefiles for previous build for example binary-syncd target, next when
dh clean is executed for target binary-sairedis, it's executing existing
configure with previous parameters by executing "./bin/bash
./config.status .recheck", this don't contain --enable-syncd=no, and
this requires libsai to be present for configuration, this will cause
configure to fail, but dh clean will ignore that error and continue next
commands. Because of this, make distclean was not executed, and
directory contains previous build artifacts like _pysairedis.la in pyext
directory, which was from stretch build, and points to different python
version 3.5 vs 3.7 on buster, and …
=> Disable syncd on binary-sairedis target during dh clean

lib/inc/sairedis.h
What I did:
Increase SAI Sync operation timeout from 1 min to 6 min by reverting https://github.com/Azure/sonic-sairedis/pull/472
Why I did:
Issue as mention https://github.com/Azure/sonic-buildimage/issues/3832 is seen when there is link/port-channel flaps towards T2  which results in sequence of this operation on T1 topology:-
Link Going down
- Next Hop Member removal from Nexthop Group
- Creation of New Nexthop Group
- All the Routes towards T2 are given SET Operation with new Nexthop Group (6000+ routes)
Link Going up
- Creation of New Nexthop Group
- All the Routes towards T2 are given SET Operation with new Nexthop Group (6000+ routes)
Above Sequence with flaps create many SAI operation of CREATE/SET and if SAI is slow to process them if there in any intermediate Get operation …
=> [201911] Increase SAI Sync operation timeout from 1 min to 6 min.

syncd/scripts/syncd_init_common.sh
Create in Mellanox devices a folder from sai.profile key SAI_DUMP_STORE_PATH in the syncd docker to have it ready for SDK dumps
=> [Mellanox] Update Mellanoxs dump generation to include SDK dumps

lib/src/ContextConfigContainer.cpp, lib/src/SwitchConfigContainer.cpp, syncd/Syncd.cpp, tests/aspell.en.pws, vslib/inc/Context.h, vslib/inc/ContextConfig.h, vslib/inc/ContextConfigContainer.h, vslib/inc/Sai.h, vslib/inc/SwitchConfig.h, vslib/inc/SwitchConfigContainer.h, vslib/inc/saivs.h, vslib/src/Context.cpp, vslib/src/ContextConfig.cpp, vslib/src/ContextConfigContainer.cpp, vslib/src/Makefile.am, vslib/src/Sai.cpp, vslib/src/SwitchConfig.cpp, vslib/src/SwitchConfigContainer.cpp, vslib/src/SwitchStateBase.cpp
So far virtual switch supported only 1 switch to be created and only default hwinfo which was empty string. This change allows to reuse context_config.json to allow multiple switches to be created in virtual switch and each can have different hwinfo. This scenario can be useful when running VS test with multiple swss containers running.
=> [VS] Add support for context and multiple switches

syncd/scripts/syncd_init_common.sh
https://github.com/Azure/sonic-sairedis/pull/830 adds support to bring up multi-asic Virtual switch.
In multi-asic VS switch, there are multiple swss and syncd dockers. Orchagent process in each swss is started with a different hwinfo(asic_id). This PR is to ensure that context configuration is passed in syncd which has the hwinfo information with which each orchagent is started. 
Signed-off-by: Suvarna Meenakshi <sumeenak@microsoft.com>
=> [vs]: Start syncd by passing context configuration file and global context index.

syncd/syncd_flex_counter.cpp
Issue:
Rif Counters can not work when removing one router interface https://github.com/Azure/SONiC/issues/729 
Root cause:
In function FlexCounter::removeRif in 201911 branch, removing the whole instance leads to zero the poll interval and therefore will not receive rif events.
As a result of not receiving rif events, the rif thread will not started and therefore the counters table will not filled up.
The symptom is N/A values in "show interfaces counters rif" command.
Fix:
Instead of removing the whole instance, remove the counter from the m_collectCountersHandlers.
Signed-off-by: Noa Or <noaor@nvidia.com>
=> [RIF] Bug fix for Issue #729

syncd/scripts/syncd_init_common.sh
The changes add cisco-8000 to syncd_init_common.sh. This is required to minimally bring up syncd for cisco-8000 based platforms.
=> add cisco-8000 checks to syncd_init_common

meta/Meta.cpp, tests/aspell.en.pws, vslib/src/VirtualSwitchSaiInterface.cpp
**What I did**
Minor tweaks to VS for MPLS support for CRM polling of MPLS In-segments and NHs.
Allows MPLS CRM support to function properly with VS.
Unit-tests in sonic-swss/tests/test_mpls.py.
Refer to HLD:  https://github.com/Azure/SONiC/pull/706
=> sonic-sairedis updates for MPLS

.azure-pipelines/build-docker-sonic-vs-template.yml, .azure-pipelines/build-swss-template.yml, .azure-pipelines/build-template.yml, .azure-pipelines/test-docker-sonic-vs-template.yml, azure-pipelines.yml
Fix branch reference error, change master to 202012
=> Fix branch reference error

syncd/Syncd.cpp
Syncd::processBulkOidRemove() is incorrectly passing objectVids.data() to m_vendorSai->bulkRemove() when it should be passing objectRids.data(). 
Only RID should be passed to m_vendorSai calls. 
Issue can be seen when SAI bulk APIs are enabled in syncd and the following sequence of iproute2 commands are executed:
"ip route add \<ip-prefix> nexthop via inet \<ip-gateway-1> dev \<port-1> nexthop via inet \<ip-gateway-2> dev \<port-2>"
"ip route del \<ip-prefix> nexthop via inet \<ip-gateway-1> dev \<port-1> nexthop via inet \<ip-gateway-2> dev \<port-2>"
=> [syncd] bulk OID remove requires RID

syncd/scripts/syncd_init_common.sh
This fix brings in support for cisco-8000 platform into sonic-sairedis/syncd. It checks for the SONIC_ASIC_TYPE keyword and picksup the PLATFORM type to see if "cisco-8000" word is available. Accordingly, it sources the required paths for SDK to carry on its operations.
=> CISCO: Support for cisco-8000 platform for sonic-sairedis/syncd

vslib/inc/VirtualSwitchSaiInterface.h, vslib/src/Sai.cpp, vslib/src/VirtualSwitchSaiInterface.cpp
Will help using multiple switches in VS with multiple contextes.
=> [VS] Fix context config guid on RealObjectIdManager

syncd/scripts/gbsyncdmgrd
Signed-off-by: Andriy Kokhan <andriyx.kokhan@intel.com>
Fixed the spawning of gearbox syncd processes.
```
Jul 11 09:30:17.336147 localhost INFO gbsyncd#supervisord 2021-07-11 09:30:17,334 INFO spawned: 'gbsyncdmgrd' with pid 20 
Jul 11 09:30:17.393517 localhost INFO gbsyncd#/supervisord: gbsyncdmgrd Traceback (most recent call last):
Jul 11 09:30:17.393601 localhost INFO gbsyncd#/supervisord: gbsyncdmgrd   File "/usr/bin/gbsyncdmgrd", line 93, in <module>
Jul 11 09:30:17.393640 localhost INFO gbsyncd#/supervisord: gbsyncdmgrd     sys.exit(main())
Jul 11 09:30:17.393675 localhost INFO gbsyncd#/supervisord: gbsyncdmgrd   File "/usr/bin/gbsyncdmgrd", line 66, in main
Jul 11 09:30:17.393709 localhost INFO gbsyncd#/supervisord: gbsyncdmgrd     proc_list = physyncd_spawn(gearbox_config)
Jul 11 …
```
=> Fixed Popen args in physyncd_spawn()

lib/src/RedisRemoteSaiInterface.cpp, syncd/Syncd.cpp
If bulk api is not supported, syncd will fallback to execute 1 by 1, but status overall was not success when started, this will address that.
=> [syncd] Fix status success on bulk fallback

syncd/RedisClient.cpp
=> [syncd] Fix access coldvid table per switch

lib/inc/Recorder.h, lib/src/Recorder.cpp, lib/src/RedisRemoteSaiInterface.cpp
Start recording CRS operations response to sairedis.rec but only when
response is not success.
=> [sairedis] Record create, remove and set response in sync mode

lib/inc/Recorder.h, lib/src/Recorder.cpp, lib/src/RedisRemoteSaiInterface.cpp
Use new api to record hardware info when creating switch for easy read. Since hardware info attribute type is s8list, it will be serialized as array of integers, so to actually improve readability of actual value, put it as comment in recording file.
=> [sairedis] Add comment api to recorder

syncd/Makefile.am, syncd/Syncd.cpp, syncd/Syncd.h, syncd/TimerWatchdog.cpp, syncd/TimerWatchdog.h, syncd/WatchdogScope.cpp, syncd/WatchdogScope.h
When watchdog thread will exceed 30sec it will print currently executing event like create/remove/get/set. This data can be also found in sairedis.rec, but this PR will also print this in syslog for convenience.
=> [syncd] Add event name to timer watchdog

syncd/Syncd.cpp, syncd/TimerWatchdog.cpp, syncd/TimerWatchdog.h, syncd/WatchdogScope.cpp, syncd/WatchdogScope.h
In case of long event execution time, we want to know all the parameters that were passed to events, not only event name. For example when doing create/set SAI api we also want to get all the parameters that were passed to it.
=> [syncd] Add event data for timer watchdog to log entire event

meta/Makefile.am
All those flags are just warnings, and were already checked in SAI repo during PR validation.
=> [meta] Simplify compilation for saimetadata.c

tests/Makefile.am, tests/main.cpp
Main motivation is to avoid linking the same files across different directories to simplify future coverage data collection.
=> [tests] Add vssyncd it's own main.cpp

syncd/scripts/syncd_init_common.sh
In multi-asic BCM switch, there are multiple swss and syncd dockers. Orchagent process in each swss is started with a different hwinfo(asic_id). This PR is to ensure that context configuration is passed in syncd which has the hwinfo information with which each orchagent is started.
This change is similar to done for VS target
=> [syncd][bcm] Start syncd by passing context configuration file

lib/Switch.cpp, meta/Makefile.am, meta/Meta.cpp, meta/Meta.h, meta/NotificationBfdSessionStateChange.cpp, meta/NotificationBfdSessionStateChange.h, meta/NotificationFactory.cpp, meta/SaiSerialize.cpp, meta/sai_serialize.h, pyext/pysairedis.cpp, saiplayer/SaiPlayer.cpp, saiplayer/SaiPlayer.h, syncd/NotificationHandler.cpp, syncd/NotificationHandler.h, syncd/NotificationProcessor.cpp, syncd/NotificationProcessor.h, syncd/SwitchNotifications.cpp, syncd/SwitchNotifications.h, syncd/Syncd.cpp, tests/aspell.en.pws, vslib/Switch.cpp, vslib/SwitchStateBase.cpp
Add sairedis and syncd support to handle and send back bfd session state change notifications.
=> Add support for BFD notification

.azure-pipelines/build-swss-template.yml, azure-pipelines.yml
What I did
AZP changes to install libnl3 from sonic-buildimage
Why I did it
Prevent sonic-sairedis AZP build failures in docker-sonic-vs.
fpmsyncd in sonic-swss now relies on modified version of libnl3 in sonic-buildimage with additional support for MPLS.
Any AZP build of docker-sonic-vs must now install libnl3 from sonic-buildimage build artifact rather than Debian released version of libnl3.
How I verified it
Unit-tests in sonic-swss/tests/test_mpls.py
System tests in sonic-mgmt
Details if related
Refer to PR:  https://github.com/Azure/sonic-swss/pull/1871
=> Install sonic-buildimage libnl3 for AZP

syncd/scripts/syncd_init_common.sh
Why I did it:    
Bulk was disable
How I did it:
enable bulk api`s in SAI for Barefoot
How to verify it:
Run sanity regression tests
=> [Barefoot] enable bulk api`s in SAI

vslib/SwitchStateBase.cpp, vslib/SwitchStateBase.h
To make the virtual SAI supports partial ports enabled.
Here is the qemu xml example that only enables two interfaces.
The SWSS will exit with an unexpected error as follow
I check the availability of eth-x ports at creating port.
=> [vslib]: Remove invalid lane when create ports

.azure-pipelines/build-template.yml
Support code diff coverage
1. Support to add the pull request checks for Code diff coverage in GitHub.
2. Support to display the code diff coverage html report in Azure Pipelines.
=> [ci]: Support code diff coverage

syncd/SwitchNotifications.cpp, syncd/SwitchNotifications.h
To satisfy LGTM alert and for performance reasons to
skip making unnecessary copy of struct.
=> [syncd] Fix SwitchNotifications to be const reference

syncd/scripts/gbsyncdmgrd
Need to startup gbsyncd in sync mode, since orchagent is using sync mode.
=> [gearbox] startup gbsyncd in sync mode in vSonic

meta/Meta.cpp, meta/SaiSerialize.cpp, unittest/meta/TestSaiSerialize.cpp, vslib/VirtualSwitchSaiInterface.cpp
* Added support for MAP_LIST serialization and deserialization
* Add FC to QoS maps
* Added a UT to validate the changes
* Add NHG map API implementation
* Add VS object availability for NHG maps
Signed-off-by: Alexandru Banu <v-albanu@microsoft.com>
=> [cbf] Add Class Based Forwarding support

vslib/SwitchStateBase.cpp
HLD: Azure/SONiC#867
Signed-off-by: Stepan Blyshchak <stepanb@nvidia.com>
=> [vslib] fill aclcapability.is_action_list_mandatory field

.azure-pipelines/build_and_install_module.sh
Fix the timeout issue when running the "install dependencies" step.
See https://dev.azure.com/mssonic/build/_build/results?buildId=51240&view=logs&s=859b8d9a-8fd6-5a5c-6f5e-f84f1990894e&j=3f6395b2-1619-5ebe-f305-2aedcf353cb5
Make the script .azure-pipelines/build_and_install_module.sh the same as https://github.com/Azure/sonic-utilities/blob/master/.azure-pipelines/build_and_install_module.sh
=> Fix hung issue when installing linux kernel modules

syncd/scripts/syncd_init_common.sh
Changes to add ACL_TABLE object to break-before-make list of objects during warm-reboot. This is done specifically for broadcom platforms where make-before-break approach results in insufficient resource error during ACL_TABLE creation, if old ACL__TABLEs are not deleted first.
Issue was observed during warm-reboot from 201811 to 202012
=> Add ACL_TABLE object to break-before-make list

meta/SaiSerialize.cpp, meta/sai_serialize.h, syncd/FlexCounter.cpp, syncd/FlexCounter.h, unittest/meta/TestSaiSerialize.cpp, unittest/syncd/Makefile.am, unittest/syncd/MockHelper.cpp, unittest/syncd/MockHelper.h, unittest/syncd/MockableSaiInterface.cpp, unittest/syncd/MockableSaiInterface.h, unittest/syncd/TestFlexCounter.cpp
**What I did**
Add trap flow counter support. See HLD: https://github.com/Azure/SONiC/pull/858
Flow counters are usually used for debugging, troubleshooting and performance enhancement processes. Host interface trap counter can get number of received traps per Trap ID.
Manual test/VS test/sonic mgmt test
=> [FlexCounter] Add trap flow counter support

syncd/scripts/syncd_init_common.sh
Cherry-picked https://github.com/Azure/sonic-sairedis/pull/970
Changes to add ACL_TABLE object to break-before-make list of objects during warm-reboot. This is done specifically for broadcom platforms where make-before-break approach results in insufficient resource error during ACL_TABLE creation, if old ACL__TABLEs are not deleted first.
Issue was observed during warm-reboot from 201811 to 202012
=> [202012] Add ACL_TABLE object to break before make list

syncd/NotificationQueue.cpp, syncd/NotificationQueue.h, unittest/syncd/Makefile.am, unittest/syncd/TestNotificationQueue.cpp
Recently in one of the production device we encountered a switch ran out of memory and crashed due to there were too many switch state event such as the following due to many multi bit ECC errors:
```
2021-11-06.18:20:10.251799|n|switch_state_change|{"status":"SAI_SWITCH_OPER_STATUS_FAILED","switch_id":"oid:0x0"}|
2021-11-06.18:20:10.251845|n|switch_state_change|{"status":"SAI_SWITCH_OPER_STATUS_FAILED","switch_id":"oid:0x0"}|
2021-11-06.18:20:10.252289|n|switch_state_change|{"status":"SAI_SWITCH_OPER_STATUS_FAILED","switch_id":"oid:0x0"}|
2021-11-06.18:20:10.252359|n|switch_state_change|{"status":"SAI_SWITCH_OPER_STATUS_FAILED","switch_id":"oid:0x0"}|
2021-11-06.18:20:10.252406|n|switch_state_change|{"status":"SAI_SWITCH_OPER_STATUS_FAILED","switch_id":"oid:0x0"}| …
```
=> Prevent other notification event storms to keep enqueue unchecked and drained all memory that leads to crashing the switch router

syncd/Syncd.cpp
Change the log severity level from ERROR to NOTICE if getStatus is not supported by vendor
This is to cherry-pick #908 to 202106.
Signed-off-by: Stephen Sun stephens@nvidia.com
=> Change the log severity level from ERROR to NOTICE if getStatus is not supported by vendor (cherry-pick #908)

lgtm.yml, syncd/NotificationQueue.cpp, syncd/NotificationQueue.h
This is to backport the fix made in master branch (https://github.com/Azure/sonic-sairedis/pull/968) to 202012 branch since it could not be cherry picked.
Copying the same info from above PR that we are back porting to this branch here for clarity of what the issue was about and how we are fixing it:
Recently in one of the production devices we encountered a switch ran out of memory and crashed due to there were too many switch state event such as the following due to many multi bit ECC errors:
```
2021-11-06.18:20:10.251799|n|switch_state_change|{"status":"SAI_SWITCH_OPER_STATUS_FAILED","switch_id":"oid:0x0"}|
2021-11-06.18:20:10.251845|n|switch_state_change|{"status":"SAI_SWITCH_OPER_STATUS_FAILED","switch_id":"oid:0x0"}|
2021-11-06.18:20:10.252289|n|switch_state_change|{"status":"SAI_SW …
```
=> [202012] Prevent other notification event storms to keep enqueue unchecked and drained all memory that leads to crashing the switch router

lgtm.yml, syncd/NotificationQueue.cpp, syncd/NotificationQueue.h
This is to backport the fix made in master branch (https://github.com/Azure/sonic-sairedis/pull/968) to 202106 branch since it could not be cherry picked.
Copying the same info from above PR that we are back porting to this branch here for clarity of what the issue was about and how we are fixing it:
Recently in one of the production devices we encountered a switch ran out of memory and crashed due to there were too many switch state event such as the following due to many multi bit ECC errors:
```
2021-11-06.18:20:10.251799|n|switch_state_change|{"status":"SAI_SWITCH_OPER_STATUS_FAILED","switch_id":"oid:0x0"}|
2021-11-06.18:20:10.251845|n|switch_state_change|{"status":"SAI_SWITCH_OPER_STATUS_FAILED","switch_id":"oid:0x0"}|
2021-11-06.18:20:10.252289|n|switch_state_change|{"status":"SAI_SW …
```
=> [202106] Prevent other notification event storms to keep enqueue unchecked and drained all memory that leads to crashing the switch router

meta/SaiSerialize.cpp, meta/sai_serialize.h, syncd/FlexCounter.cpp, syncd/FlexCounter.h, syncd/VendorSai.cpp, unittest/meta/TestSaiSerialize.cpp, unittest/syncd/TestFlexCounter.cpp
Build dependency on https://github.com/Azure/sonic-swss-common/pull/520
=> Support for MACsec statistics

unittest/vslib/TestSwitchBCM56850.cpp, vslib/SwitchStateBase.cpp, vslib/SwitchStateBase.h
What/Why I did:
Added Support for enum query capability of Nexthop Group Type.
This is needed for DVS testing of Ordered ECMP Feature.
Design Doc: https://github.com/Azure/SONiC/pull/896
Signed-off-by: Abhishek Dosi <abdosi@microsoft.com>
=> Added Support for enum query capability of Nexthop Group Type.

.azure-pipelines/build-docker-sonic-vs-template.yml
This PR will unblock the PR checker of sonic-sairedis
https://dev.azure.com/mssonic/build/_build/results?buildId=64993&view=logs&j=fd654701-c975-5a82-4ee2-7dfa2e6fd174&t=5fe9eff9-6918-5942-3485-495aa73e6e4b
=> Change sonic-buildimage.vs artifact source from CI build to official build.

.azure-pipelines/build-template.yml
* Put the downloaded swss common artifact in a separated directory while build sairedis target. 
* The downloaded swss common artifact is in a sub-directory of sairedis artifact, then it avoids overriding
the previous swss common packages.
=> [pipeline] Download swss common artifact in a separated directory

.azure-pipelines/build-docker-sonic-vs-template.yml, .azure-pipelines/build-swss-template.yml, .azure-pipelines/build-template.yml, .azure-pipelines/test-docker-sonic-vs-template.yml, azure-pipelines.yml
Download upstream pipelines 202106 branches' artifacts.
=> [build] Use 202106 branches in azure pipeline

saiasiccmp/SaiSwitchAsic.h, unittest/vslib/TestTrafficForwarder.cpp
Fixes #998
This includes two fixes. One for an issue where the string library must be explicitly imported. The solution was taken directly from the gcc-10 error message.
```
In file included from SaiSwitchAsic.cpp:1:
SaiSwitchAsic.h:24:46: error: 'string' is not a member of 'std'
24 |                     _In_ const std::map<std::string, sai_object_id_t>& hidden,
|                                              ^~~~~~
SaiSwitchAsic.h:4:1: note: 'std::string' is defined in header '<string>'; did you forget to '#include <string>'?
3 | #include "syncd/SaiSwitchInterface.h"
+++ |+#include <string>
4 |
```
The other fix is due to a cast-align warning introduced by gcc-10. This was fixed in another location in the code by https://github.com/Azure/sonic-sairedis/pull/894
I mirrored this same exact …
=> Fix build issues on gcc-10

tests/aspell.en.pws, unittest/vslib/Makefile.am, unittest/vslib/TestMACsecManager.cpp, unittest/vslib/TestSwitchStateBaseMACsec.cpp, vslib/MACsecManager.cpp, vslib/SwitchStateBaseMACsec.cpp
1. send_sci field enabled when create MACsec egress SC
2. ssci/salt field enabled when create MACsec ingress SA if the cipher is XPN
3. convert ssci to network order
=> [vslib]: Fix MACsec bug in SCI and XPN

.azure-pipelines/test-docker-sonic-vs-template.yml
This is a port of the changes in Azure/sonic-swss#2138.
Signed-off-by: Saikrishna Arcot <sarcot@microsoft.com>
=> Use the test agent pool managed by SONiC instead of the latest Azure image

syncd/ComparisonLogic.cpp, tests/BCM56850.pl, vslib/SwitchBCM81724.cpp
For created objects like buffer pool or buffer profile
those are not on the switch, but they were treated as such
and transferred to temporary view during comparison logic
causing to duplicate objects on temporary view
=> [syncd] Fix comparison logic for new transferred objects

configure.ac, debian/rules, syncd/Asan.cpp, syncd/Makefile.am, syncd/main.cpp
* add --enable-asan for syncd compilation
* add SIGTERM handler that calls __lsan_do_leak_check() to generate a
report
Signed-off-by: Yakiv Huryk <yhuryk@nvidia.com>
=> [asan] add address sanitizer support for syncd

lib/sai_redis.h, lib/sai_redis_tunnel.cpp, unittest/lib/test_sai_redis_tunnel.cpp, unittest/vslib/test_sai_vs_tunnel.cpp, vslib/sai_vs.h, vslib/sai_vs_tunnel.cpp
Signed-off-by: bingwang <bingwang@microsoft.com>
Changes include
```
- d0f3333 Tunnel Scoped TC MAP and Remarking (#1413) (#1451)
- 62364a3 Add two more API as RPC for warmboot testing (#1421) (#1437)
- 426fad1 Make saithriftv compatible with thrift 0.14.1 (#1433)
```
Also update `sai_redis_tunnel` and `sai_vs_tunnel` to fix build issue.
=> [submodule update] SAI submodule update

configure.ac, syncd/Makefile.am, syncd/SaiSwitch.cpp, syncd/Syncd.cpp
Enable SAI_SWITCH_ATTR_UNINIT_DATA_PLANE_ON_REMOVAL attribute for all platforms based on capability
- Remove Mellanox specific checks
- Check whether the attribute is supported
- Call SAI API if it is supported, else ignore
Cherry-picking https://github.com/Azure/sonic-sairedis/pull/975
=> Enable SAI_SWITCH_ATTR_UNINIT_DATA_PLANE_ON_REMOVAL attribute

vslib/SwitchStateBase.cpp, vslib/SwitchStateBase.h
This is part of HLD: Azure/SONiC#924,  Azure/SONiC#925
**What I did**
Add port capability query for AutoNeg and Link-Training
Fix the VS test failure for the port AutoNeg and Link-Training capability queries
Ran the sonic-swss/tests/test_port_an.py to verify
=> vslib: add support for read-only port capabilities

.azure-pipelines/build-docker-sonic-vs-template.yml, .azure-pipelines/build-swss-template.yml, .azure-pipelines/build-template.yml, .azure-pipelines/test-docker-sonic-vs-template.yml, azure-pipelines.yml
1. Setup pipeline without manual effort when checkout new release branch.
2. Use correct branch when downloading artifacts or checkout relative repos.
3. Clear downloaded artifacts to avoid using outdated dependencies.
4. Use commonlib pipeline to download libnl3 and libyang instead of vs image build, to increase success rate.
5. Add weekly build to keep artifacts remaining.
=> [ci] Paralize azure pipeline

syncd/FlexCounter.cpp, syncd/FlexCounter.h, unittest/syncd/MockableSaiInterface.cpp, unittest/syncd/TestFlexCounter.cpp
Fix https://github.com/Azure/sonic-buildimage/issues/10850.
A fact is there might be different port types on asic, then different port stats capabilities. Instead of using a cached supported port counter ID list for all ports, it gets supported port counter list per port.
=> [counter] Fix port flex counter 

configure.ac
Fix #1062 
Test log:
dpkg --list | grep libsaibcm
ii  libsaibcm                              7.1.0.0-1                               amd64        Switch Abstraction Interface sdk based on Broadcom SAI
ii  libsaibcm-dev                          7.1.0.0-1                               amd64        development files for Switch Abstraction Interface sdk
checking for main in -lsai... yes
configure: libsai found
checking for swig3.0... /usr/bin/swig3.0
checking whether CXX supports -Wcast-align=strict... yes
checking whether CXX supports -Wno-cast-function-type... yes
checking for sai_query_api_version... no
=> No sai api version check if vendor sai does not support

unittest/vslib/TestMACsecManager.cpp, vslib/MACsecManager.cpp, vslib/MACsecManager.h, vslib/SwitchStateBase.cpp
The previous regex can only match one device so that the original MACsec devices cannot been cleanup by config reload.
=> [vslib]: Fixbug in cleanup MACsec device

.azure-pipelines/build-template.yml, debian/control, debian/python-pysairedis.install, debian/python3-pysairedis.install, debian/rules
On bullseye, the following build command does not fail when configure
step is failing:
```
stepanb@3012cc6b379a:/sonic/src/sonic-sairedis$ fakeroot debian/rules binary-syncd
...
configure: exit 1
dh_auto_configure: error: ./configure --build=x86_64-linux-gnu --prefix=/usr --includedir=\${prefix}/include --mandir=\${prefix}/share/man --infodir=\${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules --libdir=\${prefix}/lib/x86_64-linux-gnu --libexecdir=\${prefix}/lib/x86_64-linux-gnu --disable-maintainer-mode --disable-dependency-tracking returned exit code 1
make[2]: *** [debian/rules:76: override_dh_auto_configure] Error 25
make[2]: Leaving directory '/sonic/src/sonic-sairedis'
+ dh binary -N syncd-rpc -N syncd-rpc-dbg -N syncd-vs -N …
```
=> [debian/rules] fail on script error during package build

syncd/ComparisonLogic.cpp
This is required if some of the attributes on ACL action data
object are OID's and we need to catch their refrence when
removing object and it's dependency tree.
=> [syncd] Support ACL action data object in remove dep tree

.azure-pipelines/build-template.yml
In azp run, the following failure always happens at the stage of `make check` of building syncd. 
```
Making check in syncd
make[2]: Entering directory '/__w/1/s/syncd'
make check-TESTS
make[3]: Entering directory '/__w/1/s/syncd'
tests: tests.cpp:843: void test_watchdog_timer_clock_rollback(): Assertion `settimeofday(&currentTime, NULL) == 0' failed.
/bin/bash: line 5: 13004 Aborted (core dumped) ${dir}$tst
FAIL: tests
```
The execution of `settimeofday(&currentTime, NULL)` fails in slave docker with errno **EPERM**, because CAP_SYS_TIME capability is dropped in docker. Using option `--privileged` gives docker extended privileges for its success.
This failure has existed for a long time in azp build and is not exposed till https://github.com/Azure/sonic-sairedis/pull/1050.
=> [pipeline] Add option --privileged for running slave docker

.gitmodules
This PR is to fix the branch name of submodule SAI.
The `202012` branch is depending on `v1.7` of OCP SAI. To avoid confusion, this PR corrects the branch name in `.gitmodules` of SAI, although the submodule version is specified to a particular, and the branch name in `.gitmodules` does nothing when checking out submodules.
Signed-off-by: bingwang <bingwang@microsoft.com>
=> Fix submodule SAI branch name

configure.ac
The command to build a check program was:
```
gcc -lsai -I./SAI/inc -I./SAI/experimental -I./SAI/meta conftest.cpp -o conftest
```
This, however, does not work on gcc 10.2 where the linker wants first
the executable and then the shared library:
```
gcc -I./SAI/inc -I./SAI/experimental -I./SAI/meta conftest.cpp -lsai -o conftest
```
However CXX_FLAGS comes first before the source file, so added
--no-as-needed as a fix for this issue to make it link against libsai in
any order passed to the linker.
Signed-off-by: Stepan Blyschak <stepanb@nvidia.com>
=> [configure.ac] SAI version check fix for gcc 10.2 (bullseye)

.azure-pipelines/docker-sonic-vs/Dockerfile
What I did
Fix: missing sonic-db-cli in docker-sonic-vs image
Why I did it
How I verified it
Details if related
=> Fix: missing sonic-db-cli in docker-sonic-vs image

lib/Recorder.cpp, unittest/lib/Makefile.am, unittest/lib/TestRecorder.cpp
Previously log rotate was performed after request and on first log line
that was recorded which caused delay and issues with syslog logrotate
when sending HUP signal, actual log rotate was not performed and handle
to a sairedis.rec was sill open preventing logrotate from happening.
Because of this change, perform log rotate CAN'T be done in signal handler, it needs to be postponed to main thread.
=> [sairedis] Perform log rotate on request

syncd/VirtualOidTranslator.cpp, unittest/syncd/Makefile.am, unittest/syncd/MockHelper.cpp, unittest/syncd/TestFlexCounter.cpp, unittest/syncd/TestVirtualOidTranslator.cpp
=> [syncd] Remove error message when tryTranslateVidToRid fails

syncd/scripts/syncd_init_common.sh
`SAI_OBJECT_TYPE_TUNNEL` has fewer attributes in 201811 than in 202012. These new attributes are CREATE only, and can't be added using just SET oper. Hence old object needs to be removed, and new object needs to be added.
Adding `SAI_OBJECT_TYPE_TUNNEL` to break before make to avoid creating a new object before removing existing ones.
Moreover existing sequence (make before break) causes SAI errors in removing VXLAN tunnel (as part of CPA teardown).
In 201811:
```
SAI_OBJECT_TYPE_TUNNEL oid:0x2a000000001781 
SAI_TUNNEL_ATTR_DECAP_MAPPERS      : 1:oid:0x29000000001780
SAI_TUNNEL_ATTR_TYPE               : SAI_TUNNEL_TYPE_VXLAN
SAI_TUNNEL_ATTR_UNDERLAY_INTERFACE : oid:0x600000000144e
```
In 202012:
```
SAI_OBJECT_TYPE_TUNNEL oid:0x2a000000001773 
SAI_TUNNEL_ATTR_DECAP_MAPPERS      : …
```
=> Add SAI_OBJECT_TYPE_TUNNEL object to break-before-make list

syncd/scripts/syncd_init_common.sh
Currently, we do not have an option to select a default profile for each chip. One default profile per package only.
We cannot select a chip suitable profile on SDK package installation because we must detect the chip type first.
However, we have a logic in SONiC which selects suitable profile on system boot, if not selected by the user:
https://github.com/Azure/sonic-buildimage/blob/master/device/barefoot/x86_64-accton_as9516_32d-r0/syncd.conf
This is SONiC generic way to do some platform specific hooks on syncd start:
https://github.com/Azure/sonic-sairedis/blob/bc7ccc2d5c2ddad53ebd696f81ff3d45aacbf438/syncd/scripts/syncd_init_common.sh#L328
Probably it's better to move this logic here https://github.com/Azure/sonic-sairedis/blob/26094f8a614db7ac97b91516a6946402c8a81370/syncd/scripts/syn …
=> [BFN] Provide unified approach to select P4 profile based on chip family

syncd/Asan.cpp
This is to suppress ASAN false positives for static variables.
For example, the ServiceMethodTable::m_slots is sometimes reported as leaked.
ASAN report example:
```c
Direct leak of 32 byte(s) in 1 object(s) allocated from:
#0 0x7feb0d3f4647 in operator new(unsigned long) ../../../../src/libsanitizer/asan/asan_new_delete.cpp:99
#1 0x55b3be15e430 in declare_static<syncd::ServiceMethodTable::SlotBase, syncd::ServiceMethodTable::Slot, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9> syncd/ServiceMethodTable.cpp:74
#2 0x55b3be15e430 in declare_static<syncd::ServiceMethodTable::SlotBase, syncd::ServiceMethodTable::Slot, 10> syncd/ServiceMethodTable.cpp:81
#3 0x55b3be15e430 in __static_initialization_and_destruction_0 syncd/ServiceMethodTable.cpp:85
#4 0x55b3be15e430 in _GLOBAL__sub_I_ServiceMethodTable.cpp …
```
=> [asan] suppress the static variable leaks

.azure-pipelines/docker-sonic-vs/Dockerfile
Cherry pick PR https://github.com/sonic-net/sonic-sairedis/pull/1072 to 202205 branch
What I did
Fix: missing sonic-db-cli in docker-sonic-vs image
Why I did it
How I verified it
Details if related
=> Cherry pick 'Fix: missing sonic-db-cli in docker-sonic-vs image' to 202205 branch

syncd/scripts/syncd_init_common.sh
Signed-off-by: Roman Zhurakivsky <rzhurak@larch-networks.com>
**What I did**
Added xsight platform specific options for syncd common
**How I did it**
Modify syncd_init_common.sh script. added a function to support xsight based platforms. 
**How to verify it**
Verify on Accton platform (based on Xsight ASIC)
=> Add Xsight specific syncd start options

unittest/vslib/TestSwitchBCM81724.cpp, vslib/SwitchBCM81724.cpp, vslib/SwitchStateBase.cpp, vslib/SwitchStateBase.h, vslib/SwitchStateBaseHostif.cpp
Add `SAI_PORT_ATTR_OPER_SPEED ` get in vslib. 
If the `SAI_PORT_ATTR_OPER_STATUS` is DOWN, `SAI_PORT_ATTR_OPER_SPEED`  should be 0, otherwise its value comes from `/sys/class/net/eth{X}/speed`
=> [vslib]: Add SAI_PORT_ATTR_OPER_SPEED get

lib/ZeroMQChannel.cpp, tests/tests.cpp
Fixed https://github.com/sonic-net/sonic-sairedis/issues/1106
=> Add retry on zmq functions if fail with EINTR.

configure.ac, syncd/VendorSai.cpp, unittest/syncd/Makefile.am, unittest/syncd/TestVendorSai.cpp
Why I did this?
bulk counter feature uses two new SAI API sai_bulk_object_get_stats/sai_bulk_object_clear_stats. Some vendors have no such API implemented in their SAI code. Need a way to make compilation pass.
How I fix this?
1. Add AC_CHECK_FUNCS for sai_bulk_object_get_stats/sai_bulk_object_clear_stats which generates macro HAVE_SAI_BULK_OBJECT_CLEAR_STATS/HAVE_SAI_BULK_OBJECT_GET_STATS in config.h.
2. Use ifdef to avoid compilation failure.
=> Fix issue: bulk counter feature cannot compile on platforms having no sai_bulk_object_get_stats/sai_bulk_object_clear_stats

unittest/vslib/Makefile.am, unittest/vslib/TestSwitchStateBase.cpp, vslib/SwitchStateBase.cpp
Create fabric ports for switch_type fabric. This is needed to create vs test for fabric on supervisor.
=> Create fabric ports for switch_type fabric.

.azure-pipelines/build-swss-template.yml, .azure-pipelines/build-template.yml, .azure-pipelines/test-docker-sonic-vs-template.yml, azure-pipelines.yml
sonic-swss-common lib will add depency to libyang soon, so need install libyang lib to prevent build and UT break.
Modify azure pipeline to install libyang in azure pipeline steps.
Pass all UT.
Modify azure pipeline to install libyang in azure pipeline steps.
=> Install libyang in azure pipeline.

syncd/FlexCounter.cpp, syncd/FlexCounter.h
Backport of https://github.com/sonic-net/sonic-sairedis/pull/886
Added Flex counter support for tunnel counters and rates implementation
=> [202012][VxLAN] VxLAN Tunnel Counters and Rates implementation

syncd/Syncd.cpp, syncd/scripts/syncd_init_common.sh
This PR is similar to https://github.com/sonic-net/sonic-sairedis/pull/1100 - it is being raised as a different PR following discussion with Ying Xie.
This PR should be merged together with sonic-utilities PR (https://github.com/sonic-net/sonic-utilities/pull/2365) and sonic-buildimage PR (https://github.com/sonic-net/sonic-buildimage/pull/12026).
Fast-reboot is utilizing warm-reboot infrastructure to improve its performance, but it should ignore warm-boot logic when syncd starts in fast-boot.
As well it shouldn't use temporary view between init and apply.
=> [202205]Use warm-boot infrastructure for fast-boot

unittest/vslib/TestSwitchBCM81724.cpp, vslib/SwitchBCM81724.cpp, vslib/SwitchStateBase.cpp, vslib/SwitchStateBase.h, vslib/SwitchStateBaseHostif.cpp
Add `SAI_PORT_ATTR_OPER_SPEED ` get in vslib. 
If the `SAI_PORT_ATTR_OPER_STATUS` is DOWN, `SAI_PORT_ATTR_OPER_SPEED`  should be 0, otherwise its value comes from `/sys/class/net/eth{X}/speed`
Fixing the PR(https://github.com/sonic-net/sonic-sairedis/pull/1107) conflict with 202205
=> [202205][vslib]: Add SAI_PORT_ATTR_OPER_SPEED get

syncd/Syncd.cpp, syncd/scripts/syncd_init_common.sh
This PR should be merged together with sonic-utilities PR (https://github.com/sonic-net/sonic-utilities/pull/2286) and sonic-buildimage PR (https://github.com/sonic-net/sonic-buildimage/pull/11594).
Fast-reboot is utilizing warm-reboot infrastructure to improve its performance, but it should ignore warm-boot logic when syncd starts in fast-boot.
As well it shouldn't use temporary view between init and apply.
=> [fastboot] fastboot enhancement: Use warm-boot infrastructure for fast-boot

lgtm.yml
sonic-swss-common lib will add depency to libyang soon, so need install libyang lib to prevent lgtm break.
Modify azure pipeline to install libyang in lgtm steps.
Pass lgtm validation.
Modify lgtm.yml to install libyang in lgtm.
=> [lgtm] Fix libyang missing in lgtm validation issue

vslib/SwitchBCM81724.cpp
This change is to support SAI_PORT_ATTR_PORT_SERDES_ID on the SAI for vs gearbox
=> Support SAI_PORT_ATTR_PORT_SERDES_ID on vs gearbox

lgtm.yml
LGTM on 202012 PRs are failing due to a dependency issue with libyang and swsscommon. Use the 202012 branch of swsscommon to avoid this.
Signed-off-by: Lawrence Lee <lawlee@microsoft.com>
=> [lgtm]: Use 202012 branch of swsscommon

lib/src/Recorder.cpp
While the Recorder is writing to the sairedis log file, it's possible for a log rotate to occur at exactly the right time so that file stream used for writing (a `std::ofstream`) is re-opened in the middle of the write operation (since writing and log rotate are handled by separate threads). Since standard library objects are not thread safe, this can cause some pointers used during the write operation to be overwritten, leading to a segmentation fault when the write operation proceeds.
To prevent this from occurring, acquire a lock for the file stream for any methods that change the ofstream (including opening, closing, and writing to it with the `<<` operator).
Signed-off-by: Lawrence Lee <lawlee@microsoft.com>
=> [202012][Recorder]: Acquire lock for ofstream changes

syncd/FlexCounter.cpp
* Fixing issue #11621
* The cleanup code for stale rif counters are now moved to syncd . Earlier as part of fix for issue #2193 the cleanup for stale rif counters was added.
* But it could create a race condition between orchagent removes RIF rate counters from DB and lua script fetching them.
* So as a fix all such cleanup has been moved to syncd.
Signed-off-by: Suman Kumar <suman.kumar@broadcom.com>
All the details are mentioned in : 
https://github.com/sonic-net/sonic-swss/pull/2488
=> sairedis: Fixing race condition for rif counters

lib/Recorder.cpp
While the Recorder is writing to the sairedis log file, it's possible for a log rotate to occur at exactly the right time so that file stream used for writing (a std::ofstream) is re-opened in the middle of the write operation (since writing and log rotate are handled by separate threads). Since standard library objects are not thread safe, this can cause some pointers used during the write operation to be overwritten, leading to a segmentation fault when the write operation proceeds.
To prevent this from occurring, acquire a lock for the file stream for any methods that change the ofstream (including opening, closing, and writing to it with the << operator). Also use `recordLine` for all writes to the file stream to avoid deadlock.
Signed-off-by: Lawrence Lee …
=> [Recorder]: Acquire lock for ofstream changes

meta/Meta.cpp, unittest/lib/Makefile.am, unittest/lib/test_sai_redis_generic_programmable.cpp, unittest/meta/TestMeta.cpp, unittest/vslib/Makefile.am, unittest/vslib/test_sai_vs_generic_programmable.cpp
With a support added for attr value type json, there is a validation support for this attr value type missing. This PR is to enable validation checks for the same.
Signed-off-by: svshah-intel shitanshu.shah@intel.com
=> validation support for SAI_ATTR_VALUE_TYPE_JSON

syncd/scripts/syncd_init_common.sh
enable cisco8000 SAI bulk API feature
**What is the motivation for this PR?**
running ipfwd/test_nhop_count.py with cisco8000 will have an log analyzer's error message from monit as below if testcase configs a very huge amount NHG with more NHG members.
E               Aug 10 11:05:43.720848 str2-8102-02 ERR monit[513]: 'routeCheck' status failed (255) – Failure results: {{#012    "Unaccounted_ROUTE_ENTRY_TABLE_entries": [#012        "192.168.87.132/31",#012        "192.168.87.134/31",#012        "192.168.87.136/31",#012        "192.168.87.138/31",#012        "192.168.87.150/31",#012        "192.168.87.154/31",#012        "192.168.87.156/31",#012        "192.168.87.158/31",#012        "192.168.87.160/31",#012        "192.168.87.164/31",#012        "192.168.87.166/31",#012 …
=> enable cisco8000 SAI bulk API feature

syncd/scripts/syncd_init_common.sh
enable cisco8000 SAI bulk API feature
**What is the motivation for this PR?**
running ipfwd/test_nhop_count.py with cisco8000 will have an log analyzer's error message from monit as below if testcase configs a very huge amount NHG with more NHG members.
E Aug 10 11:05:43.720848 str2-8102-02 ERR monit[513]: 'routeCheck' status failed (255) – Failure results: "Unaccounted_ROUTE_ENTRY_TABLE_entries
192.168.87.132/31", "192.168.87.134/31", "192.168.87.136/31", ...
ROOT-CAUSE: ASIC_DB and AAPL_DB are not in-sync on route info on time
loganalyzer got "ERR monit" because route-check.py(sonic-utility)
compares with both DB are un-matched on routing within a certain period of time.
cisco@mth64-m5-2:~$
sonic-db-cli ASIC_DB keys * | grep -n 192.183.96.128
ASIC_STATE:SAI_OBJECT_TYPE_ROUTE_ENTRY: …
=> enable cisco8000 SAI bulk API feature on 202012

unittest/meta/TestLegacyFdbEntry.cpp, unittest/meta/TestLegacyOther.cpp
When running unit tests for sairedis, there may be random test failures for Legacy.switch_get and LegacyFdbEntry.fdb_entry_get. This is happening because when doing the get call for
`SAI_SWITCH_ATTR_DEFAULT_VIRTUAL_ROUTER_ID`, the value isn't initialized in this unit test function, with the assumption that it would contain the actual value assuming the get call was successful. There's two problems that happen:
1. Since a dummy SAI interface is being used for these tests, the get call always succeeds (assuming that the attr list and count arguments are valid), but the value for each attr is not modified at all.
2. Since this call returns a success, in `meta_generic_validation_post_get_objlist`, it will see the value for the attr (which is uninitialized memory) and complain that this value …
=> Initialize attr variables in Legacy.switch_get and LegacyFdbEntry.fdb_entry_get

.azure-pipelines/build-docker-sonic-vs-template.yml, .azure-pipelines/build-template.yml, .azure-pipelines/docker-sonic-vs/Dockerfile, .azure-pipelines/test-docker-sonic-vs-template.yml, azure-pipelines.yml
This adds ASAN to CI DVS test run via 3 new stages:
* BuildAsan: build with --enable-asan
* BuildDockerAsan: builds docker-sonic-vs-asan with asan-enabled syncd and syncd-dbg
* TestAsan: runs the tests via docker-sonic-vs-asan and checks/publishes the reports
Current stages are not affected. Also, if an ASAN test run or a report check fails, it doesn't block a PR.
=> [ci][asan] add DVS tests run with ASAN

syncd/RedisClient.cpp, syncd/SaiSwitch.cpp
This issue is related to the dynamic port breakout mode support on multi-ASIC platforms. When the port breakout mode changes, SWSS removes ports from LANES mapping and adds new ports to LANES mapping. This logic works properly on the single-chip platform (NPU switch type) but it does not work properly on the multi-ASIC platform (VOQ switch type) because LANES mapping is not created on the multi-ASIC platform.
To fix this issue, my proposal is to create LANES mapping on the multi-ASIC platform.  Though the fix is straightforward, the comment in the existing codebase is a bit concerning to me. I am not sure if creating LANES mapping on the multi-ASIC platform could affect backward compatibility. @arlakshm
=> Manage LANES mapping on VOQ system

.azure-pipelines/build-template.yml
The custom branch we were using previously has since been deleted. That branch appears to have some fix for searching for the source file (for a gcda file) recursively. I don'y know if it's needed or not today, but using the stock gcovr 5.2 (from the official repo) appears to work.
Signed-off-by: Saikrishna Arcot <sarcot@microsoft.com>
=> Switch to using stock gcovr 5.2

unittest/vslib/TestSwitchStateBase.cpp, vslib/SwitchStateBase.cpp
This PR is to cherry-pick #1114 into `202205` branch after resolving conflicts.
The error of `test_fabric.py` can be fixed with this change
```
sudo pytest test_fabric.py -v --pdb --imgname=docker-sonic-vs:build --keeptb
========================================================================================= test session starts =========================================================================================
platform linux -- Python 3.7.5, pytest-7.1.1, pluggy-1.0.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /home/bingwang/work/sonic/sonic-buildimage-202205/src/sonic-swss/tests
plugins: flaky-3.7.0
collected 2 items …
```
=> [202205] Create fabric ports for switch_type fabric

syncd/Asan.cpp
cherry-pick from https://github.com/sonic-net/sonic-sairedis/pull/1085
This is to suppress ASAN false positives for static variables. For example, the ServiceMethodTable::m_slots is sometimes reported as leaked.
* [asan] suppress the static variable leaks
* [asan] add missing SWSS_LOG_ENTER()
=> [202205][Cherry-pick][asan] suppress the static variable leaks

syncd/scripts/syncd_init_common.sh, unittest/vslib/Makefile.am, unittest/vslib/TestSwitchMLNX2700.cpp, unittest/vslib/TestVirtualSwitchSaiInterface.cpp, unittest/vslib/test_sai_vs_port.cpp, vslib/SwitchStateBase.cpp, vslib/VirtualSwitchSaiInterface.cpp
**HLD:** https://github.com/sonic-net/SONiC/pull/1084
* fix vslib to handle bulk requests properly
* enable bulk API for both VS and NVIDIA
=> [ppi]: Enable bulk API

syncd/scripts/syncd_init_common.sh
enable cisco8000 SAI bulk API feature
**What is the motivation for this PR?**
running ipfwd/test_nhop_count.py with cisco8000 will have an log analyzer's error message from monit as below if testcase configs a very huge amount NHG with more NHG members.
E Aug 10 11:05:43.720848 str2-8102-02 ERR monit[513]: 'routeCheck' status failed (255) – Failure results: "Unaccounted_ROUTE_ENTRY_TABLE_entries
192.168.87.132/31", "192.168.87.134/31", "192.168.87.136/31", ...
.......
ROOT-CAUSE: ASIC_DB and AAPL_DB are not in-sync on route info on time
loganalyzer got "ERR monit" because route-check.py(sonic-utility)
compares with both DB are un-matched on routing within a certain period of time.
cisco@mth64-m5-2:~$
sonic-db-cli ASIC_DB keys * | grep -n 192.183.96.128 …
=> enable cisco8000 SAI bulk API feature on 202205

configure.ac, syncd/VendorSai.cpp
AC_CHECK_FUNCS did not create macros HAVE_SAI_BULK_OBJECT_GET_STATS HAVE_SAI_BULK_OBJECT_CLEAR_STATS as expected. When those macros are not created, feature is disabled.
Define needed CXXFLAGS for AC_CHECK_FUNCS, now macros are being created.
Run sonic-mgmt test test_cpu_memory_usage_desired_process
=> [Bulk counters] Enable bulk counter feature for SAI vendors supporting the feature

syncd/scripts/syncd_init_common.sh
Update syncd_init_common to check if fast-reboot is enabled according to the new value for FAST_REBOOT entry in STATE_DB.
This PR should come along with the following PRs:
https://github.com/sonic-net/sonic-utilities/pull/2621
https://github.com/sonic-net/sonic-buildimage/pull/13484
https://github.com/sonic-net/sonic-swss-common/pull/742
https://github.com/sonic-net/sonic-platform-daemons/pull/335
This set of PRs solves the issue https://github.com/sonic-net/sonic-buildimage/issues/13251
=> Use new value of STATE_DB FAST_REBOOT entry

syncd/scripts/syncd_init_common.sh
Signed-off-by: Andriy Yurkiv <ayurkiv@nvidia.com>
Update sai.profile with SAI_ADDITIONAL_MAC_ENABLED=1 if "dual_tor" attr is passed to syncd
=> [Dual-ToR] update sai.profile with SAI_ADDITIONAL_MAC_ENABLED attribute if corresponding arg passed to syncd

syncd/scripts/syncd_init_common.sh
Dedicated PR for 202205 branch similar to https://github.com/sonic-net/sonic-sairedis/pull/1213 as part of fast-reboot finalizer implementation.
Update syncd_init_common to check if fast-reboot is enabled according to the new value for FAST_REBOOT entry in STATE_DB.
This PR should come along with the following PRs:
https://github.com/sonic-net/sonic-utilities/pull/2724
https://github.com/sonic-net/sonic-platform-daemons/pull/343
https://github.com/sonic-net/sonic-buildimage/pull/14143
This set of PRs solves the issue https://github.com/sonic-net/sonic-buildimage/issues/13251
=> [202205] Use new value of STATE_DB FAST_REBOOT entry

.azure-pipelines/build-docker-sonic-vs-template.yml, .azure-pipelines/build-swss-template.yml, .azure-pipelines/build-template.yml, .azure-pipelines/build_and_install_module.sh, .azure-pipelines/docker-sonic-vs/Dockerfile, .azure-pipelines/test-docker-sonic-vs-template.yml
Cherry pick tow commits in master branch:
```
2bbe97f [ci] Continue on error when running test.
749b393 [ci] Fix apt-get install unable locate package issue. (#1212)
```
=> [ci] Fix apt-get install unable locate package issue. (#1212)

.azure-pipelines/build-swss-template.yml, .azure-pipelines/build-template.yml, .azure-pipelines/docker-sonic-vs/Dockerfile, azure-pipelines.yml
With the merge of sonic-net/sonic-buildimage#13294, docker-sonic-vs is now based on Bullseye. Switch to building for Bullseye to match that change.
=> Update build pipeline to build for Bullseye

.azure-pipelines/build-template.yml, meta/Meta.cpp, unittest/meta/Makefile.am, unittest/meta/TestMeta.cpp
- Change SAI Meta validation functions to return `SAI_STATUS_ITEM_NOT_FOUND` if the key being operated on doesn't exist
=> Use SAI_STATUS_ITEM_NOT_FOUND when key not found

.azure-pipelines/build-template.yml, debian/syncd.dirs, debian/syncd.install, debian/syncd.links, meta/DummySaiInterface.cpp, meta/DummySaiInterface.h, syncd/Makefile.am, syncd/MdioIpcClient.cpp, syncd/MdioIpcClient.h, syncd/MdioIpcCommon.h, syncd/MdioIpcServer.cpp, syncd/MdioIpcServer.h, tests/aspell.en.pws, unittest/syncd/Makefile.am, unittest/syncd/MockableSaiInterface.cpp, unittest/syncd/MockableSaiInterface.h, unittest/syncd/TestMdioIpcServer.cpp
Signed-off-by: Jiahua Wang <jiahua.wang@broadcom.com>
Why I did it
The syncd has a MDIO IPC server to help the access of external PHYs on the NPU MDIO bus. A MDIO IPC client library is required to communicate to the MDIO IPC server. The gbsyncd will pass the function pointers for the function in the client library to the PAI.
How I did it
MDIO IPC client functions are added to connect to the MDIO IPC server socket, to send request and to wait for response IPC messages. The client functions are made into a .so library. The .so library is packaged in the syncd debian package.
How to verify it
The client functions are also available in as a .a library. The unit test code can use the code to test both IPC server and client.
=> Add mdio IPC client library

lib/ClientSai.cpp, lib/Recorder.cpp, lib/RedisRemoteSaiInterface.cpp, lib/sai_redis.h, meta/DummySaiInterface.cpp, meta/Meta.cpp, meta/Meta.h, unittest/lib/TestClientServerSai.cpp, vslib/VirtualSwitchSaiInterface.cpp, vslib/sai_vs.h
Replace manually written handlers for bulk API with macro-generated handlers.
The macro-generated handlers significantly reduce the number of lines of manually written code, prevent code duplication, and simplify adding new API support. The approach is the same a for regular quad API.
This is needed to prepare infrastructure for DASH API implementation.
=> Add macros for bulk API handlers generation.

configure.ac
since commit 8e1fb37 (v1.8.0) there is check enum binary backward compatibility so we are relaxing this check below, versions do not have to be equal but both need to be at least 2ebde24 (v1.9.0), this will make sure that enums are always ok, but since that commit some data structures changed and are not binary backwad compatible like next hop group api, acl_capability, structs are backward binary compatible from commit aed34c8, which closest tag version for it is commit 3ff228a (v1.12.0), so min version check should be set to (v1.12.0), but some production branches do not use that high SAI version yet, some use even version v1.7.0 which then it is impossible to provide even enum backward compatibility, check those links:
https://github.com/opencomputeproject/SAI/pull/1297 (enums) …
=> [configure] Check for minimal SAI version

syncd/VendorSai.cpp
After advancing SAI version to 1.12 and still using SAI v1.11 in the SDK, switch cannot start up due to following reason:
```
May 26 09:27:12.708367 str2-7050cx3-acs-02 WARNING syncd#syncd: :- Syncd: enable sync mode is deprecated, please use communication mode, FORCING redis sync mode
May 26 09:27:12.709654 str2-7050cx3-acs-02 NOTICE syncd#syncd: :- RedisSelectableChannel: opened redis channel
May 26 09:27:12.711334 str2-7050cx3-acs-02 NOTICE syncd#syncd: :- isVeryFirstRun: First Run: True
May 26 09:27:12.711334 str2-7050cx3-acs-02 NOTICE syncd#syncd: :- initialize: SAI API version: 11100
May 26 09:27:12.711370 str2-7050cx3-acs-02 ERR syncd#syncd: :- initialize: SAI implementation API version 11100 does not match SAI headers API version 11200
May 26 09:27:12.711370 str2-7050cx3-acs-02 …
```
=> Remove return failure when SAI version mismatch

syncd/VendorSai.cpp
since commit 8e1fb37 (v1.8.0) there is check enum binary backward compatibility so we are relaxing this check below, versions do not have to be equal but both need to be at least 2ebde24 (v1.9.0), this will make sure that enums are always ok, but since that commit some data structures changed and are not binary backwad compatible like next hop group api, acl_capability, structs are backward binary compatible from commit aed34c8, which closest tag version for it is commit 3ff228a (v1.12.0), so min version check should be set to (v1.12.0), but some production branches do not use that high SAI version yet, some use even version v1.7.0 which then it is impossible to provide even enum backward compatibility
=> [syncd] Check for minimal SAI version

pyext/pysairedis.i
Fix https://github.com/sonic-net/sonic-buildimage/issues/13775
-fvar-tracking-assignments
Annotate assignments to user variables early in the compilation and attempt to carry the annotations over throughout the compilation all the way to the end, in an attempt to improve debug information while optimizing. 
By default, this flag is enabled.
There is no reason to use this flag for auto-generated code.
=> disable GCC VTA for SWIG-generated file to reduce build time

syncd/Syncd.cpp
**MICROSOFT ADO#: 24107886**
"SaiGetHardwareInfo" is now returning string "none" instead of empty string (""), which is causing INIT_VIEW failure:
```
May 26 18:57:33.577868 NOTICE syncd#syncd: :- onSwitchCreateInInitViewMode: new switch oid:0x21000000000000 contains hardware info: ''
May 26 18:57:33.577868 ERR syncd#syncd: :- onSwitchCreateInInitViewMode: hardware info mismatch: current 'none' vs new ''
May 26 18:57:33.578017 ERR syncd#syncd: :- run: Runtime error: :- onSwitchCreateInInitViewMode: hardware info mismatch: current 'none' vs new ''
```
Adding this change as a temp workaround before CSP is resolved with BRCM. 
Test syncd build on lab device, able to pass INIT_VIEW stage. 
sign-off: Jing Zhang zhangjing@microsoft.com
=> [warmboot] Add workaround for `INIT_VIEW` failure 

.azure-pipelines/build-template.yml, meta/Meta.cpp, unittest/meta/TestMeta.cpp
* Use SAI_STATUS_ITEM_NOT_FOUND when key not found
* Add unit tests for Meta SAI validation
* generate coverage info for Meta.cpp
=> [202205]Use SAI_STATUS_ITEM_NOT_FOUND when key not found (#1224)

.github/workflows/codeql-analysis.yml
Increase robustness of CodeQL: use only dependencies with the relevant versions
**NOTE:** solution relies on the fact that each repository suppose to have a dependency with the relevant branch
=> [CodeQL]: Use dependencies with relevant versions in azp template

.github/workflows/codeql-analysis.yml
Signed-off-by: Nazarii Hnydyn [nazariig@nvidia.com](mailto:nazariig@nvidia.com)
Increase robustness of CodeQL: use only dependencies with the relevant versions
**NOTE:** solution relies on the fact that each repository suppose to have a dependency with the relevant branch
=> [202211][CodeQL]: Use dependencies with relevant versions in azp template

debian/rules
PR #1194 removed the .ONESHELL flag, causing commands for a target to be executed in separate shell environments. Because of that, multi-line shell code blocks aren't parsed correctly.
Since the `syncd_init_common.sh` file should always exist anyways (it's unconditionally sourced by an init script and a start script), remove the if-check around it, and always run `sed` when building rpc packages.
=> Fix RPC package build failure due to shell syntax issue

debian/control, debian/rules
When the RPC version needs to be built, the regular version of syncd also needs to be built. Unfortunately, this is not easy to do with the current build infra except for manually rerunning configure, removing the built object files/binaries, and building the new config.
=> Build both the regular and RPC version when the RPC profile is enabled

configure.ac, lib/sai_redis_interfacequery.cpp, syncd/VendorSai.cpp, syncd/VendorSai.h, syncd/tests.cpp, unittest/lib/test_sai_redis_interfacequery.cpp
Also update VendorSai class to use latest generic api from SAI metadata.
Since latest SAI uses version v1.12 on master branch, force require sai_query_api_version to be present at all SAI libs
=> [submodule] Update SAI to latest v1.12 branch

.azure-pipelines/build-swss-template.yml, .azure-pipelines/test-docker-sonic-vs-template.yml
Swss containter needs dash_api to properly build, based on https://github.com/sonic-net/sonic-swss/pull/2722, attempting to add missing libs
=> [azp] Fix swss missing libs

vslib/SwitchState.cpp, vslib/SwitchState.h
This is continuation of previous PR.
https://github.com/sonic-net/sonic-sairedis/pull/1274
In this PR addressed review comments. Please review.
=> port counter support on sonic-vs

lib/ClientConfig.cpp, lib/ContextConfigContainer.cpp, lib/ServerConfig.cpp, meta/SaiSerialize.cpp, saiasiccmp/View.h, unittest/meta/TestNotificationFactory.cpp, vslib/ContextConfigContainer.cpp, vslib/FdbInfo.cpp
This header file comes from an external package, and a very old version of the header file has been checked into swss-common. This will cause problems for the upcoming Bookworm upgrade.
Change references to the header file to use the Debian package nlohmann-json-dev (added in https://github.com/sonic-net/sonic-buildimage/pull/16308), instead of from swss-common.
=> Use json.hpp from nlohmann-json-dev instead of swss-common

configure.ac, saidiscovery/Makefile.am, saisdkdump/Makefile.am, syncd/Makefile.am
Since vendor libsai.so may require some extra libs we need to pass this as a param for linker
=> Add extra parameter to pass vendor LDFLAGS for libsai.so

syncd/SaiDiscovery.cpp
When multiple asic are present and multiple ports are created then those log lines willpollute logs for no reason
=> [syncd] Change sai discovery log priority to info

meta/SaiInterface.cpp, meta/SaiInterface.h, syncd/SaiDiscovery.cpp, syncd/SaiDiscovery.h, syncd/VendorSai.cpp, syncd/VendorSai.h
Previously log after sai discovery log level was set to NOTICE not respecting actual API log level or what user set via swsslog
fixes: https://github.com/sonic-net/sonic-sairedis/issues/1300
=> [syncd] Respect each api log level after sai discovery

meta/Meta.cpp
When there is no matching FDB entry found in the database, then an incorrect SAI error code (SAI_STATUS_INVALID_PARAMETER) is returned. As a port of this fix, the correct SAI error return code (SAI_STATUS_ITEM_NOT_FOUND) is returned.
This Return code can be used by the callers to take approprite actions, if the FDB entry is indeed not available during the set/remove operations.
=> The meta_sai_validate_fdb_entry() validates the input FDB entry for the set/remove operation. (#1154)

syncd/ConcurrentQueue.h, tests/aspell.en.pws, unittest/syncd/Makefile.am, unittest/syncd/TestConcurrentQueue.cpp
HLD: https://github.com/sonic-net/SONiC/pull/1071
=> [Link event damping] Add concurrent queue.

lib/Utils.cpp, lib/Utils.h, unittest/lib/TestUtils.cpp
- Adding utility methods to calculate: 1) Remaining value of a substance after time t using half-life formula. 2) Time to reach a target value using half-life formula.
HLD: sonic-net/SONiC#1071
=> [Link event damping] Add utility methods.

syncd/NotificationProcessor.cpp
Fixes https://github.com/sonic-net/sonic-buildimage/issues/16992
We will also translate removed RID in notification in case that BFD session was removed, and notification arrived for that session asynchronously
=> [syncd] Translate removed RID on bfd session state change

lib/sairedis.h, tests/aspell.en.pws
- Add link event damping sairedis port attributes.
- These attributes will be used by OA to set the link event damping algorithm and AIED link event damping config.
- Syncd uses these sairedis port attribute to receive the link event damping algorithm and AIED config to execute syncd-based link event damping.
HLD: sonic-net/SONiC#1071
=> [Link Event Damping] Add link event damping sairedis port attributes.

syncd/Syncd.cpp
Previously we were hard-codding default value for fdb flush, and since this value could change in the future, we want to get this form SAI metadata
=> [syncd] User fdb flush default value from SAI

unittest/vslib/TestSwitchStateBase.cpp, vslib/SwitchStateBase.cpp, vslib/SwitchStateBase.h
Signed-off-by: Nazarii Hnydyn [nazariig@nvidia.com](mailto:nazariig@nvidia.com)
**HLD:** https://github.com/sonic-net/SONiC/pull/1501
=> [hash]: Extend VS lib with ECMP/LAG hash algorithm

syncd/SelectableEventHandler.h
- Handler in the class will be used to handle the timer event of link event dampers.
HLD: sonic-net/SONiC#1071
=> [Link Event Damping] Add Abstract SelectEventHandler class to handle link event damping timer events.

syncd/scripts/syncd_init_common.sh
Feature - CMIS management
- Microsoft ADO **(number only)**:
update syncd init common script to add module control profile content into sai.profile file
manually check sai.profile on a supporting switch (MSFT SKU) and verify module control profile content in it
=> add if statement for module control mode support

syncd/PortStateChangeHandler.cpp
- In PR https://github.com/sonic-net/sonic-sairedis/pull/1310, a constexpt static data member was added. Since sairedis repo uses c++14, definition of this data member needs to be provided in .cpp file too.
=> Fix compilation issue due to PORT_STATE_CHANGE_QUEUE_SIZE undefined reference.

syncd/Syncd.cpp
It's handled inside loop where meta->attrvaluetype == SAI_ATTR_VALUE_TYPE_POINTER
=> [syncd] Remove notify pointers manual handling

lib/sairedis.h, meta/SaiSerialize.cpp, meta/sai_serialize.h, unittest/meta/TestSaiSerialize.cpp
- Adding serialization/deserialization logic for link event damping config so that when libsai is sending link event damping algo and config to syncd for set request, it uses serialization logic to serialize the requested data before sending the set request and when syncd receives the link event damping port attribute set request, it uses the deserialization logic to deserialize the data.
HLD: sonic-net/SONiC#1071
=> [Link Event Damping] Serialization/deserialization logic for link event damping port attrs

.azure-pipelines/build-docker-sonic-vs-template.yml, .azure-pipelines/build-swss-template.yml, .azure-pipelines/docker-sonic-vs/Dockerfile
The Azp pipeline of sonic-dash-api has been moved from buildimage to it's submodule.
=> [Azp]: Update dash api source from buildimage to submodule

lib/Switch.cpp, meta/Makefile.am, meta/Meta.cpp, meta/Meta.h, meta/NotificationFactory.cpp, meta/NotificationTwampSessionEvent.cpp, meta/NotificationTwampSessionEvent.h, meta/SaiSerialize.cpp, meta/sai_serialize.h, syncd/NotificationHandler.cpp, syncd/NotificationHandler.h, syncd/NotificationProcessor.cpp, syncd/NotificationProcessor.h, syncd/SwitchNotifications.cpp, syncd/SwitchNotifications.h, syncd/Syncd.cpp, tests/aspell.en.pws
For supporting TWAMP Light, it requires vendor-sai to report TWAMP Light mearsurement data from silicon.
And, so it defines the notification event and getting statistics function in SAI and invokes them in syncd.
=> Support TWAMP Light notification in syncd

debian/rules
This fixes a breakage from #1194 where code coverage and ASAN were not enabled, due to DEB_CONFIGURE_EXTRA_FLAGS no longer being used in dh_auto_configure.
=> Fix code coverage and ASAN not being enabled

syncd/scripts/syncd_init_common.sh
Reverts sonic-net/sonic-sairedis#1305
this logic is not needed. we'll change sai.profile directly
=> Revert "add if statement for module control mode support"

lib/sai_redis_tam.cpp, syncd/ServiceMethodTable.cpp, syncd/SwitchNotifications.cpp, unittest/lib/test_sai_redis_tam.cpp, unittest/vslib/test_sai_vs_tam.cpp, vslib/sai_vs_tam.cpp
This adds support for sairedis to compile on Debian Bookworm (with GCC 12). This PR also includes a SAI submodule update that brings in other unrelated changes; this is needed because of a change in Doxyfile that would cause warnings/errors in newer versions of Doxygen.
The SAI submodule update brings in the following changes:
* Update the Doxyfile for doxygen in Debian Bookworm (opencomputeproject/SAI#1946)
* Enable sai_uint16_t in ProcessStructValueType Struct Member (opencomputeproject/SAI#1949)
* [meta] Add support for port stat extensions (opencomputeproject/SAI#1947)
* [meta] Add custom range start end values check (opencomputeproject/SAI#1945)
* Cable diagnostics attribute added (opencomputeproject/SAI#1894)
* Add attributes to disable L3 rewrites (opencomputeproject/SAI#1924)
* …
=> Make changes to support compiling on Bookworm (with GCC 12)

syncd/scripts/syncd_init_common.sh
- Create a folder for SDK dumps based on the SDK_DUMP_PATH variable from the SAI profile file.
- Update the number of huge pages required to run SDK. 
- Customise interfaces configuration based on SKU
=> [nvidia] Update syncd start script to cover changes in SDK initialization process. 

vslib/LaneMapFileParser.cpp
Enable 8 lanes support in vslib. This is needed to emulate HW SKUs which contains 8 lanes in their port_config.ini.
Tested bring up of vs image with HWSKU containing 8 lanes in their port_config.ini/lanemap.ini files.
=> Enable 8 Lanes Support in vslib

syncd/scripts/syncd_init_common.sh
Changed config_mlnx_syncd() functionality to use common sai.profile for all SKUs, then apply the specific SKU sai.profile on top of it, and remove duplications.
Why I did it
To have the ability to add common parameters to only 1 file instead of all SKUs.
=> Add new functionality to syncd_init_common.sh, to use common sai.profile

configure.ac
**What I did**
Fix compilation with ASAN enabled for the Debian Bookworm with GCC version 12.2.0 (Debian 12.2.0-14).
The compilation fails due to the issue in GGC compiler: [GCC Bugzilla – Bug 105562](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105562)
The suggested fix is suppressing the `maybe-uninitialized` warning to overcome the problem and may be removed when the GCC version is upgraded to the one that includes the fix.
Compile SWSS package with ASAN enabled.
Related to: https://github.com/sonic-net/sonic-swss/pull/3062
=> [asan] Disable the "maybe-uninitialized" warning when compiled with ASAN enabled.

syncd/MdioIpcServer.cpp
This PR is to address the issue [syncd crash observed during sonic-mgmt reboot tests #17346](https://github.com/sonic-net/sonic-buildimage/issues/17346)
=> Check MDIO server thread joinable before join the thread

unittest/vslib/TestMACsecManager.cpp, vslib/MACsecManager.cpp
Bookworm's iproute2 has built-in support for configuring MACsec with XPN ciphers. Unfortunately, the syntax is slightly different, which means changes are needed for this to work on Bookworm.
Update the iproute2 commands run for Bookworm. This does mean compatibility with Bullseye will break.
=> Update ip commands for MACsec for Bookworm

.azure-pipelines/build-template.yml, azure-pipelines.yml
Add a step to verify the build for Bookworm for amd64, armhf, and arm64.
=> Add Bookworm build to PR checks

lib/sai_redis_dash_eni.cpp, unittest/lib/test_sai_redis_dash_eni.cpp, unittest/vslib/test_sai_vs_dash_eni.cpp, vslib/sai_vs_dash_eni.cpp
SAI submodule update to bring saithrift changes needed for syncd bookworm migration
=> SAI submodule update to bring saithrift changes for syncd bookworm

tests/aspell.en.pws, unittest/vslib/TestSwitchStateBaseMACsec.cpp, vslib/MACsecAttr.h, vslib/MACsecManager.cpp, vslib/SwitchStateBaseMACsec.cpp
While Bookworm's iproute2 has built-in support for the MACsec XPN protocols, the SSCI argument is passed in in a different way compared to the patch that we had. Instead of taking in a number, a hex string is taken in instead.
Update the code in sairedis to pass in a hex string for SSCI instead of a number.
Also simplify the endian conversion for the SCI by using `htobe64`, so that we don't need `#ifdef`'s checking for endianness. It's technically non-standard, but since this will be compiled for Linux, that should be fine.
=> Fix SSCI parameter when creating MACsec tunnels on Bookworm

lib/Switch.cpp, meta/Makefile.am, meta/Meta.cpp, meta/Meta.h, meta/NotificationFactory.cpp, meta/NotificationSwitchAsicSdkHealthEvent.cpp, meta/NotificationSwitchAsicSdkHealthEvent.h, meta/SaiSerialize.cpp, meta/sai_serialize.h, saiplayer/SaiPlayer.cpp, saiplayer/SaiPlayer.h, syncd/NotificationHandler.cpp, syncd/NotificationHandler.h, syncd/NotificationProcessor.cpp, syncd/NotificationProcessor.h, syncd/SwitchNotifications.cpp, syncd/SwitchNotifications.h, syncd/Syncd.cpp, unittest/lib/TestSwitch.cpp, unittest/meta/Makefile.am, unittest/meta/TestNotificationFactory.cpp, unittest/meta/TestNotificationSwitchAsicSdkHealthEvent.cpp, unittest/syncd/TestNotificationHandler.cpp, unittest/syncd/TestNotificationProcessor.cpp, vslib/Switch.cpp
Support ASIC/SDK health event
1. Handle vendor SAI ASIC/SDK health event and encode it
2. Pass it to swss through the communication channel.
=> Support ASIC/SDK health event

syncd/Makefile.am
Make original syncd-vs and syncd-dash co-exist.
=> [syncd]: Generate syncd_dash

tests/Makefile.am, tests/checksaiapi.sh
This test will make sure only SAI global api are used in expected places
=> Add check for global SAI api used

syncd/scripts/syncd_init_common.sh
Update nvidia bluefield syncd initialization for a single-port SKU
=> [nvidia] update config_syncd_nvidia_bluefield()

meta/DummySaiInterface.cpp, meta/DummySaiInterface.h, meta/Makefile.am, proxylib/Makefile.am, proxylib/Options.cpp, proxylib/Options.h, proxylib/Proxy.cpp, proxylib/Proxy.h, proxylib/Sai.cpp, proxylib/Sai.h, proxylib/saiproxy.h, stub.pl, tests/aspell.en.pws, unittest/meta/Makefile.am, unittest/meta/TestDummySaiInterface.cpp, unittest/proxylib/Makefile.am, unittest/proxylib/TestProxy.cpp, unittest/proxylib/TestSai.cpp, unittest/syncd/Makefile.am
This proxy class will be used in DASH application.
This change contains:
* Update DummySaiInterface do support dummy notifications for testing
* DummySaiInterface unittests
* Proxy class support notifications
* Proxy class unittests
* Sai class support notifications
* Sai class unittests
* Added Options class for handy zmq options configuration
* Move DummySaiInterface to saimeta library
* Added TODO which functions should be replaced after SAI submodule update
* Update aspell
=> [proxy] Support notifications

syncd/Syncd.cpp, syncd/tests.cpp
Fixes https://github.com/sonic-net/sonic-buildimage/issues/19411
During fast reboot temp view is not used and any failure will not result in SAI failure dump taken. Hence moving the handling of SAI failure dump above the ignore of non temp view.
=> Moving SAI failure dump handling above the ignore for non temp view

.azure-pipelines/test-docker-sonic-vs-template.yml
https://github.com/sonic-net/sonic-swss/pull/3019 introduced the ability to run VS tests in parallel to decrease execution time. Implement the same change for sairedis.
=> [azp] Run VS tests in parallel

lib/Recorder.h, meta/Meta.cpp, meta/Meta.h, meta/SaiInterface.cpp, meta/SaiInterface.h, meta/SaiSerialize.cpp, meta/sai_serialize.h, pyext/pysairedis.i, syncd/VendorSai.cpp, unittest/meta/TestMeta.cpp, unittest/meta/TestNotificationFactory.cpp, unittest/meta/TestNotificationPortStateChange.cpp, unittest/meta/TestSaiInterface.cpp, unittest/syncd/TestVendorSai.cpp
=> [submodule] Update SAI to latest master

syncd/NotificationQueue.cpp, syncd/NotificationQueue.h, tests/aspell.en.pws, unittest/syncd/TestNotificationQueue.cpp
Since there could be burst of notifications, that allocated memory can be over 2GB, but when queue will be drained that memory will not be automatically released. Underlying deque container contains function shrink_to_fit but that is just a request, and usually this function does nothing.
=> [syncd] Make sure notification queue release memory when drained

proxylib/Proxy.cpp, proxylib/Proxy.h, syncd/NotificationHandler.cpp, syncd/NotificationHandler.h, syncd/Syncd.cpp, syncd/Workaround.cpp, syncd/Workaround.h, unittest/syncd/TestNotificationHandler.cpp, unittest/syncd/TestWorkaround.cpp
Adding new field in port status notification is breaking
change and can cause some issues when getting notification
from older SAI library, this will add workaround to handle
that case
=> [syncd] Add workaround for port error status notification

lib/RedisRemoteSaiInterface.cpp, lib/RedisRemoteSaiInterface.h, lib/Sai.cpp, syncd/tests/TestSyncdMlnx.cpp
Manually cherry-pick this PR: https://github.com/sonic-net/sonic-sairedis/pull/1421
The counters for syncd (switch chip) were attempted to be added to gbsyncd (gearbox phys), and vice versa. This issue is introduced by #1362 When setting the redis attribute SAI_REDIS_SWITCH_ATTR_FLEX_COUNTER_GROUP and
SAI_REDIS_SWITCH_ATTR_FLEX_COUNTER, the operation is applied to every contexts (both syncd and gbsyncd). However, the counters to initialize could only exist in one context.
The fix is to check that the target switch id exists in a specific context, for the set operation of any redis type attribute; if not, skip the set on that context.
Before the fix, we see the error below in syslog
ERR gbsyncd#syncd: :- processFlexCounterEvent: port VID oid:0x1000000000002, was not found (probably port …
=> [202405] Fix adding flex counter to wrong context (#1421)

pyext/pysairedis.i, unittest/syncd/TestSyncd.cpp
There are two issues causing compilation failures of sairedis on Buster. Since the SONiC PTF container is still based on Buster, sairedis still needs to compile for Buster.
For the first issue, when generating Python bindings through SWIG on Buster, the `sai_struct_member_info_t` and `sai_object_type_info_t` struct cause issues during compilation on Buster. The errors stem from function pointers being used, but I'm not certain on the exact reason why these two specific structs have issues.
Instead of debugging further at this point, skip these two structs for now. We won't need it in the near future. Alternatively, once the Buster build is no longer needed, these lines can be removed.
For the second issue, the `TestSyncd.cpp` file uses the `MOCK_METHOD` macro. However, this macro is …
=> Fix compilation on Buster

.azure-pipelines/build-template.yml
sonic-swss-common introduced nested directory in common/c-api and it causes gcovr to write output file in non existing directory this fix replaces all / to - for all gcovr output files to be in the same directory
=> [azpipeline] Fix gcovr nested directory

syncd/CommandLineOptions.cpp, syncd/CommandLineOptions.h, syncd/CommandLineOptionsParser.cpp, syncd/FlexCounter.cpp, syncd/FlexCounter.h, syncd/FlexCounterManager.cpp, syncd/FlexCounterManager.h, syncd/Syncd.cpp, syncd/scripts/syncd_init_common.sh, unittest/syncd/TestCommandLineOptions.cpp, unittest/syncd/TestFlexCounter.cpp
Do not poll counters in bulk mode during initialization for objects that support bulk per CLI option
1. Read the counter groups that support bulk mode from `CONFIG_DB.DEVICE_METADATA|localhost.supporting_bulk_counter_groups`
2. Generate CLI options to syncd
3. Based on CLI options syncd records the counter groups that support bulk mode. For those objects, we do not need to poll them in bulk mode during initialization
=> Do not poll counters in bulk mode during initialization for objects that support bulk per CLI option

lib/Recorder.cpp, lib/Recorder.h, lib/RedisRemoteSaiInterface.cpp, saiplayer/SaiPlayer.cpp
Use a different letter to represent counter polling in sairedis.rec to avoid saiplayer crash
The character `s` was used for counter-polling polling which failed saiplayer because the format differed.
Now the character `p` is used to avoid failure. The saiplayer ignores `p`.
=> Use a different letter to represent counter polling in sairedis.rec to avoid saiplayer crash

syncd/scripts/syncd_init_common.sh
Backported PR #1420 from master to 202405.
=> [PATCH] [Marvell] Add Flag to identify SONiC related Init Handling

unittest/meta/TestNotificationSwitchAsicSdkHealthEvent.cpp
Related to https://github.com/sonic-net/sonic-buildimage/issues/19760.
Tests added to rule out v13 and v14 headers health_data stack shift influencing timestamp.
=> [test] Add more testing for NotificationSwitchAsicSdkHealthEvent

syncd/scripts/syncd_init_common.sh
=======
this is one of the dependent set of PRs being raised for changing the innovium asic type to marvell-teralynx
=======
syncd based logging enablement inside syncd docker and its related asic type checks are modified as per the renaming
==========
Verfify syncd docker configs are applied properly in teralynx platform
=> [Marvell] platform renaming for innovium

meta/Meta.cpp, meta/Meta.h, unittest/meta/TestMeta.cpp
Use metadata for validation instead of hard coded values
=> [meta] Use metadata to check port notification port_id type

syncd/AttrVersionChecker.cpp, syncd/AttrVersionChecker.h, syncd/CommandLineOptions.cpp, syncd/CommandLineOptions.h, syncd/CommandLineOptionsParser.cpp, syncd/HardReiniter.cpp, syncd/HardReiniter.h, syncd/Makefile.am, syncd/SaiDiscovery.cpp, syncd/SaiDiscovery.h, syncd/SaiSwitch.cpp, syncd/SaiSwitch.h, syncd/SingleReiniter.cpp, syncd/SingleReiniter.h, syncd/Syncd.cpp, tests/aspell.en.pws, tests/utils.pm, unittest/syncd/Makefile.am, unittest/syncd/TestAttrVersionChecker.cpp, unittest/syncd/TestCommandLineOptions.cpp
By default disabled. If enabled, it will use SAI metadata and libsai version returned by sai_api_version_query to verify if given attribute during SAI discovery process was introduced in the current libsai version or below that version.
This feature is partial solution to this problem:
https://github.com/sonic-net/sonic-buildimage/issues/20725, more here: https://github.com/opencomputeproject/SAI/issues/2099
=> [syncd] Add attribute version check feature

meta/SaiInterface.cpp, meta/SaiInterface.h, meta/SaiOptions.h, syncd/HardReiniter.cpp, syncd/HardReiniter.h, syncd/SaiDiscovery.cpp, syncd/SaiDiscovery.h, syncd/SaiSwitch.cpp, syncd/SaiSwitch.h, syncd/SingleReiniter.cpp, syncd/SingleReiniter.h, syncd/Syncd.cpp, syncd/VendorSaiOptions.h, tests/aspell.en.pws, unittest/meta/TestSaiInterface.cpp
And SaiOptions interface, for easy passing parameters over Sai objects
This will simplify passing parameters over different objects that have SaiInterface.
=> [syncd] Introduce VendorSaiOptions class

syncd/scripts/syncd_init_common.sh
syncd_init_common.sh is checking fast-reboot by reading /proc/cmdline. However, /proc/cmdline will not change after config reload. So, consider a case like fast-reboot -> config reload. In the config reload process, syncd_init_common.sh will also treat it as fast-reboot and probably enter wrong logic.
=> Use temp view also in fast-reboot

unittest/syncd/TestSyncd.cpp
There is issue causing compilation failures of sairedis on Buster. Since the SONiC PTF container is still based on Buster, sairedis still needs to compile for Buster.
The TestSyncd.cpp file uses the MOCK_METHOD macro. However, this macro is available only from version 1.10 of gmock, but Buster has version 1.8.1. As a simple fix, check to see if MOCK_METHOD is defined; if not, then don't compile this test.
=> [202405] Fix compilation error on Buster

syncd/scripts/syncd_init_common.sh
What i did
=======
this is one of the dependent set of PRs being raised for changing the marvell asic type to marvell-prestera
How i did
=======
syncd based logging enablement inside syncd docker and its related asic type checks are modified as per the renaming
How to verify
==========
Verfify syncd docker configs are applied properly in marvell-prestera platform
=> platform/marvell renaming to platform/marvell-prestera

syncd/FlexCounter.cpp, syncd/FlexCounter.h
Fixes issue: https://github.com/sonic-net/sonic-buildimage/issues/21232
In MACSEC there are two set of counters one for INGRESS another for EGRESS which gets mapped to the same COUNTER type - CounterType::MACSEC_SA ( https://github.com/sonic-net/sonic-swss/blob/c20902f3195b5bf8a941045e131aa1b863b69fd0/orchagent/macsecorch.cpp#L2145 )
In the releases after 202205 we started seeing this behavior where the MACSEC RX counters were missing as mentioned in the issue 21232.  Further debugging pointed to issue seen after this PR : https://github.com/sonic-net/sonic-sairedis/pull/1073 was merged.
In this case when macsec orch tries to addCounter for INGRESS SA after the EGRESS SA, and it don't go through as the m_supportedCounters is not empty.
For a fix I am removing the check in …
=> Fix to not miss the entire set of counters to be added in addObject for CounterContext::updateSupportedCount

.azure-pipelines/build-template.yml, .azure-pipelines/test-docker-sonic-vs-template.yml
On arm64 (and maybe sometimes amd64), rsyslogd appears to need a second or two to actually fully exit. The current code expects it to exit practically instantly. Add a sleep of 2 seconds to give it some time. Also enable some logging so that the commands being run can be seen.
Also, fix an error related to libswsscommon not getting installed due to new dependencies being added. Solve this by using apt install to install the package, which brings in any necessary dependencies.
=> Fix pipeline errors related to rsyslogd and libswsscommon installation

.azure-pipelines/build-template.yml, .azure-pipelines/test-docker-sonic-vs-template.yml
1. Use sonictest pool instead of sonic-common
2. Fix arm64 build error.
=> Use sonictest pool instead of sonic-common and fix arm64 issue.

lib/sairedis.h
Define bulk chunk size and bulk chunk size per counter ID.
This is to resolve the VS test failure in #1457, which is caused by loop dependency.
In PR #1457, new fields `bulk_chunk_size` and `bulk_chunk_size_per_prefix` have been introduced to `sai_redis_flex_counter_group_parameter_t` whose instances are initialized by orchagent.
However, the orchagent is still compiled with the old sairedis header, which prevents both new fields from being uninitialized which in turn fails vs test.
We have to split this PR into two:
1. #1519 which updates the header sairedis.h only. the motivation is to compile swss(orchagent) with both new fields initiated.
2. #1457 contains all the rest of code
The order to merge:
1. #1519
2. https://github.com/sonic-net/sonic-swss/pull/3391
3. #1457
=> Define bulk chunk size and bulk chunk size per counter ID

.azure-pipelines/test-docker-sonic-vs-template.yml, lib/sai_redis_interfacequery.cpp, syncd/VendorSai.cpp, unittest/lib/test_sai_redis_interfacequery.cpp, unittest/syncd/TestVendorSai.cpp, unittest/vslib/test_sai_vs_interfacequery.cpp, vslib/sai_vs_interfacequery.cpp
Fixes: https://github.com/sonic-net/sonic-buildimage/issues/21180
=> [syncd] Move logSet logGet under mutex to prevent race condition

lib/RedisRemoteSaiInterface.cpp, syncd/FlexCounter.cpp, syncd/FlexCounter.h, tests/aspell.en.pws, unittest/syncd/TestFlexCounter.cpp
**What I did**
Optimize the counter-polling performance in terms of polling interval accuracy
1. Enable bulk counter-polling to run at a smaller chunk size
There is one counter-polling thread for each counter group. All such threads can compete for the critical sections at the vendor SAI level, which means a counter-polling thread can wait for a critical section if another thread has been in it, which introduces latency for the waiting counter group.
An example is the competition between the PFC watchdog and the port counter groups.
The port counter group contains many counters and is polled in a bulk mode which takes a relatively longer time. The PFC watchdog counter group contains only a few counters but is polled at a short interval. Sometimes, PFC watchdog counters need to wait before …
=> Optimize counter polling interval by making it more accurate

syncd/VendorSai.cpp, unittest/syncd/TestVendorSai.cpp
Revert "Do not enter vendor SAI critical section for counter polling/clearing operations (#1450)"
This reverts commit 0317b16e4fdccf769c77a7b164ff90c1365c7d4e.
=> Revert "Do not enter vendor SAI critical section for counter polling/clearing operations (#1450)"

syncd/Syncd.cpp, unittest/syncd/TestSyncd.cpp
Backport commit https://github.com/sonic-net/sonic-sairedis/pull/1492.
Log level should be warning instead of error, because functionality is fine. Latter code will fall back to use single api instead of bulk api, when syncd support bulk but sai doesn't support it.
When syncd added support for bulk APIs like bulk set, but sai didn't implement it, this error will be printed:
"processBulkOidSet: bulk set api is not implemented or not supported, object_type = SAI_OBJECT_TYPE_QUEUE", and it will fail the cases. Actually the print should be warning, as in current code, bulk set fall back to single set in latter code, so sai will still receive single set APIs, so functionality is actually OK.
Update log level from error to warning.
When bulk set api is added in syncd, but sai did not implement …
=> [202411] Backport: [syncd] Update log level for bulk api

syncd/scripts/syncd_init_common.sh
Use CMD `syncd_dash` in place of `syncd` while kvm sonic is running as kvm DPU
=> [dash] Use CMD syncd_dash for kvm dpu

.azure-pipelines/test-docker-sonic-vs-template.yml, syncd/VendorSai.cpp, unittest/syncd/TestVendorSai.cpp
* [syncd] Move logSet logGet under mutex to prevent race condition
Fixes: https://github.com/sonic-net/sonic-buildimage/issues/21180
=> [syncd] Move logSet logGet under mutex to prevent race condition (#1520)

syncd/tests/TestSyncdMlnx.cpp, unittest/vslib/TestSwitchStateBase.cpp, vslib/SwitchStateBase.cpp
Generic Hash feature:
update ECMP/LAG hash VS lib with SAI_NATIVE_HASH_FIELD_IPV6_FLOW_LABEL
Updated VS unittest tests
=> [hash] update ECMP/LAG hash VS lib with SAI_NATIVE_HASH_FIELD_IPV6_FLOW_LABEL

syncd/FlexCounter.cpp, unittest/syncd/TestFlexCounter.cpp, unittest/vslib/TestSwitchMLNX2700.cpp, unittest/vslib/TestVirtualSwitchSaiInterface.cpp, vslib/SwitchStateBase.cpp, vslib/VirtualSwitchSaiInterface.cpp
Fix two day 1 counter issues on VS platform which have been exposed recently.
1. Use switch object to detect counter capability in flex counter. This is to fix the following error message
```
E               2025 Feb 20 15:43:21.906623 vlab-03 ERR syncd#syncd: :- queryStatsCapability: parameter switchId oid:0x100000001 object type is SAI_OBJECT_TYPE_PORT, but expected SAI_OBJECT_TYPE_SWITCH
E               
E               2025 Feb 20 15:43:21.910428 vlab-03 ERR syncd#syncd: :- queryStatsCapability: parameter switchId oid:0x1500000003 object type is SAI_OBJECT_TYPE_QUEUE, but expected SAI_OBJECT_TYPE_SWITCH
```
2. Support PFC counters on VS platform
Previously it didn't check counter capability before polling PFC counters by mistake.
3. Do not poll counters for a group without any counter …
=> Fix counter issues on VS platform

lib/RedisRemoteSaiInterface.cpp, syncd/FlexCounter.cpp, syncd/FlexCounter.h, tests/aspell.en.pws, unittest/syncd/TestFlexCounter.cpp
What I did
This is to backport PR #1457 to 202411 branch
Optimize the counter-polling performance in terms of polling interval accuracy
Enable bulk counter-polling to run at a smaller chunk size There is one counter-polling thread for each counter group. All such threads can compete for the critical sections at the vendor SAI level, which means a counter-polling thread can wait for a critical section if another thread has been in it, which introduces latency for the waiting counter group. An example is the competition between the PFC watchdog and the port counter groups. The port counter group contains many counters and is polled in a bulk mode which takes a relatively longer time. The PFC watchdog counter group contains only a few counters but is polled at a short interval. Sometimes, …
=> [202411] Optimize counter polling interval by making it more accurate (Backport PR #1457)

unittest/vslib/TestSwitchConfig.cpp, vslib/Sai.cpp, vslib/SwitchConfig.cpp, vslib/SwitchConfig.h, vslib/SwitchStateBase.cpp, vslib/saivs.h
This PR adds two features to `vslib`.
- `SAI_KEY_VS_OPER_SPEED_IS_CONFIGURED_SPEED`: when `true`, `SAI_PORT_ATTR_SPEED` returns the configured speed instead of the value retrieved via [`/sys/class/net/<name>/speed`](https://github.com/sonic-net/sonic-sairedis/blob/master/vslib/SwitchStateBaseHostif.cpp#L892-L893). 
- fixes https://github.com/sonic-net/sonic-buildimage/issues/19735
- `SAI_PORT_ATTR_HOST_TX_READY_STATUS`: always returns `true`. Required to support running `xcvrd` in the VS env.
- ref: https://github.com/sonic-net/SONiC/pull/1849/files#diff-6f3e95e6c57a3edc2e30e1f13edb9fd9a32a0db44e1035ac1f0b1b9a191762a5R46
=> [vslib] SAI_KEY_VS_OPER_SPEED_IS_CONFIGURED_SPEED, SAI_PORT_ATTR_HOST_TX_READY_STATUS support

vslib/Sai.cpp, vslib/SwitchConfig.cpp, vslib/SwitchConfig.h, vslib/SwitchStateBase.cpp, vslib/saivs.h
Adding support for SAI_SWITCH_ATTR_SUPPORTED_IPV4_BFD_SESSION_OFFLOAD_TYPE and SAI_SWITCH_ATTR_SUPPORTED_IPV6_BFD_SESSION_OFFLOAD_TYPE in vslib. This is needed by BfdOrch in sonic-swss to choose between software BFD or regular (offloaded) BFD.
Default will be to return SAI_BFD_SESSION_OFFLOAD_TYPE_FULL, as this was the default behavior previously when this value was not checked. 
Added capability to return SAI_BFD_SESSION_OFFLOAD_TYPE_NONE by setting SAI_VS_BFD_OFFLOAD_SUPPORTED=false in sai.profile for testing and in cases where software BFD is desired.
=> Update to support SAI BFD_SESSION_OFFLOAD_TYPE.

.azure-pipelines/build_and_install_module.sh
sonic-sairedis will checkout sonic-swss to do vstest but using local build_and_install_module.sh to setup test environment, which is out of date with newer Linux kernel version.
The build_and_install_module.sh in sonic-swss is up to date with latest Ubuntu 20.04, so we need to update the build sh file with the file in sonic-swss.
In a long term, we may need to do some automatically sync, but now we have some azure agent security issue need to fix immediately, so just update the build_and_install_module.sh manually.
=> Update build_and_install_module.sh to match newer Linux kernel version

vslib/SwitchStateBase.cpp
Support auto negotiation on the VS platform to avoid error messages.
=> Support auto negotiation on the VS platform to avoid error messages.

syncd/FlexCounter.cpp, unittest/syncd/TestFlexCounter.cpp
Enhance the logic to check the capability of the bulk counter poll in `bulkAddObject`
1. Check bulk capability using m_vendorSai->queryStatsCapability before calling SAI API to check capability
2. Check single call capability before adding it to `m_objectIdsMap`
3. Reduce the log severity to `INFO` when a counter is not supported to be bulk-polled to avoid too many log messages
4. Remove redundant code for buffer pool counters
Details:
In `bulkAddObject` it enables counter polling for a set of objects. A brief flow is the following:
1. Check the object type's counter capability of single operation (`SAI_STATS_MODE_READ_AND_CLEAR` or `SAI_STATS_MODE_READ`) using `updateSupportedCounters` (which eventually calls `query_stats_capability`). All counters that do not support the capability will …
=> Enhance the logic to check capability of bulk counter poll

.github/workflows/codeql-analysis.yml
Update the CodeQL runner Ubuntu version. This is to address the following:
```
This is a scheduled Ubuntu 20.04 retirement. Ubuntu 20.04 LTS runner will be removed on 2025-04-15. For more details, see https://github.com/actions/runner-images/issues/11101
```
=> Update codeql runs-on ubuntu version to 22.04

syncd/scripts/syncd_init_common.sh
Enable ACL multi-binding for Dual-ToR scenario
=> [ACL] Enable ACL multi-binding for Dual-ToR setups

syncd/FlexCounter.cpp, unittest/syncd/TestFlexCounter.cpp
Move the timestamp out of the COUNTER table to avoid updating the table too frequently and overwhelming the telemetry system.
Fixes https://github.com/sonic-net/sonic-buildimage/issues/22201
=> Move time stamp to time stamp table in counter database to avoid frequently update the counter table

unittest/lib/TestServerSai.cpp
Use `#ifdef MOCK_METHOD` to conditionally enable TestServerSaiMockChannel. This macro is introduced in gmock 1.10, however slave buster has older version of gmock 1.8, within which compiling `unittest/lib/TestServerSai.cpp` fails.
=> [unittest ]Conditionally enable TestServerSaiMockChannel

configure.ac, syncd/VendorSai.cpp, tests/TestClient.cpp, unittest/syncd/TestVendorSai.cpp
Check if sai_query_stats_st_capability sai_tam_telemetry_get_data is defined whilie configure to make sure if vendor is not implementing those new APIs then it will still link syncd for VendorSai.cpp
=> [syncd] Check whether stat_st and tam_telemetry is defined

syncd/scripts/syncd_init_common.sh
This configuration will be applied by a separate systemd service on system start.
=> [nvidia-bluefield] Remove switchdev configuration from syncd init.

meta/DummySaiInterface.cpp, meta/Makefile.am, meta/Meta.cpp, meta/Meta.h, meta/NotificationFactory.cpp, meta/NotificationIcmpEchoSessionStateChange.cpp, meta/NotificationIcmpEchoSessionStateChange.h, meta/SaiSerialize.cpp, meta/sai_serialize.h, proxylib/Proxy.cpp, proxylib/Proxy.h, pyext/pysairedis.cpp, pyext/pysairedis.i, saiplayer/SaiPlayer.cpp, saiplayer/SaiPlayer.h, syncd/NotificationHandler.cpp, syncd/NotificationHandler.h, syncd/NotificationProcessor.cpp, syncd/NotificationProcessor.h, syncd/SwitchNotifications.cpp, syncd/SwitchNotifications.h, syncd/Syncd.cpp, unittest/meta/Makefile.am, unittest/meta/TestDummySaiInterface.cpp, unittest/meta/TestNotificationIcmpEchoSessionStateChange.cpp, unittest/proxylib/TestProxy.cpp, unittest/proxylib/TestSai.cpp, unittest/syncd/TestNotificationHandler.cpp, unittest/syncd/TestNotificationProcessor.cpp, vslib/SwitchStateBase.cpp
Added support for ICMP_ECHO_SESSION in following areas of sonic-sairedis
meta layer
syncd
Notification Handling
added unittest to test notification and attribute handling
=> ICMP_ECHO_SESSION meta and notification layer changes

meta/Meta.cpp
bulk operations do not continue when SAI_BULK_OP_ERROR_MODE_IGNORE_ERROR is set and an error occurs. Create new check that considers the mode when validating bulk operations.
fixes a crash in https://github.com/sonic-net/sonic-buildimage/issues/21243 because route entries that are not removed in syncd by bulker are assumed to be removed in orchagent. Then when the nexthops are attempting to be removed, orchagent crashes due to OBJECT_IN_USE.
=> [meta] do not fail bulk operations if MODE_IGNORE_ERROR

configure.ac
Temporary workaround we are using internally for 720DT and DNX devices which are hitting:
`INFO gbsyncd#supervisord: syncd /usr/bin/syncd: symbol lookup error: /usr/bin/syncd: undefined symbol: sai_query_stats_st_capability#015`
as described in https://github.com/sonic-net/sonic-buildimage/issues/23387
=> [broadcom platforms] Temporary workaround for undefined symbol: sai_query_stats_st_capability error

.azure-pipelines/build-docker-sonic-vs-template.yml, .azure-pipelines/build-swss-template.yml, .azure-pipelines/build-template.yml, .azure-pipelines/test-docker-sonic-vs-template.yml
Cherry-pick #1605 to 202411.
The VS test stage of PR tests pipeline has been failing. The reason is that one of the VS test step is to download ubuntu deb packages built from an upstream pipeline. The upstream pipeline has been renamed from sonic-net.sonic-buildimage-ubuntu20.04 to sonic-net.sonic-buildimage-ubuntu22.04 because of the deprecation of Ubuntu 20.04.
This pipeline needs to be updated according to use the new upstream pipeline name for artifacts downloading.
This change also deprecated a parameter `sonic_buildimage_ubuntu20_04 which is not really necessary.
* Fixed conflicts in .azure-pipelines/test-docker-sonic-vs-template.yml
=> [202411]: Update upstream pipeline name to fix VS test issue.

meta/SaiInterface.cpp, unittest/meta/TestSaiInterface.cpp
Adding support for create, remove, get, and set of SAI_OBJECT_TYPE_L2MC_ENTRY and SAI_OBJECT_TYPE_IPMC_ENTRY.  This is verified by the unit tests in TestSaiInterface.cpp.
=> Add support for IPMC and L2MC Entry
